from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QDateTime

class Ui_Form(object):
    def setupUi(self, Form, frame, tela):
        self.frame =frame
        self.tela = tela
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(2, 2, 269, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label.setStyleSheet("border:none;")
        self.label_RESERVADOS = QtWidgets.QLabel(parent=self.frame)
        self.label_RESERVADOS.setStyleSheet("border:none;")
        self.label_RESERVADOS.setGeometry(QtCore.QRect(60, 50, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_RESERVADOS.setFont(font)
        self.label_RESERVADOS.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_RESERVADOS.setObjectName("label_RESERVADOS")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setGeometry(QtCore.QRect(2, 50, 41, 31))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 0);border:none;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.VALOR_R = QtWidgets.QLabel(parent=self.frame)
        self.VALOR_R.setGeometry(QtCore.QRect(200, 50, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.VALOR_R.setFont(font)
        self.VALOR_R.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);border: none;")
        self.VALOR_R.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.VALOR_R.setObjectName("VALOR_R")
        self.label_VAGOS = QtWidgets.QLabel(parent=self.frame)
        self.label_VAGOS.setGeometry(QtCore.QRect(60, 110, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_VAGOS.setFont(font)
        self.label_VAGOS.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_VAGOS.setObjectName("label_VAGOS")
        self.label_VAGOS.setStyleSheet("border:none;")
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        self.frame_3.setGeometry(QtCore.QRect(2, 110, 41, 31))
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"background-color: rgb(85, 170, 0);border:none;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.VALOR_V = QtWidgets.QLabel(parent=self.frame)
        self.VALOR_V.setGeometry(QtCore.QRect(200, 110, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.VALOR_V.setFont(font)
        self.VALOR_V.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);border: none;")
        self.VALOR_V.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.VALOR_V.setObjectName("VALOR_V")
        self.label_OCUPADOS = QtWidgets.QLabel(parent=self.frame)
        self.label_OCUPADOS.setGeometry(QtCore.QRect(60, 170, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_OCUPADOS.setFont(font)
        self.label_OCUPADOS.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_OCUPADOS.setObjectName("label_OCUPADOS")
        self.label_OCUPADOS.setStyleSheet("border:none;")
        self.frame_5 = QtWidgets.QFrame(parent=self.frame)
        self.frame_5.setGeometry(QtCore.QRect(2, 170, 41, 31))
        self.frame_5.setStyleSheet("background-color: rgb(255, 0, 0);border:none;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.VALOR_O = QtWidgets.QLabel(parent=self.frame)
        self.VALOR_O.setGeometry(QtCore.QRect(200, 170, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.VALOR_O.setFont(font)
        self.VALOR_O.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);border: none;")
        self.VALOR_O.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.VALOR_O.setObjectName("VALOR_O")
        self.label_BLOQUEADOS = QtWidgets.QLabel(parent=self.frame)
        self.label_BLOQUEADOS.setGeometry(QtCore.QRect(60, 230, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_BLOQUEADOS.setFont(font)
        self.label_BLOQUEADOS.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_BLOQUEADOS.setObjectName("label_BLOQUEADOS")
        self.label_BLOQUEADOS.setStyleSheet("border:none;")
        self.frame_6 = QtWidgets.QFrame(parent=self.frame)
        self.frame_6.setGeometry(QtCore.QRect(2, 230, 41, 15))
        self.frame_6.setStyleSheet("background-color: rgb(85, 85, 255);border:none;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.VALOR_B = QtWidgets.QLabel(parent=self.frame)
        self.VALOR_B.setGeometry(QtCore.QRect(200, 230, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.VALOR_B.setFont(font)
        self.VALOR_B.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);border: none;")
        self.VALOR_B.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.VALOR_B.setObjectName("VALOR_B")
        self.frame_7 = QtWidgets.QFrame(parent=self.frame)
        self.frame_7.setGeometry(QtCore.QRect(2, 245, 41, 15))
        self.frame_7.setStyleSheet("background-color: rgb(0, 170, 255);border:none;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(2, 290, 269, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_2.setStyleSheet("border:none;")
        self.label_RESERVADOS_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_RESERVADOS_2.setGeometry(QtCore.QRect(60, 340, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_RESERVADOS_2.setFont(font)
        self.label_RESERVADOS_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_RESERVADOS_2.setObjectName("label_RESERVADOS_2")
        self.label_RESERVADOS_2.setStyleSheet("border:none;")
        self.frame_8 = QtWidgets.QFrame(parent=self.frame)
        self.frame_8.setGeometry(QtCore.QRect(2, 340, 41, 31))
        self.frame_8.setStyleSheet("background-color: rgb(85, 85, 255);border:none;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.VALOR_R_2 = QtWidgets.QLabel(parent=self.frame)
        self.VALOR_R_2.setGeometry(QtCore.QRect(200, 340, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.VALOR_R_2.setFont(font)
        self.VALOR_R_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);border: none;")
        self.VALOR_R_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.VALOR_R_2.setObjectName("VALOR_R_2")
        self.label_RESERVADOS_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_RESERVADOS_3.setGeometry(QtCore.QRect(60, 370, 121, 31))
        self.label_RESERVADOS_3.setStyleSheet("border:none;")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_RESERVADOS_3.setFont(font)
        self.label_RESERVADOS_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_RESERVADOS_3.setObjectName("label_RESERVADOS_3")
        self.frame_9 = QtWidgets.QFrame(parent=self.frame)
        self.frame_9.setGeometry(QtCore.QRect(2, 370, 41, 31))
        self.frame_9.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"background-color: rgb(85, 170, 255);border:none;")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.VALOR_R_3 = QtWidgets.QLabel(parent=self.frame)
        self.VALOR_R_3.setGeometry(QtCore.QRect(200, 370, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.VALOR_R_3.setFont(font)
        self.VALOR_R_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);border: none;")
        self.VALOR_R_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.VALOR_R_3.setObjectName("VALOR_R_3")
        self.label_RESERVADOS_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_RESERVADOS_4.setGeometry(QtCore.QRect(60, 450, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_RESERVADOS_4.setStyleSheet("border:none;")
        self.label_RESERVADOS_4.setFont(font)
        self.label_RESERVADOS_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_RESERVADOS_4.setWordWrap(True)
        self.label_RESERVADOS_4.setObjectName("label_RESERVADOS_4")
        self.frame_10 = QtWidgets.QFrame(parent=self.frame)
        self.frame_10.setGeometry(QtCore.QRect(2, 400, 41, 51))
        self.frame_10.setStyleSheet("background-color: rgb(85, 85, 255);border:none;")
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.VALOR_R_4 = QtWidgets.QLabel(parent=self.frame)
        self.VALOR_R_4.setGeometry(QtCore.QRect(200, 450, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.VALOR_R_4.setFont(font)
        self.VALOR_R_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);border: none;")
        self.VALOR_R_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.VALOR_R_4.setObjectName("VALOR_R_4")
        self.label_RESERVADOS_5 = QtWidgets.QLabel(parent=self.frame)
        self.label_RESERVADOS_5.setGeometry(QtCore.QRect(60, 400, 121, 51))
        font = QtGui.QFont()
        self.label_RESERVADOS_5.setStyleSheet("border:none;")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_RESERVADOS_5.setFont(font)
        self.label_RESERVADOS_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_RESERVADOS_5.setWordWrap(True)
        self.label_RESERVADOS_5.setObjectName("label_RESERVADOS_5")
        self.VALOR_R_5 = QtWidgets.QLabel(parent=self.frame)
        self.VALOR_R_5.setGeometry(QtCore.QRect(200, 400, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.VALOR_R_5.setFont(font)
        self.VALOR_R_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);border: none;")
        self.VALOR_R_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.VALOR_R_5.setObjectName("VALOR_R_5")
        self.frame_11 = QtWidgets.QFrame(parent=self.frame)
        self.frame_11.setGeometry(QtCore.QRect(2, 450, 41, 41))
        self.frame_11.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"background-color: rgb(85, 170, 255);border:none;")
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setGeometry(QtCore.QRect(2, 510, 269, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border:none;")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("Form", "GLOBAL DE LEITOS"))
        self.label_RESERVADOS.setText(_translate("Form", "RESERVADOS"))
        valorr = str(self.tela.total_rese)
        self.VALOR_R.setText(_translate("Form", valorr))
        self.label_VAGOS.setText(_translate("Form", "VAGOS"))
        valorv = str(self.tela.total_vago)
        self.VALOR_V.setText(_translate("Form", valorv))
        self.label_OCUPADOS.setText(_translate("Form", "OCUPADOS"))
        valoro = str(self.tela.total_ocup)
        self.VALOR_O.setText(_translate("Form", valoro))
        self.label_BLOQUEADOS.setText(_translate("Form", "BLOQUEADOS"))
        valorb = str(self.tela.total_bloq)
        self.VALOR_B.setText(_translate("Form", valorb))
        self.label_2.setText(_translate("Form", "BLOQUEIO DE LEITOS"))
        self.label_RESERVADOS_2.setText(_translate("Form", "MANUTENÇÃO"))
        if self.tela.qt_bl_manu != 0 and valorb != '0':
            valor_m = "{:.2f} %".format(self.tela.qt_bl_manu / int(valorb) * 100)
        else:
            valor_m = '0.0 %'
        self.VALOR_R_2.setText(_translate("Form", valor_m))
        self.label_RESERVADOS_3.setText(_translate("Form", "VM/VNI"))
        if self.tela.qt_bl_VM_VNI != 0 and valorb != '0':
            valor_vm = "{:.2f} %".format(self.tela.qt_bl_VM_VNI / int(valorb) * 100)
        else:
            valor_vm = '0.0 %'

        self.VALOR_R_3.setText(_translate("Form", valor_vm))
        self.label_RESERVADOS_4.setText(_translate("Form", "PONTUAL FUNCIONÁRIO"))
        if self.tela.qt_pront != 0 and valorb != 0:
            valor_pont = "{:.2f} %".format(self.tela.qt_pront / int(valorb) * 100)
        else:
            valor_pont = '0.0 %'
        self.VALOR_R_4.setText(_translate("Form", valor_pont))
        self.label_RESERVADOS_5.setText(_translate("Form", "FALTA FUNCIONÁRIO"))
        if self.tela.qt_se_fun != 0 and valorb != 0:
            valor_fal = "{:.2f} %".format(self.tela.qt_se_fun / int(valorb) * 100)
        else:
            valor_fal = '0.0 %'
        self.VALOR_R_5.setText(_translate("Form", valor_fal))
        current_datetime = QDateTime.currentDateTime()
        formatted_date = current_datetime.toString("dd/MM/yyyy")
        formatted_time = current_datetime.toString("hh:mm:ss")

        self.label_3.setText(_translate("Form", f"IMPRESSÃO EM: {formatted_date} {formatted_time}"))