# Decompiled with PyLingual (https://pylingual.io)
# Internal filename: nono_LESTE_TRANSPLANTES.py
# Bytecode version: 3.12.0rc2 (3531)
# Source timestamp: 1970-01-01 00:00:00 UTC (0)

from PyQt6 import QtCore, QtGui, QtWidgets
import csv
from PyQt6.QtCore import QRect, Qt, QSettings, QStandardPaths, Qt
from PyQt6.QtWidgets import QLabel
from PyQt6.QtGui import QFont

class Ui_Form(object):
    def setupUi(self, Form, frame, tela):
        self.tela = tela
        self.form = Form
        self.frame_tela = frame
        self.frame_14 = QtWidgets.QFrame(parent=self.frame_tela)
        self.frame_14.setGeometry(QtCore.QRect(204, 63, 493, 171))
        self.frame_14.setStyleSheet('\nbackground-color: rgb(255, 255, 255);\nborder: none;')
        self.settings = QSettings('HC', 'SGL')
        script_directory = QStandardPaths.writableLocation(QStandardPaths.StandardLocation.AppDataLocation)
        config_file_path = f'{script_directory}/config.ini'
        self.settings = QSettings(config_file_path, QSettings.Format.IniFormat)
        self.frame_14.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_14.setObjectName('frame_14')
        self.frame_2 = QtWidgets.QFrame(parent=self.frame_tela)
        self.frame_2.setGeometry(QtCore.QRect(169, 230, 880, 40))
        self.frame_2.setStyleSheet('background-color: #c0c0c0;\n')
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName('frame_2')
        self.line_63 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_63.setGeometry(QtCore.QRect(554, 3, 1, 104))
        self.line_63.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_63.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_63.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_63.setObjectName('line_63')
        self.line_64 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_64.setGeometry(QtCore.QRect(512, 60, 109, 1))
        self.line_64.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_64.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_64.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_64.setObjectName('line_64')
        self.line_17 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_17.setGeometry(QtCore.QRect(510, 0, 3, 108))
        self.line_17.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_17.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_17.setObjectName('line_17')
        self.frame_43 = QtWidgets.QFrame(parent=self.frame_14)
        self.frame_43.setGeometry(QtCore.QRect(513, 61, 41, 50))
        self.frame_43.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_43.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_43.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_43.setObjectName('frame_43')
        self.line_118 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_118.setGeometry(QtCore.QRect(620, 2, 3, 108))
        self.line_118.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_118.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_118.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_118.setObjectName('line_118')
        self.frame_44 = QtWidgets.QFrame(parent=self.frame_14)
        self.frame_44.setGeometry(QtCore.QRect(691, 60, 38, 50))
        self.frame_44.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_44.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_44.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_44.setObjectName('frame_44')
        self.line_119 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_119.setGeometry(QtCore.QRect(620, 60, 109, 1))
        self.line_119.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_119.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_119.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_119.setObjectName('line_119')
        self.line_120 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_120.setGeometry(QtCore.QRect(690, 3, 1, 104))
        self.line_120.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_120.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_120.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_120.setObjectName('line_120')
        self.line_50 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_50.setGeometry(QtCore.QRect(42, 60, 3, 110))
        self.line_50.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_50.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_50.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_50.setObjectName('line_50')
        self.frame_36 = QtWidgets.QFrame(parent=self.frame_14)
        self.frame_36.setGeometry(QtCore.QRect(136, 95, 83, 81))
        self.frame_36.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_36.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_36.setObjectName('frame_36')
        self.line_52 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_52.setGeometry(QtCore.QRect(259, 2, 3, 90))
        self.line_52.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_52.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_52.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_52.setObjectName('line_52')
        self.line_81 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_81.setGeometry(QtCore.QRect(220, 90, 41, 3))
        self.line_81.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_81.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_81.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_81.setObjectName('line_81')
        self.line_55 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_55.setGeometry(QtCore.QRect(133, 90, 3, 81))
        self.line_55.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_55.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_55.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_55.setObjectName('line_55')
        self.line_56 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_56.setGeometry(QtCore.QRect(219, 90, 3, 79))
        self.line_56.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_56.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_56.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_56.setObjectName('line_56')
        self.line_58 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_58.setGeometry(QtCore.QRect(175, 0, 3, 92))
        self.line_58.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_58.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_58.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_58.setObjectName('line_58')
        self.line_85 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_85.setGeometry(QtCore.QRect(90, 90, 44, 3))
        self.line_85.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_85.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_85.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_85.setObjectName('line_85')
        self.frame_39 = QtWidgets.QFrame(parent=self.frame_14)
        self.frame_39.setGeometry(QtCore.QRect(45, 127, 47, 50))
        self.frame_39.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_39.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_39.setObjectName('frame_39')
        self.line_59 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_59.setGeometry(QtCore.QRect(0, 60, 45, 3))
        self.line_59.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_59.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_59.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_59.setObjectName('line_59')
        self.line_84 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_84.setGeometry(QtCore.QRect(0, 0, 3, 61))
        self.line_84.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_84.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_84.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_84.setObjectName('line_84')
        self.line_130 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_130.setGeometry(QtCore.QRect(90, 0, 3, 170))
        self.line_130.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_130.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_130.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_130.setObjectName('line_130')
        self.label = QtWidgets.QLabel(parent=self.frame_14)
        self.label.setGeometry(QtCore.QRect(362, 50, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet('color: white;\nbackground-color:BLACK;\nborder-color: transparent; \ntransform: rotate(270deg);')
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName('label')
        self.frame_13 = QtWidgets.QFrame(parent=self.frame_tela)
        self.frame_13.setGeometry(QtCore.QRect(697, 60, 351, 171))
        self.frame_13.setStyleSheet('\nbackground-color: rgb(255, 255, 255);\n                border-left: 2px solid black;\n                border-right: 2px solid black;\n                border-top: 2px solid black;\n')
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName('frame_13')
        self.frame_30 = QtWidgets.QFrame(parent=self.frame_13)
        self.frame_30.setGeometry(QtCore.QRect(661, 60, 38, 50))
        self.frame_30.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_30.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_30.setObjectName('frame_30')
        self.line_108 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_108.setGeometry(QtCore.QRect(590, 60, 109, 1))
        self.line_108.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_108.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_108.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_108.setObjectName('line_108')
        self.line_22 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_22.setGeometry(QtCore.QRect(260, 2, 3, 169))
        self.line_22.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_22.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_22.setObjectName('line_22')
        self.line_76 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_76.setGeometry(QtCore.QRect(262, 90, 44, 3))
        self.line_76.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_76.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_76.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_76.setObjectName('line_76')
        self.frame_32 = QtWidgets.QFrame(parent=self.frame_13)
        self.frame_32.setGeometry(QtCore.QRect(308, 125, 41, 50))
        self.frame_32.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_32.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_32.setObjectName('frame_32')
        self.line_40 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_40.setGeometry(QtCore.QRect(306, 90, 3, 79))
        self.line_40.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_40.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_40.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_40.setObjectName('line_40')
        self.frame_33 = QtWidgets.QFrame(parent=self.frame_13)
        self.frame_33.setGeometry(QtCore.QRect(91, 125, 41, 50))
        self.frame_33.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_33.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_33.setObjectName('frame_33')
        self.line_41 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_41.setGeometry(QtCore.QRect(133, 168, 45, 3))
        self.line_41.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_41.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_41.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_41.setObjectName('line_41')
        self.line_42 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_42.setGeometry(QtCore.QRect(132, 90, 3, 81))
        self.line_42.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_42.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_42.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_42.setObjectName('line_42')
        self.line_77 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_77.setGeometry(QtCore.QRect(133, 90, 44, 3))
        self.line_77.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_77.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_77.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_77.setObjectName('line_77')
        self.frame_34 = QtWidgets.QFrame(parent=self.frame_13)
        self.frame_34.setGeometry(QtCore.QRect(219, 125, 41, 50))
        self.frame_34.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_34.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_34.setObjectName('frame_34')
        self.line_43 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_43.setGeometry(QtCore.QRect(177, 168, 45, 3))
        self.line_43.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_43.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_43.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_43.setObjectName('line_43')
        self.line_44 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_44.setGeometry(QtCore.QRect(220, 90, 3, 79))
        self.line_44.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_44.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_44.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_44.setObjectName('line_44')
        self.line_78 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_78.setGeometry(QtCore.QRect(178, 90, 44, 3))
        self.line_78.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_78.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_78.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_78.setObjectName('line_78')
        self.line_46 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_46.setGeometry(QtCore.QRect(176, 0, 3, 93))
        self.line_46.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_46.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_46.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_46.setObjectName('line_46')
        self.line_47 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_47.setGeometry(QtCore.QRect(90, 0, 3, 170))
        self.line_47.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_47.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_47.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_47.setObjectName('line_47')
        self.line_590 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_590.setGeometry(QtCore.QRect(0, 0, 261, 3))
        self.line_590.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_590.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_590.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_590.setObjectName('line_590')
        self.frame_35 = QtWidgets.QFrame(parent=self.frame_13)
        self.frame_35.setGeometry(QtCore.QRect(2, 125, 42, 50))
        self.frame_35.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_35.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_35.setObjectName('frame_35')
        self.line_49 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_49.setGeometry(QtCore.QRect(44, 90, 3, 81))
        self.line_49.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_49.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_49.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_49.setObjectName('line_49')
        self.line_79 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_79.setGeometry(QtCore.QRect(46, 90, 44, 3))
        self.line_79.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_79.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_79.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_79.setObjectName('line_79')
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_tela)
        self.frame_6.setGeometry(QtCore.QRect(1064, 110, 199, 161))
        self.frame_6.setStyleSheet('background-color: rgb(255, 255, 255);\nborder: 2px solid #2E3D48')
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName('frame_6')
        self.label_ocupado1_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_ocupado1_3.setGeometry(QtCore.QRect(10, 130, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_ocupado1_3.setFont(font)
        self.label_ocupado1_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_ocupado1_3.setObjectName('label_ocupado1_3')
        self.label_tabela_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_tabela_3.setGeometry(QtCore.QRect(10, 10, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_tabela_3.setFont(font)
        self.label_tabela_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_tabela_3.setObjectName('label_tabela_3')
        self.qt_vago_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.qt_vago_3.setGeometry(QtCore.QRect(130, 40, 61, 21))
        font = QtGui.QFont()
        self.qt_vago_3.setFont(font)
        self.qt_vago_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.qt_vago_3.setObjectName('qt_vago_3')
        self.label_bloq1_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_bloq1_3.setGeometry(QtCore.QRect(10, 100, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_bloq1_3.setFont(font)
        self.label_bloq1_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_bloq1_3.setObjectName('label_bloq1_3')
        self.qt_reservado_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.qt_reservado_3.setGeometry(QtCore.QRect(130, 70, 61, 21))
        font = QtGui.QFont()
        self.qt_reservado_3.setFont(font)
        self.qt_reservado_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.qt_reservado_3.setObjectName('qt_reservado_3')
        self.qt_bloqueado_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.qt_bloqueado_3.setGeometry(QtCore.QRect(130, 100, 61, 21))
        font = QtGui.QFont()
        self.qt_bloqueado_3.setFont(font)
        self.qt_bloqueado_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.qt_bloqueado_3.setObjectName('qt_bloqueado_3')
        self.label_reser1_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_reser1_3.setGeometry(QtCore.QRect(10, 70, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_reser1_3.setFont(font)
        self.label_reser1_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_reser1_3.setObjectName('label_reser1_3')
        self.qt_ocupado_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.qt_ocupado_3.setGeometry(QtCore.QRect(130, 130, 61, 21))
        font = QtGui.QFont()
        self.qt_ocupado_3.setFont(font)
        self.qt_ocupado_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.qt_ocupado_3.setObjectName('qt_ocupado_3')
        self.label_vago1_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_vago1_3.setGeometry(QtCore.QRect(10, 40, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_vago1_3.setFont(font)
        self.label_vago1_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_vago1_3.setObjectName('label_vago1_3')
        self.frame = QtWidgets.QFrame(parent=self.frame_tela)
        self.frame.setGeometry(QtCore.QRect(169, 270, 881, 171))
        self.frame.setStyleSheet('                border-left: 2px solid black;\nbackground-color: rgb(255, 255, 255);\n                border-bottom: 2px solid black;\n                border-right: 2px solid black;\n')
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName('frame')
        self.line_18 = QtWidgets.QFrame(parent=self.frame)
        self.line_18.setGeometry(QtCore.QRect(349, 0, 3, 170))
        self.line_18.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_18.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_18.setObjectName('line_18')
        self.line_67 = QtWidgets.QFrame(parent=self.frame)
        self.line_67.setGeometry(QtCore.QRect(40, 0, 3, 42))
        self.line_67.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_67.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_67.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_67.setObjectName('line_67')
        self.line_69 = QtWidgets.QFrame(parent=self.frame)
        self.line_69.setGeometry(QtCore.QRect(0, 40, 43, 3))
        self.line_69.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_69.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_69.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_69.setObjectName('line_69')
        self.frame_51 = QtWidgets.QFrame(parent=self.frame)
        self.frame_51.setGeometry(QtCore.QRect(43, 33, 41, 48))
        self.frame_51.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_51.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_51.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_51.setObjectName('frame_51')
        self.frame_24 = QtWidgets.QFrame(parent=self.frame)
        self.frame_24.setGeometry(QtCore.QRect(43, (-3), 86, 41))
        self.frame_24.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_24.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_24.setObjectName('frame_24')
        self.line_87 = QtWidgets.QFrame(parent=self.frame)
        self.line_87.setGeometry(QtCore.QRect(81, 40, 3, 130))
        self.line_87.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_87.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_87.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_87.setObjectName('line_87')
        self.frame_58 = QtWidgets.QFrame(parent=self.frame)
        self.frame_58.setGeometry(QtCore.QRect(82, 33, 47, 48))
        self.frame_58.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_58.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_58.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_58.setObjectName('frame_58')
        self.frame_59 = QtWidgets.QFrame(parent=self.frame_58)
        self.frame_59.setGeometry(QtCore.QRect(43, 40, 44, 71))
        self.frame_59.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_59.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_59.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_59.setObjectName('frame_59')
        self.line_88 = QtWidgets.QFrame(parent=self.frame)
        self.line_88.setGeometry(QtCore.QRect(128, 0, 3, 42))
        self.line_88.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_88.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_88.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_88.setObjectName('line_88')
        self.line_89 = QtWidgets.QFrame(parent=self.frame)
        self.line_89.setGeometry(QtCore.QRect(128, 40, 43, 3))
        self.line_89.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_89.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_89.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_89.setObjectName('line_89')
        self.line_90 = QtWidgets.QFrame(parent=self.frame)
        self.line_90.setGeometry(QtCore.QRect(170, 0, 3, 170))
        self.line_90.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_90.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_90.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_90.setObjectName('line_90')
        self.line_91 = QtWidgets.QFrame(parent=self.frame)
        self.line_91.setGeometry(QtCore.QRect(214, 0, 3, 42))
        self.line_91.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_91.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_91.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_91.setObjectName('line_91')
        self.frame_38 = QtWidgets.QFrame(parent=self.frame)
        self.frame_38.setGeometry(QtCore.QRect(173, (-3), 41, 41))
        self.frame_38.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_38.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_38.setObjectName('frame_38')
        self.line_92 = QtWidgets.QFrame(parent=self.frame)
        self.line_92.setGeometry(QtCore.QRect(214, 40, 93, 3))
        self.line_92.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_92.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_92.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_92.setObjectName('line_92')
        self.line_93 = QtWidgets.QFrame(parent=self.frame)
        self.line_93.setGeometry(QtCore.QRect(305, 0, 3, 42))
        self.line_93.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_93.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_93.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_93.setObjectName('line_93')
        self.line_94 = QtWidgets.QFrame(parent=self.frame)
        self.line_94.setGeometry(QtCore.QRect(260, 40, 3, 130))
        self.line_94.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_94.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_94.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_94.setObjectName('line_94')
        self.frame_40 = QtWidgets.QFrame(parent=self.frame)
        self.frame_40.setGeometry(QtCore.QRect(308, (-3), 41, 41))
        self.frame_40.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_40.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_40.setObjectName('frame_40')
        self.line_95 = QtWidgets.QFrame(parent=self.frame)
        self.line_95.setGeometry(QtCore.QRect(483, 0, 3, 42))
        self.line_95.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_95.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_95.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_95.setObjectName('line_95')
        self.frame_41 = QtWidgets.QFrame(parent=self.frame)
        self.frame_41.setGeometry(QtCore.QRect(528, (-3), 41, 41))
        self.frame_41.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_41.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_41.setObjectName('frame_41')
        self.line_68 = QtWidgets.QFrame(parent=self.frame)
        self.line_68.setGeometry(QtCore.QRect(395, 0, 3, 42))
        self.line_68.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_68.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_68.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_68.setObjectName('line_68')
        self.line_96 = QtWidgets.QFrame(parent=self.frame)
        self.line_96.setGeometry(QtCore.QRect(660, 0, 3, 42))
        self.line_96.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_96.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_96.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_96.setObjectName('line_96')
        self.frame_25 = QtWidgets.QFrame(parent=self.frame)
        self.frame_25.setGeometry(QtCore.QRect(398, (-7), 86, 48))
        self.frame_25.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_25.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_25.setObjectName('frame_25')
        self.frame_60 = QtWidgets.QFrame(parent=self.frame)
        self.frame_60.setGeometry(QtCore.QRect(439, 33, 45, 48))
        self.frame_60.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_60.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_60.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_60.setObjectName('frame_60')
        self.frame_61 = QtWidgets.QFrame(parent=self.frame_60)
        self.frame_61.setGeometry(QtCore.QRect(43, 40, 44, 71))
        self.frame_61.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_61.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_61.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_61.setObjectName('frame_61')
        self.line_70 = QtWidgets.QFrame(parent=self.frame)
        self.line_70.setGeometry(QtCore.QRect(352, 40, 44, 3))
        self.line_70.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_70.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_70.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_70.setObjectName('line_70')
        self.line_97 = QtWidgets.QFrame(parent=self.frame)
        self.line_97.setGeometry(QtCore.QRect(440, 40, 3, 130))
        self.line_97.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_97.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_97.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_97.setObjectName('line_97')
        self.frame_52 = QtWidgets.QFrame(parent=self.frame)
        self.frame_52.setGeometry(QtCore.QRect(398, 33, 43, 48))
        self.frame_52.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_52.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_52.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_52.setObjectName('frame_52')
        self.line_98 = QtWidgets.QFrame(parent=self.frame)
        self.line_98.setGeometry(QtCore.QRect(569, 0, 3, 42))
        self.line_98.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_98.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_98.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_98.setObjectName('line_98')
        self.line_99 = QtWidgets.QFrame(parent=self.frame)
        self.line_99.setGeometry(QtCore.QRect(615, 40, 3, 130))
        self.line_99.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_99.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_99.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_99.setObjectName('line_99')
        self.line_100 = QtWidgets.QFrame(parent=self.frame)
        self.line_100.setGeometry(QtCore.QRect(485, 40, 42, 3))
        self.line_100.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_100.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_100.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_100.setObjectName('line_100')
        self.line_101 = QtWidgets.QFrame(parent=self.frame)
        self.line_101.setGeometry(QtCore.QRect(569, 40, 93, 3))
        self.line_101.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_101.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_101.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_101.setObjectName('line_101')
        self.line_103 = QtWidgets.QFrame(parent=self.frame)
        self.line_103.setGeometry(QtCore.QRect(525, 0, 3, 170))
        self.line_103.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_103.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_103.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_103.setObjectName('line_103')
        self.frame_42 = QtWidgets.QFrame(parent=self.frame)
        self.frame_42.setGeometry(QtCore.QRect(663, (-3), 41, 41))
        self.frame_42.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_42.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_42.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_42.setObjectName('frame_42')
        self.line_82 = QtWidgets.QFrame(parent=self.frame)
        self.line_82.setGeometry(QtCore.QRect(570, 0, 91, 3))
        self.line_82.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_82.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_82.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_82.setObjectName('line_82')
        self.line_23 = QtWidgets.QFrame(parent=self.frame)
        self.line_23.setGeometry(QtCore.QRect(701, 0, 3, 170))
        self.line_23.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_23.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_23.setObjectName('line_23')
        self.frame_66 = QtWidgets.QFrame(parent=self.frame)
        self.frame_66.setGeometry(QtCore.QRect(791, 33, 45, 48))
        self.frame_66.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_66.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_66.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_66.setObjectName('frame_66')
        self.frame_67 = QtWidgets.QFrame(parent=self.frame_66)
        self.frame_67.setGeometry(QtCore.QRect(43, 40, 44, 71))
        self.frame_67.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_67.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_67.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_67.setObjectName('frame_67')
        self.line_126 = QtWidgets.QFrame(parent=self.frame)
        self.line_126.setGeometry(QtCore.QRect(837, 40, 42, 3))
        self.line_126.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_126.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_126.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_126.setObjectName('line_126')
        self.line_127 = QtWidgets.QFrame(parent=self.frame)
        self.line_127.setGeometry(QtCore.QRect(747, 0, 3, 42))
        self.line_127.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_127.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_127.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_127.setObjectName('line_127')
        self.line_128 = QtWidgets.QFrame(parent=self.frame)
        self.line_128.setGeometry(QtCore.QRect(704, 40, 44, 3))
        self.line_128.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_128.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_128.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_128.setObjectName('line_128')
        self.frame_55 = QtWidgets.QFrame(parent=self.frame)
        self.frame_55.setGeometry(QtCore.QRect(750, 33, 47, 48))
        self.frame_55.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_55.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_55.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_55.setObjectName('frame_55')
        self.line_129 = QtWidgets.QFrame(parent=self.frame)
        self.line_129.setGeometry(QtCore.QRect(792, 40, 3, 130))
        self.line_129.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_129.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_129.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_129.setObjectName('line_129')
        self.frame_28 = QtWidgets.QFrame(parent=self.frame)
        self.frame_28.setGeometry(QtCore.QRect(750, (-3), 86, 41))
        self.frame_28.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_28.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_28.setObjectName('frame_28')
        self.line_102 = QtWidgets.QFrame(parent=self.frame_2)
        self.line_102.setGeometry(QtCore.QRect(878, 1, 2, 43))
        self.line_102.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_102.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_102.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_102.setObjectName('line_102')
        self.frame_20 = QtWidgets.QFrame(parent=self.frame_tela)
        self.frame_20.setGeometry(QtCore.QRect(1064, 280, 147, 157))
        self.frame_20.setStyleSheet('background-color: rgb(255, 255, 255);\nborder: 2px solid #2E3D48')
        self.frame_20.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_20.setObjectName('frame_20')
        self.label_ocupado2_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.label_ocupado2_3.setGeometry(QtCore.QRect(40, 130, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_ocupado2_3.setFont(font)
        self.label_ocupado2_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_ocupado2_3.setObjectName('label_ocupado2_3')
        self.label_bloqueado2_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.label_bloqueado2_3.setGeometry(QtCore.QRect(40, 100, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_bloqueado2_3.setFont(font)
        self.label_bloqueado2_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_bloqueado2_3.setObjectName('label_bloqueado2_3')
        self.label_vago2_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.label_vago2_3.setGeometry(QtCore.QRect(40, 40, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_vago2_3.setFont(font)
        self.label_vago2_3.setStyleSheet('background-color: rgb(255, 255, 255);\nborder: transparent;')
        self.label_vago2_3.setObjectName('label_vago2_3')
        self.label_reservado2_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.label_reservado2_3.setGeometry(QtCore.QRect(40, 70, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_reservado2_3.setFont(font)
        self.label_reservado2_3.setStyleSheet('background-color: rgb(255, 255, 255);\nborder: transparent;')
        self.label_reservado2_3.setObjectName('label_reservado2_3')
        self.cor_legenda_red_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.cor_legenda_red_3.setGeometry(QtCore.QRect(10, 130, 21, 21))
        self.cor_legenda_red_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 0, 0);')
        self.cor_legenda_red_3.setText('')
        self.cor_legenda_red_3.setObjectName('cor_legenda_red_3')
        self.cor_b_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.cor_b_3.setGeometry(QtCore.QRect(10, 100, 21, 21))
        self.cor_b_3.setStyleSheet('\nborder: transparent;background-color: rgb(170, 170, 255);')
        self.cor_b_3.setText('')
        self.cor_b_3.setObjectName('cor_b_3')
        self.cor_legenda_blue_4 = QtWidgets.QLabel(parent=self.frame_20)
        self.cor_legenda_blue_4.setGeometry(QtCore.QRect(10, 40, 21, 21))
        self.cor_legenda_blue_4.setStyleSheet('background-color: rgb(170, 255, 255);\nborder-left-color: rgb(0, 0, 0);\nborder-bottom-color: rgb(0, 0, 0);\nborder-right-color: rgb(0, 0, 0);\nborder-right-color: rgb(0, 0, 0);\nborder-top-color: rgb(0, 0, 0);\nborder-color: rgb(0, 0, 0);\nborder: transparent;')
        self.cor_legenda_blue_4.setText('')
        self.cor_legenda_blue_4.setObjectName('cor_legenda_blue_4')
        self.legenda_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.legenda_3.setGeometry(QtCore.QRect(10, 10, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.legenda_3.setFont(font)
        self.legenda_3.setStyleSheet('background-color: rgb(255, 255, 255);\nborder: transparent;')
        self.legenda_3.setObjectName('legenda_3')
        self.cor_legenda_yellow_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.cor_legenda_yellow_3.setGeometry(QtCore.QRect(10, 70, 21, 21))
        self.cor_legenda_yellow_3.setStyleSheet('\nborder: transparent;\nbackground-color: rgb(255, 255, 0);')
        self.cor_legenda_yellow_3.setText('')
        self.cor_legenda_yellow_3.setObjectName('cor_legenda_yellow_3')
        self.labels = []
        if self.tela.help_sccrol_painel == True:
            self.tela.monitora = False
            self.tela.abri_cti(Form, 'UNIDADE DE INTERNAÇÃO - 09L')

        for row in range(self.tela.conta_linha()):
            leito = self.tela.leito(row)
            if self.tela.help_sccrol_painel == True:
                label = QLabel(leito.text(), self.frame_tela)
            else:
                label = QLabel(leito.text(), self.tela.frame_do_monitoramento)

            label.setGeometry(0, 0, 60, 25)
            filename = 'monitora_nono_leste.csv'
            if self.tela.help_sccrol_painel == True:
                filename = 'monitora_nono_lestepainel.csv'

            try:
                with open(filename, mode='r') as file:
                    reader = csv.reader(file)
                    data = list(reader)
                    for row in range(len(data)):
                        if data[row][0] == leito.text():
                            x = int(data[row][1])
                            y = int(data[row][2])
                            label.setGeometry(x, y, 70, 25)
                            break
            except FileNotFoundError:
                print("Arquivo não encontrado:", filename)

            label.setAlignment(Qt.AlignmentFlag.AlignCenter)
            label.setCursor(Qt.CursorShape.OpenHandCursor)
            label.mousePressEvent = lambda event, label=label: self.mousePressEvent(event, label)
            label.mouseMoveEvent = lambda event, label=label: self.mouseMoveEvent(event, label)
            label.setWordWrap(True)
            fonte = QFont()
            fonte.setPointSize(10)
            label.setFont(fonte)
            label.setStyleSheet('background-color: rgb(170, 255, 255);')
            self.labels.append(label)
        else:
            self.atualizar_monitoramento(Form)
            self.conf_layout()
            if self.tela.help_sccrol_painel == True:
                self.frame.move(140, 230)
                self.frame_2.move(140, 193)
                self.frame_13.move(674, 26)
                self.frame_14.move(180, 26)
                self.frame_20.hide()
                self.frame_6.hide()
                self.tela.qt_int_adulto2 += self.ocupado
                self.tela.qt_int_adulto_total2 += self.total
                self.tela.total_bloq += self.bloqueado
                self.tela.total_vago += self.vago
                self.tela.total_rese += self.reservado
                self.tela.total_ocup += self.ocupado
                self.tela.qt_vagos_9leste = self.vago

    def atualizar_monitoramento(self, Form):
        self.vago = 0
        self.reservado = 0
        self.ocupado = 0
        self.bloqueado = 0
        self.total = 0
        colum_nome = 0
        colum_status = 0
        for colum in range(1, self.tela.tabela_grade.columnCount()):
            item_pac = self.tela.tabela_grade.horizontalHeaderItem(colum)
            if item_pac.text() == 'NOME DO PACIENTE':
                colum_nome = colum
            if item_pac.text() == 'STATUS DO LEITO':
                colum_status = colum
        for row in range(self.tela.conta_linha()):
            selecao = self.tela.item(row, colum_status)
            leitos = self.tela.leito(row)
            LEITOS = leitos.text()
            paciente = self.tela.item(row, colum_nome).text()
            self.total += 1
            if selecao.text() == 'VAGO':
                self.vago += 1
                for label in self.labels:
                    if label.text() == LEITOS:
                        label.setAlignment(Qt.AlignmentFlag.AlignCenter)
                        tooltip_text = 'Leito Vago'
                        label.setToolTip(tooltip_text)
            if selecao.text() == 'OCUPADO':
                for label in self.labels:
                    if label.text() == LEITOS:
                        label.setAlignment(Qt.AlignmentFlag.AlignCenter)
                        tooltip_text = f'Paciente: {paciente} \n Leito: {LEITOS}'
                        label.setToolTip(tooltip_text)
                        font = QtGui.QFont()
                        font.setBold(True)
                        font.setWeight(75)
                        label.setFont(font)
                        label.setStyleSheet('background-color: rgb(255, 0, 0);')
                self.ocupado += 1
            if selecao.text() == 'RESERVADO':
                print(4145)
                for label in self.labels:
                    if label.text() == LEITOS:
                        print(LEITOS)
                        label.setAlignment(Qt.AlignmentFlag.AlignCenter)
                        tooltip_text = f'Paciente: {paciente} \n Leito: {LEITOS}'
                        label.setToolTip(tooltip_text)
                        font = QtGui.QFont()
                        font.setBold(True)
                        font.setWeight(75)
                        label.setFont(font)
                        label.setStyleSheet('background-color: rgb(255, 255, 0);')
                self.reservado += 1
            if selecao.text() == 'BLOQUEADO':
                for label in self.labels:
                    if label.text() == LEITOS:
                        label.setAlignment(Qt.AlignmentFlag.AlignCenter)
                        tooltip_text = 'Leito Bloqueado'
                        label.setToolTip(tooltip_text)
                        font = QtGui.QFont()
                        font.setBold(True)
                        font.setWeight(75)
                        label.setFont(font)
                        label.setStyleSheet('background-color: rgb(170, 170, 255);')
                self.bloqueado += 1
            if self.tela.help_sccrol_painel == True:
                if selecao.text() == 'BLOQUEADO POR FALTA DE FUNCIONÁRIOS':
                    self.tela.qt_se_fun += 1
                    self.bloqueado += 1
                if selecao.text() == 'PONTUAL - BLOQUEADO POR FALTA DE FUNCIONÁRIOS':
                    self.tela.qt_pront += 1
                    self.bloqueado += 1
                if selecao.text() == 'BLOQUEADO POR MANUTENÇÃO':
                    self.tela.qt_bl_manu += 1
                    self.bloqueado += 1
                if selecao.text() == 'BLOQUEADO POR VM/VNI':
                    self.tela.qt_bl_VM_VNI += 1
                    self.bloqueado += 1
        self.retranslateUi(Form)

    def mousePressEvent(self, event, label):
        label.mouse_offset = event.pos()

    def mouseMoveEvent(self, event, label):
        if event.buttons() == Qt.MouseButton.LeftButton:
            new_pos = label.mapToParent(event.pos() - label.mouse_offset)
            label.move(new_pos)
            x, y = (new_pos.x(), new_pos.y())
            frame = self.tela.frame_do_monitoramento
            print(y)
            if not self.tela.help_sccrol_painel == True:
                frame = self.tela.frame_do_monitoramento
            else:  # inserted
                frame = self.frame_tela
            if frame:
                frame_rect = frame.rect()
                new_pos.setX(max(frame_rect.left(), min(new_pos.x(), frame_rect.right() - label.width())))
                new_pos.setY(max(frame_rect.top(), min(new_pos.y(), frame_rect.bottom() - label.height())))
                label.move(new_pos)
        filename = 'monitora_nono_leste.csv'
        if self.tela.help_sccrol_painel == True:
            filename = 'monitora_nono_lestepainel.csv'
        with open(filename, mode='w', newline='') as file:
            writer = csv.writer(file)
            for lisa in self.labels:
                texto = lisa.text()
                posicao = lisa.pos()
                writer.writerow([texto, posicao.x(), posicao.y()])

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate('Form', 'POSTO'))
        self.label_ocupado1_3.setText(_translate('Form', 'OCUPADO :'))
        self.label_tabela_3.setText(_translate('Form', 'TABELA :'))
        vago = str(self.vago)
        reservado = str(self.reservado)
        bloqueado = str(self.bloqueado)
        ocupado = str(self.ocupado)
        self.qt_vago_3.setText(_translate('Form', vago))
        self.label_bloq1_3.setText(_translate('Form', 'BLOQUEADO :'))
        self.qt_reservado_3.setText(_translate('Form', reservado))
        self.qt_bloqueado_3.setText(_translate('Form', bloqueado))
        self.label_reser1_3.setText(_translate('Form', 'RESERVADO :'))
        self.qt_ocupado_3.setText(_translate('Form', ocupado))
        self.label_vago1_3.setText(_translate('Form', 'VAGO :'))
        self.label_ocupado2_3.setText(_translate('Form', 'OCUPADO'))
        self.label_bloqueado2_3.setText(_translate('Form', 'BLOQUEADO'))
        self.label_vago2_3.setText(_translate('Form', 'VAGO'))
        self.label_reservado2_3.setText(_translate('Form', 'RESERVADO'))
        self.legenda_3.setText(_translate('Form', 'LEGENDA :'))

    def conf_layout(self):
        if self.settings.contains('tema'):
            font_name = self.settings.value('font', defaultValue='')
            backcolocor = self.settings.value('tema', defaultValue='')
            color = self.settings.value('color', defaultValue='')
            tamanho = int(self.settings.value('tamanho', defaultValue=10))
            self.backcolocor = backcolocor
            self.color = color
            self.font = font_name
            self.tamanho = tamanho
            if not self.tela.help_sccrol_painel == True:
                self.tela.frame_do_monitoramento.setStyleSheet('QFrame { background-color: transparent; border: 1px solid black; border-radius: 10px; box-shadow: 5px 5px 5px grey; }')