# Decompiled with PyLingual (https://pylingual.io)
# Internal filename: oitavo_ALA_SUL.py
# Bytecode version: 3.12.0rc2 (3531)
# Source timestamp: 1970-01-01 00:00:00 UTC (0)

from PyQt6 import QtCore, QtGui, QtWidgets
import csv
from PyQt6.QtCore import QRect, Qt, QSettings, QStandardPaths, Qt
from PyQt6.QtWidgets import QLabel
from PyQt6.QtGui import QFont

class Ui_Form(object):
    def setupUi(self, Form, frame, tela):
        self.tela = tela
        self.frame_tela = frame
        self.settings = QSettings('HC', 'SGL')
        script_directory = QStandardPaths.writableLocation(QStandardPaths.StandardLocation.AppDataLocation)
        config_file_path = f'{script_directory}/config.ini'
        self.settings = QSettings(config_file_path, QSettings.Format.IniFormat)
        self.form = Form
        self.frame_2 = QtWidgets.QFrame(parent=self.frame_tela)
        self.frame_2.setGeometry(QtCore.QRect(110, 230, 841, 40))
        self.frame_2.setStyleSheet('background-color: #c0c0c0;\n')
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName('frame_2')
        self.frame_20 = QtWidgets.QFrame(parent=self.frame_tela)
        self.frame_20.setGeometry(QtCore.QRect(959, 270, 147, 157))
        self.frame_20.setStyleSheet('background-color: rgb(255, 255, 255);\nborder: 2px solid #2E3D48')
        self.frame_20.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_20.setObjectName('frame_20')
        self.label_ocupado2_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.label_ocupado2_3.setGeometry(QtCore.QRect(40, 130, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_ocupado2_3.setFont(font)
        self.label_ocupado2_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_ocupado2_3.setObjectName('label_ocupado2_3')
        self.label_bloqueado2_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.label_bloqueado2_3.setGeometry(QtCore.QRect(40, 100, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_bloqueado2_3.setFont(font)
        self.label_bloqueado2_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_bloqueado2_3.setObjectName('label_bloqueado2_3')
        self.label_vago2_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.label_vago2_3.setGeometry(QtCore.QRect(40, 40, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_vago2_3.setFont(font)
        self.label_vago2_3.setStyleSheet('background-color: rgb(255, 255, 255);\nborder: transparent;')
        self.label_vago2_3.setObjectName('label_vago2_3')
        self.label_reservado2_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.label_reservado2_3.setGeometry(QtCore.QRect(40, 70, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_reservado2_3.setFont(font)
        self.label_reservado2_3.setStyleSheet('background-color: rgb(255, 255, 255);\nborder: transparent;')
        self.label_reservado2_3.setObjectName('label_reservado2_3')
        self.cor_legenda_red_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.cor_legenda_red_3.setGeometry(QtCore.QRect(10, 130, 21, 21))
        self.cor_legenda_red_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 0, 0);')
        self.cor_legenda_red_3.setText('')
        self.cor_legenda_red_3.setObjectName('cor_legenda_red_3')
        self.cor_b_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.cor_b_3.setGeometry(QtCore.QRect(10, 100, 21, 21))
        self.cor_b_3.setStyleSheet('\nborder: transparent;background-color: rgb(170, 170, 255);')
        self.cor_b_3.setText('')
        self.cor_b_3.setObjectName('cor_b_3')
        self.cor_legenda_blue_4 = QtWidgets.QLabel(parent=self.frame_20)
        self.cor_legenda_blue_4.setGeometry(QtCore.QRect(10, 40, 21, 21))
        self.cor_legenda_blue_4.setStyleSheet('background-color: rgb(170, 255, 255);\nborder-left-color: rgb(0, 0, 0);\nborder-bottom-color: rgb(0, 0, 0);\nborder-right-color: rgb(0, 0, 0);\nborder-right-color: rgb(0, 0, 0);\nborder-top-color: rgb(0, 0, 0);\nborder-color: rgb(0, 0, 0);\nborder: transparent;')
        self.cor_legenda_blue_4.setText('')
        self.cor_legenda_blue_4.setObjectName('cor_legenda_blue_4')
        self.legenda_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.legenda_3.setGeometry(QtCore.QRect(10, 10, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.legenda_3.setFont(font)
        self.legenda_3.setStyleSheet('background-color: rgb(255, 255, 255);\nborder: transparent;')
        self.legenda_3.setObjectName('legenda_3')
        self.cor_legenda_yellow_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.cor_legenda_yellow_3.setGeometry(QtCore.QRect(10, 70, 21, 21))
        self.cor_legenda_yellow_3.setStyleSheet('\nborder: transparent;\nbackground-color: rgb(255, 255, 0);')
        self.cor_legenda_yellow_3.setText('')
        self.cor_legenda_yellow_3.setObjectName('cor_legenda_yellow_3')
        self.frame_13 = QtWidgets.QFrame(parent=self.frame_tela)
        self.frame_13.setGeometry(QtCore.QRect(659, 269, 291, 161))
        self.frame_13.setStyleSheet('                border-bottom: 2px solid black;\n\nbackground-color: rgb(255, 255, 255);\n                border-left: 2px solid black;\n                border-right: 2px solid black;\n')
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName('frame_13')
        self.frame_30 = QtWidgets.QFrame(parent=self.frame_13)
        self.frame_30.setGeometry(QtCore.QRect(691, 60, 38, 50))
        self.frame_30.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_30.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_30.setObjectName('frame_30')
        self.line_109 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_109.setGeometry(QtCore.QRect(690, 3, 1, 104))
        self.line_109.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_109.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_109.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_109.setObjectName('line_109')
        self.line_22 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_22.setGeometry(QtCore.QRect(169, 0, 3, 160))
        self.line_22.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_22.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_22.setObjectName('line_22')
        self.frame_12 = QtWidgets.QFrame(parent=self.frame_13)
        self.frame_12.setGeometry(QtCore.QRect(172, (-3), 40, 57))
        self.frame_12.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName('frame_12')
        self.line_59 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_59.setGeometry(QtCore.QRect(170, 80, 118, 1))
        self.line_59.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_59.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_59.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_59.setObjectName('line_59')
        self.frame_14 = QtWidgets.QFrame(parent=self.frame_13)
        self.frame_14.setGeometry(QtCore.QRect(79, (-3), 40, 57))
        self.frame_14.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_14.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_14.setObjectName('frame_14')
        self.line_60 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_60.setGeometry(QtCore.QRect(0, 80, 118, 1))
        self.line_60.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_60.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_60.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_60.setObjectName('line_60')
        self.line_78 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_78.setGeometry(QtCore.QRect(78, 1, 1, 158))
        self.line_78.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_78.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_78.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_78.setObjectName('line_78')
        self.line_79 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_79.setGeometry(QtCore.QRect(212, 0, 1, 158))
        self.line_79.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_79.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_79.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_79.setObjectName('line_79')
        self.line_23 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_23.setGeometry(QtCore.QRect(119, 0, 3, 160))
        self.line_23.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_23.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_23.setObjectName('line_23')
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_tela)
        self.frame_6.setGeometry(QtCore.QRect(959, 100, 199, 161))
        self.frame_6.setStyleSheet('background-color: rgb(255, 255, 255);\nborder: 2px solid #2E3D48')
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName('frame_6')
        self.label_ocupado1_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_ocupado1_3.setGeometry(QtCore.QRect(10, 130, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_ocupado1_3.setFont(font)
        self.label_ocupado1_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_ocupado1_3.setObjectName('label_ocupado1_3')
        self.label_tabela_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_tabela_3.setGeometry(QtCore.QRect(10, 10, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_tabela_3.setFont(font)
        self.label_tabela_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_tabela_3.setObjectName('label_tabela_3')
        self.qt_vago_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.qt_vago_3.setGeometry(QtCore.QRect(130, 40, 61, 21))
        font = QtGui.QFont()
        self.qt_vago_3.setFont(font)
        self.qt_vago_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.qt_vago_3.setObjectName('qt_vago_3')
        self.label_bloq1_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_bloq1_3.setGeometry(QtCore.QRect(10, 100, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_bloq1_3.setFont(font)
        self.label_bloq1_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_bloq1_3.setObjectName('label_bloq1_3')
        self.qt_reservado_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.qt_reservado_3.setGeometry(QtCore.QRect(130, 70, 61, 21))
        font = QtGui.QFont()
        self.qt_reservado_3.setFont(font)
        self.qt_reservado_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.qt_reservado_3.setObjectName('qt_reservado_3')
        self.qt_bloqueado_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.qt_bloqueado_3.setGeometry(QtCore.QRect(130, 100, 61, 21))
        font = QtGui.QFont()
        self.qt_bloqueado_3.setFont(font)
        self.qt_bloqueado_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.qt_bloqueado_3.setObjectName('qt_bloqueado_3')
        self.label_reser1_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_reser1_3.setGeometry(QtCore.QRect(10, 70, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_reser1_3.setFont(font)
        self.label_reser1_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_reser1_3.setObjectName('label_reser1_3')
        self.qt_ocupado_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.qt_ocupado_3.setGeometry(QtCore.QRect(130, 130, 61, 21))
        font = QtGui.QFont()
        self.qt_ocupado_3.setFont(font)
        self.qt_ocupado_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.qt_ocupado_3.setObjectName('qt_ocupado_3')
        self.label_vago1_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_vago1_3.setGeometry(QtCore.QRect(10, 40, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_vago1_3.setFont(font)
        self.label_vago1_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_vago1_3.setObjectName('label_vago1_3')
        self.frame_3 = QtWidgets.QFrame(parent=self.frame_tela)
        self.frame_3.setGeometry(QtCore.QRect(109, 270, 549, 161))
        self.frame_3.setStyleSheet('background-color: rgb(255, 255, 255);border:none;')
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName('frame_3')
        self.label = QtWidgets.QLabel(parent=self.frame_3)
        self.label.setGeometry(QtCore.QRect(330, 50, 111, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet('color: white;\nbackground-color:BLACK;\nborder-color: transparent; \ntransform: rotate(270deg);')
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName('label')
        self.frame = QtWidgets.QFrame(parent=self.frame_tela)
        self.frame.setGeometry(QtCore.QRect(109, 61, 841, 171))
        self.frame.setStyleSheet('                border-left: 2px solid black;\nbackground-color: rgb(255, 255, 255);\n                border-right: 2px solid black;\n')
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName('frame')
        self.line_40 = QtWidgets.QFrame(parent=self.frame)
        self.line_40.setGeometry(QtCore.QRect(0, 50, 109, 1))
        self.line_40.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_40.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_40.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_40.setObjectName('line_40')
        self.line_5 = QtWidgets.QFrame(parent=self.frame)
        self.line_5.setGeometry(QtCore.QRect(108, 0, 3, 170))
        self.line_5.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_5.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_5.setObjectName('line_5')
        self.frame_8 = QtWidgets.QFrame(parent=self.frame)
        self.frame_8.setGeometry(QtCore.QRect(70, 117, 38, 57))
        self.frame_8.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName('frame_8')
        self.line_18 = QtWidgets.QFrame(parent=self.frame)
        self.line_18.setGeometry(QtCore.QRect(430, 0, 3, 170))
        self.line_18.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_18.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_18.setObjectName('line_18')
        self.line_47 = QtWidgets.QFrame(parent=self.frame)
        self.line_47.setGeometry(QtCore.QRect(70, 0, 1, 171))
        self.line_47.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_47.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_47.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_47.setObjectName('line_47')
        self.line_49 = QtWidgets.QFrame(parent=self.frame)
        self.line_49.setGeometry(QtCore.QRect(0, 114, 109, 1))
        self.line_49.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_49.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_49.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_49.setObjectName('line_49')
        self.line_74 = QtWidgets.QFrame(parent=self.frame)
        self.line_74.setGeometry(QtCore.QRect(267, 0, 3, 170))
        self.line_74.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_74.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_74.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_74.setObjectName('line_74')
        self.line_76 = QtWidgets.QFrame(parent=self.frame)
        self.line_76.setGeometry(QtCore.QRect(670, 0, 3, 170))
        self.line_76.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_76.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_76.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_76.setObjectName('line_76')
        self.frame_26 = QtWidgets.QFrame(parent=self.frame)
        self.frame_26.setGeometry(QtCore.QRect(920, 0, 38, 50))
        self.frame_26.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_26.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_26.setObjectName('frame_26')
        self.line_88 = QtWidgets.QFrame(parent=self.frame)
        self.line_88.setGeometry(QtCore.QRect(720, 0, 3, 170))
        self.line_88.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_88.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_88.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_88.setObjectName('line_88')
        self.line_90 = QtWidgets.QFrame(parent=self.frame)
        self.line_90.setGeometry(QtCore.QRect(846, 110, 111, 1))
        self.line_90.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_90.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_90.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_90.setObjectName('line_90')
        self.line_91 = QtWidgets.QFrame(parent=self.frame)
        self.line_91.setGeometry(QtCore.QRect(920, 0, 1, 170))
        self.line_91.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_91.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_91.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_91.setObjectName('line_91')
        self.line_92 = QtWidgets.QFrame(parent=self.frame)
        self.line_92.setGeometry(QtCore.QRect(845, 50, 111, 1))
        self.line_92.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_92.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_92.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_92.setObjectName('line_92')
        self.line_95 = QtWidgets.QFrame(parent=self.frame)
        self.line_95.setGeometry(QtCore.QRect(843, 0, 3, 170))
        self.line_95.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_95.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_95.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_95.setObjectName('line_95')
        self.line_98 = QtWidgets.QFrame(parent=self.frame)
        self.line_98.setGeometry(QtCore.QRect(960, 110, 71, 1))
        self.line_98.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_98.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_98.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_98.setObjectName('line_98')
        self.line_99 = QtWidgets.QFrame(parent=self.frame)
        self.line_99.setGeometry(QtCore.QRect(958, 0, 1, 170))
        self.line_99.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_99.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_99.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_99.setObjectName('line_99')
        self.line_100 = QtWidgets.QFrame(parent=self.frame)
        self.line_100.setGeometry(QtCore.QRect(960, 50, 69, 1))
        self.line_100.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_100.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_100.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_100.setObjectName('line_100')
        self.line_138 = QtWidgets.QFrame(parent=self.frame)
        self.line_138.setGeometry(QtCore.QRect(844, 0, 76, 2))
        self.line_138.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_138.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_138.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_138.setObjectName('line_138')
        self.line_139 = QtWidgets.QFrame(parent=self.frame)
        self.line_139.setGeometry(QtCore.QRect(958, 0, 73, 2))
        self.line_139.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_139.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_139.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_139.setObjectName('line_139')
        self.line_140 = QtWidgets.QFrame(parent=self.frame)
        self.line_140.setGeometry(QtCore.QRect(630, 0, 1, 170))
        self.line_140.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_140.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_140.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_140.setObjectName('line_140')
        self.line_94 = QtWidgets.QFrame(parent=self.frame)
        self.line_94.setGeometry(QtCore.QRect(553, 113, 117, 1))
        self.line_94.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_94.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_94.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_94.setObjectName('line_94')
        self.frame_11 = QtWidgets.QFrame(parent=self.frame)
        self.frame_11.setGeometry(QtCore.QRect(723, 118, 40, 57))
        self.frame_11.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName('frame_11')
        self.line_57 = QtWidgets.QFrame(parent=self.frame)
        self.line_57.setGeometry(QtCore.QRect(722, 50, 118, 1))
        self.line_57.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_57.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_57.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_57.setObjectName('line_57')
        self.line_58 = QtWidgets.QFrame(parent=self.frame)
        self.line_58.setGeometry(QtCore.QRect(722, 114, 117, 1))
        self.line_58.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_58.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_58.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_58.setObjectName('line_58')
        self.frame_15 = QtWidgets.QFrame(parent=self.frame)
        self.frame_15.setGeometry(QtCore.QRect(158, 117, 38, 57))
        self.frame_15.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_15.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_15.setObjectName('frame_15')
        self.line_103 = QtWidgets.QFrame(parent=self.frame)
        self.line_103.setGeometry(QtCore.QRect(155, 2, 3, 170))
        self.line_103.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_103.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_103.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_103.setObjectName('line_103')
        self.line_54 = QtWidgets.QFrame(parent=self.frame)
        self.line_54.setGeometry(QtCore.QRect(158, 114, 109, 1))
        self.line_54.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_54.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_54.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_54.setObjectName('line_54')
        self.line_61 = QtWidgets.QFrame(parent=self.frame)
        self.line_61.setGeometry(QtCore.QRect(158, 51, 109, 1))
        self.line_61.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_61.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_61.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_61.setObjectName('line_61')
        self.line_75 = QtWidgets.QFrame(parent=self.frame)
        self.line_75.setGeometry(QtCore.QRect(196, 3, 1, 165))
        self.line_75.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_75.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_75.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_75.setObjectName('line_75')
        self.line_141 = QtWidgets.QFrame(parent=self.frame)
        self.line_141.setGeometry(QtCore.QRect(762, 0, 1, 170))
        self.line_141.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_141.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_141.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_141.setObjectName('line_141')
        self.frame_16 = QtWidgets.QFrame(parent=self.frame)
        self.frame_16.setGeometry(QtCore.QRect(630, 7, 40, 57))
        self.frame_16.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_16.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_16.setObjectName('frame_16')
        self.line_19 = QtWidgets.QFrame(parent=self.frame)
        self.line_19.setGeometry(QtCore.QRect(550, 0, 3, 170))
        self.line_19.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_19.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_19.setObjectName('line_19')
        self.line_62 = QtWidgets.QFrame(parent=self.frame)
        self.line_62.setGeometry(QtCore.QRect(553, 60, 118, 1))
        self.line_62.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_62.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_62.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_62.setObjectName('line_62')
        self.line_142 = QtWidgets.QFrame(parent=self.frame)
        self.line_142.setGeometry(QtCore.QRect(473, 0, 1, 170))
        self.line_142.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_142.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_142.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_142.setObjectName('line_142')
        self.line_63 = QtWidgets.QFrame(parent=self.frame)
        self.line_63.setGeometry(QtCore.QRect(432, 60, 118, 1))
        self.line_63.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_63.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_63.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_63.setObjectName('line_63')
        self.line_96 = QtWidgets.QFrame(parent=self.frame)
        self.line_96.setGeometry(QtCore.QRect(432, 113, 117, 1))
        self.line_96.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_96.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_96.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_96.setObjectName('line_96')
        self.frame_17 = QtWidgets.QFrame(parent=self.frame)
        self.frame_17.setGeometry(QtCore.QRect(433, 117, 40, 57))
        self.frame_17.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_17.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_17.setObjectName('frame_17')
        self.line_110 = QtWidgets.QFrame(parent=self.frame_2)
        self.line_110.setGeometry(QtCore.QRect(834, 40, 191, 2))
        self.line_110.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_110.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_110.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_110.setObjectName('line_110')
        self.frame_10 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_10.setGeometry(QtCore.QRect(650, 10, 39, 60))
        self.frame_10.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName('frame_10')
        if self.tela.help_sccrol_painel == True:
            self.tela.monitora = False
            self.tela.abri_cti(Form, 'UNIDADE DE INTERNAÇÃO - 08S')
        self.labels = []
        for row in range(self.tela.conta_linha()):
            leito = self.tela.leito(row)
            if self.tela.help_sccrol_painel == True:
                label = QLabel(leito.text(), self.frame_tela)
            else:  # inserted
                label = QLabel(leito.text(), self.tela.frame_do_monitoramento)
            label.setGeometry(0, 0, 60, 25)
            filename = 'monitora_oitavo_sul.csv'
            if self.tela.help_sccrol_painel == True:
                filename = 'monitora_oitavo_sulpainel.csv'
            try:
                with open(filename, mode='r') as file:
                    pass  # postinserted
            except FileNotFoundError:
                print(1)
                    reader = csv.reader(file)
                    print('fay')
                    data = list(reader)
                    print('fay')
                    for row in range(len(data)):
                        print('fay')
                        if data[row][0] == leito.text():
                            print('fay')
                            x = int(data[row][1])
                            y = int(data[row][2])
                            label.setGeometry(x, y, 70, 25)
                            break
                        label.setAlignment(Qt.AlignmentFlag.AlignCenter)
                        label.setCursor(Qt.CursorShape.OpenHandCursor)
                        label.mousePressEvent = lambda event, label=label: self.mousePressEvent(event, label)
                        label.mouseMoveEvent = lambda event, label=label: self.mouseMoveEvent(event, label)
                        label.setWordWrap(True)
                        fonte = QFont()
                        fonte.setPointSize(10)
                        label.setFont(fonte)
                        label.setStyleSheet('background-color: rgb(170, 255, 255); ')
                        self.labels.append(label)
                        self.atualizar_monitoramento(Form)
        else:  # inserted
            self.conf_layout()
            if self.tela.help_sccrol_painel == True:
                self.frame_6.hide()
                self.frame_20.hide()
                self.tela.total_bloq += self.bloqueado
                self.tela.total_vago += self.vago
                self.tela.total_rese += self.reservado
                self.tela.total_ocup += self.ocupado
                self.tela.qt_int_adulto2 += self.ocupado
                self.tela.qt_int_adulto_total2 += self.total
                self.tela.qt_vagos_8sul = self.vago

    def atualizar_monitoramento(self, Form):
        self.vago = 0
        self.reservado = 0
        self.ocupado = 0
        self.bloqueado = 0
        self.total = 0
        colum_nome = 0
        colum_status = 0
        for colum in range(1, self.tela.tabela_grade.columnCount()):
            item_pac = self.tela.tabela_grade.horizontalHeaderItem(colum)
            if item_pac.text() == 'NOME DO PACIENTE':
                colum_nome = colum
            if item_pac.text() == 'STATUS DO LEITO':
                colum_status = colum
        for row in range(self.tela.conta_linha()):
            selecao = self.tela.item(row, colum_status)
            leitos = self.tela.leito(row)
            LEITOS = leitos.text()
            paciente = self.tela.item(row, colum_nome).text()
            self.total += 1
            if selecao.text() == 'VAGO':
                self.vago += 1
                for label in self.labels:
                    if label.text() == LEITOS:
                        label.setAlignment(Qt.AlignmentFlag.AlignCenter)
                        tooltip_text = 'Leito Vago'
                        label.setToolTip(tooltip_text)
            if selecao.text() == 'OCUPADO':
                for label in self.labels:
                    if label.text() == LEITOS:
                        label.setAlignment(Qt.AlignmentFlag.AlignCenter)
                        tooltip_text = f'Paciente: {paciente} \n Leito: {LEITOS}'
                        label.setToolTip(tooltip_text)
                        font = QtGui.QFont()
                        font.setBold(True)
                        font.setWeight(75)
                        label.setFont(font)
                        label.setStyleSheet('background-color: rgb(255, 0, 0);')
                self.ocupado += 1
            if selecao.text() == 'RESERVADO':
                print(4145)
                for label in self.labels:
                    if label.text() == LEITOS:
                        print(LEITOS)
                        label.setAlignment(Qt.AlignmentFlag.AlignCenter)
                        tooltip_text = f'Paciente: {paciente} \n Leito: {LEITOS}'
                        label.setToolTip(tooltip_text)
                        font = QtGui.QFont()
                        font.setBold(True)
                        font.setWeight(75)
                        label.setFont(font)
                        label.setStyleSheet('background-color: rgb(255, 255, 0);')
                self.reservado += 1
            if selecao.text() == 'BLOQUEADO':
                for label in self.labels:
                    if label.text() == LEITOS:
                        label.setAlignment(Qt.AlignmentFlag.AlignCenter)
                        tooltip_text = 'Leito Bloqueado'
                        label.setToolTip(tooltip_text)
                        font = QtGui.QFont()
                        font.setBold(True)
                        font.setWeight(75)
                        label.setFont(font)
                        label.setStyleSheet('background-color: rgb(170, 170, 255);')
                self.bloqueado += 1
            if self.tela.help_sccrol_painel == True:
                if selecao.text() == 'BLOQUEADO POR FALTA DE FUNCIONÁRIOS':
                    self.tela.qt_se_fun += 1
                    self.bloqueado += 1
                if selecao.text() == 'PONTUAL - BLOQUEADO POR FALTA DE FUNCIONÁRIOS':
                    self.tela.qt_pront += 1
                    self.bloqueado += 1
                if selecao.text() == 'BLOQUEADO POR MANUTENÇÃO':
                    self.tela.qt_bl_manu += 1
                    self.bloqueado += 1
                if selecao.text() == 'BLOQUEADO POR VM/VNI':
                    self.tela.qt_bl_VM_VNI += 1
                    self.bloqueado += 1
        self.retranslateUi(Form)

    def mousePressEvent(self, event, label):
        label.mouse_offset = event.pos()

    def mouseMoveEvent(self, event, label):
        if event.buttons() == Qt.MouseButton.LeftButton:
            new_pos = label.mapToParent(event.pos() - label.mouse_offset)
            label.move(new_pos)
            x, y = (new_pos.x(), new_pos.y())
            if not self.tela.help_sccrol_painel == True:
                frame = self.tela.frame_do_monitoramento
            else:  # inserted
                frame = self.frame_tela
            if frame:
                frame_rect = frame.rect()
                new_pos.setX(max(frame_rect.left(), min(new_pos.x(), frame_rect.right() - label.width())))
                new_pos.setY(max(frame_rect.top(), min(new_pos.y(), frame_rect.bottom() - label.height())))
                label.move(new_pos)
        filename = 'monitora_oitavo_sul.csv'
        if self.tela.help_sccrol_painel == True:
            filename = 'monitora_oitavo_sulpainel.csv'
        with open(filename, mode='w', newline='') as file:
            writer = csv.writer(file)
            for lisa in self.labels:
                texto = lisa.text()
                posicao = lisa.pos()
                writer.writerow([texto, posicao.x(), posicao.y()])

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.label_ocupado2_3.setText(_translate('Form', 'OCUPADO'))
        self.label_bloqueado2_3.setText(_translate('Form', 'BLOQUEADO'))
        self.label_vago2_3.setText(_translate('Form', 'VAGO'))
        self.label_reservado2_3.setText(_translate('Form', 'RESERVADO'))
        self.legenda_3.setText(_translate('Form', 'LEGENDA :'))
        self.label_ocupado1_3.setText(_translate('Form', 'OCUPADO :'))
        self.label_tabela_3.setText(_translate('Form', 'TABELA :'))
        vago = str(self.vago)
        reservado = str(self.reservado)
        bloqueado = str(self.bloqueado)
        ocupado = str(self.ocupado)
        self.qt_vago_3.setText(_translate('Form', vago))
        self.label_bloq1_3.setText(_translate('Form', 'BLOQUEADO :'))
        self.qt_reservado_3.setText(_translate('Form', reservado))
        self.qt_bloqueado_3.setText(_translate('Form', bloqueado))
        self.label_reser1_3.setText(_translate('Form', 'RESERVADO :'))
        self.qt_ocupado_3.setText(_translate('Form', ocupado))
        self.label_vago1_3.setText(_translate('Form', 'VAGO :'))
        self.label.setText(_translate('Form', 'POSTO'))

    def conf_layout(self):
        if self.settings.contains('tema'):
            font_name = self.settings.value('font', defaultValue='')
            backcolocor = self.settings.value('tema', defaultValue='')
            color = self.settings.value('color', defaultValue='')
            tamanho = int(self.settings.value('tamanho', defaultValue=10))
            self.backcolocor = backcolocor
            self.color = color
            self.font = font_name
            self.tamanho = tamanho
            if not self.tela.help_sccrol_painel == True:
                self.tela.frame_do_monitoramento.setStyleSheet('QFrame { background-color: transparent; border: 1px solid black; border-radius: 10px; box-shadow: 5px 5px 5px grey; }')