# Decompiled with PyLingual (https://pylingual.io)
# Internal filename: oitavo_ALA_LESTE.py
# Bytecode version: 3.12.0rc2 (3531)
# Source timestamp: 1970-01-01 00:00:00 UTC (0)

from PyQt6 import QtCore, QtGui, QtWidgets
import csv
from PyQt6.QtCore import QRect, Qt, QSettings, QStandardPaths, Qt
from PyQt6.QtWidgets import QLabel
from PyQt6.QtGui import QFont

class Ui_Form(object):
    def setupUi(self, Form, frame, tela):
        self.tela = tela
        self.frame_tela = frame
        self.form = Form
        self.frame_2 = QtWidgets.QFrame(parent=self.frame_tela)
        self.frame_2.setGeometry(QtCore.QRect(20, 210, 1119, 40))
        self.frame_2.setStyleSheet('background-color: #c0c0c0;\n')
        self.settings = QSettings('HC', 'SGL')
        script_directory = QStandardPaths.writableLocation(QStandardPaths.StandardLocation.AppDataLocation)
        config_file_path = f'{script_directory}/config.ini'
        self.settings = QSettings(config_file_path, QSettings.Format.IniFormat)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName('frame_2')
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_tela)
        self.frame_6.setGeometry(QtCore.QRect(1150, 90, 199, 161))
        self.frame_6.setStyleSheet('background-color: rgb(255, 255, 255);\nborder: 2px solid #2E3D48')
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName('frame_6')
        self.label_ocupado1_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_ocupado1_3.setGeometry(QtCore.QRect(10, 130, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_ocupado1_3.setFont(font)
        self.label_ocupado1_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_ocupado1_3.setObjectName('label_ocupado1_3')
        self.label_tabela_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_tabela_3.setGeometry(QtCore.QRect(10, 10, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_tabela_3.setFont(font)
        self.label_tabela_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_tabela_3.setObjectName('label_tabela_3')
        self.qt_vago_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.qt_vago_3.setGeometry(QtCore.QRect(130, 40, 61, 21))
        font = QtGui.QFont()
        self.qt_vago_3.setFont(font)
        self.qt_vago_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.qt_vago_3.setObjectName('qt_vago_3')
        self.label_bloq1_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_bloq1_3.setGeometry(QtCore.QRect(10, 100, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_bloq1_3.setFont(font)
        self.label_bloq1_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_bloq1_3.setObjectName('label_bloq1_3')
        self.qt_reservado_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.qt_reservado_3.setGeometry(QtCore.QRect(130, 70, 61, 21))
        font = QtGui.QFont()
        self.qt_reservado_3.setFont(font)
        self.qt_reservado_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.qt_reservado_3.setObjectName('qt_reservado_3')
        self.qt_bloqueado_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.qt_bloqueado_3.setGeometry(QtCore.QRect(130, 100, 61, 21))
        font = QtGui.QFont()
        self.qt_bloqueado_3.setFont(font)
        self.qt_bloqueado_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.qt_bloqueado_3.setObjectName('qt_bloqueado_3')
        self.label_reser1_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_reser1_3.setGeometry(QtCore.QRect(10, 70, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_reser1_3.setFont(font)
        self.label_reser1_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_reser1_3.setObjectName('label_reser1_3')
        self.qt_ocupado_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.qt_ocupado_3.setGeometry(QtCore.QRect(130, 130, 61, 21))
        font = QtGui.QFont()
        self.qt_ocupado_3.setFont(font)
        self.qt_ocupado_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.qt_ocupado_3.setObjectName('qt_ocupado_3')
        self.label_vago1_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_vago1_3.setGeometry(QtCore.QRect(10, 40, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_vago1_3.setFont(font)
        self.label_vago1_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_vago1_3.setObjectName('label_vago1_3')
        self.frame_13 = QtWidgets.QFrame(parent=self.frame_tela)
        self.frame_13.setGeometry(QtCore.QRect(700, 41, 351, 171))
        self.frame_13.setStyleSheet('\nbackground-color: rgb(255, 255, 255);\n                border-left: 2px solid black;\n                border-right: 2px solid black;\n                border-top: 2px solid black;\n')
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName('frame_13')
        self.line_36 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_36.setGeometry(QtCore.QRect(512, 60, 109, 1))
        self.line_36.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_36.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_36.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_36.setObjectName('line_36')
        self.frame_29 = QtWidgets.QFrame(parent=self.frame_13)
        self.frame_29.setGeometry(QtCore.QRect(513, 61, 41, 50))
        self.frame_29.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_29.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_29.setObjectName('frame_29')
        self.frame_30 = QtWidgets.QFrame(parent=self.frame_13)
        self.frame_30.setGeometry(QtCore.QRect(691, 60, 38, 50))
        self.frame_30.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_30.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_30.setObjectName('frame_30')
        self.line_108 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_108.setGeometry(QtCore.QRect(620, 60, 109, 1))
        self.line_108.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_108.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_108.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_108.setObjectName('line_108')
        self.line_109 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_109.setGeometry(QtCore.QRect(690, 3, 1, 104))
        self.line_109.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_109.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_109.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_109.setObjectName('line_109')
        self.line_22 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_22.setGeometry(QtCore.QRect(260, 2, 3, 169))
        self.line_22.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_22.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_22.setObjectName('line_22')
        self.line_76 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_76.setGeometry(QtCore.QRect(262, 90, 44, 3))
        self.line_76.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_76.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_76.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_76.setObjectName('line_76')
        self.frame_32 = QtWidgets.QFrame(parent=self.frame_13)
        self.frame_32.setGeometry(QtCore.QRect(308, 124, 41, 50))
        self.frame_32.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_32.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_32.setObjectName('frame_32')
        self.line_40 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_40.setGeometry(QtCore.QRect(306, 90, 3, 79))
        self.line_40.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_40.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_40.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_40.setObjectName('line_40')
        self.frame_33 = QtWidgets.QFrame(parent=self.frame_13)
        self.frame_33.setGeometry(QtCore.QRect(91, 124, 41, 50))
        self.frame_33.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_33.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_33.setObjectName('frame_33')
        self.line_42 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_42.setGeometry(QtCore.QRect(132, 90, 3, 81))
        self.line_42.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_42.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_42.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_42.setObjectName('line_42')
        self.line_77 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_77.setGeometry(QtCore.QRect(133, 90, 44, 3))
        self.line_77.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_77.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_77.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_77.setObjectName('line_77')
        self.frame_34 = QtWidgets.QFrame(parent=self.frame_13)
        self.frame_34.setGeometry(QtCore.QRect(219, 124, 41, 50))
        self.frame_34.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_34.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_34.setObjectName('frame_34')
        self.line_44 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_44.setGeometry(QtCore.QRect(220, 90, 3, 79))
        self.line_44.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_44.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_44.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_44.setObjectName('line_44')
        self.line_78 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_78.setGeometry(QtCore.QRect(178, 90, 44, 3))
        self.line_78.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_78.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_78.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_78.setObjectName('line_78')
        self.line_46 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_46.setGeometry(QtCore.QRect(176, 0, 3, 170))
        self.line_46.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_46.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_46.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_46.setObjectName('line_46')
        self.line_47 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_47.setGeometry(QtCore.QRect(90, 0, 3, 170))
        self.line_47.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_47.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_47.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_47.setObjectName('line_47')
        self.line_48 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_48.setGeometry(QtCore.QRect(46, 168, 45, 3))
        self.line_48.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_48.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_48.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_48.setObjectName('line_48')
        self.frame_35 = QtWidgets.QFrame(parent=self.frame_13)
        self.frame_35.setGeometry(QtCore.QRect(2, 124, 42, 50))
        self.frame_35.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_35.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_35.setObjectName('frame_35')
        self.line_49 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_49.setGeometry(QtCore.QRect(44, 90, 3, 81))
        self.line_49.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_49.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_49.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_49.setObjectName('line_49')
        self.line_79 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_79.setGeometry(QtCore.QRect(46, 90, 44, 3))
        self.line_79.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_79.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_79.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_79.setObjectName('line_79')
        self.frame = QtWidgets.QFrame(parent=self.frame_tela)
        self.frame.setGeometry(QtCore.QRect(19, 249, 1119, 171))
        self.frame.setStyleSheet('                border-left: 2px solid black;\nbackground-color: rgb(255, 255, 255);\n                border-bottom: 2px solid black;\n                border-right: 2px solid black;\n')
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName('frame')
        self.line_5 = QtWidgets.QFrame(parent=self.frame)
        self.line_5.setGeometry(QtCore.QRect(180, 81, 3, 88))
        self.line_5.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_5.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_5.setObjectName('line_5')
        self.frame_18 = QtWidgets.QFrame(parent=self.frame)
        self.frame_18.setGeometry(QtCore.QRect(223, (-3), 91, 41))
        self.frame_18.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_18.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_18.setObjectName('frame_18')
        self.line_18 = QtWidgets.QFrame(parent=self.frame)
        self.line_18.setGeometry(QtCore.QRect(350, 0, 3, 170))
        self.line_18.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_18.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_18.setObjectName('line_18')
        self.frame_25 = QtWidgets.QFrame(parent=self.frame)
        self.frame_25.setGeometry(QtCore.QRect(690, (-3), 41, 50))
        self.frame_25.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_25.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_25.setObjectName('frame_25')
        self.frame_26 = QtWidgets.QFrame(parent=self.frame)
        self.frame_26.setGeometry(QtCore.QRect(820, (-3), 41, 50))
        self.frame_26.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_26.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_26.setObjectName('frame_26')
        self.line_6 = QtWidgets.QFrame(parent=self.frame)
        self.line_6.setGeometry(QtCore.QRect(182, 80, 43, 3))
        self.line_6.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_6.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_6.setObjectName('line_6')
        self.frame_45 = QtWidgets.QFrame(parent=self.frame)
        self.frame_45.setGeometry(QtCore.QRect(480, (-3), 41, 50))
        self.frame_45.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_45.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_45.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_45.setObjectName('frame_45')
        self.line_8 = QtWidgets.QFrame(parent=self.frame)
        self.line_8.setGeometry(QtCore.QRect(222, 2, 3, 79))
        self.line_8.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_8.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_8.setObjectName('line_8')
        self.line_10 = QtWidgets.QFrame(parent=self.frame)
        self.line_10.setGeometry(QtCore.QRect(310, 2, 3, 79))
        self.line_10.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_10.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_10.setObjectName('line_10')
        self.line_7 = QtWidgets.QFrame(parent=self.frame)
        self.line_7.setGeometry(QtCore.QRect(310, 80, 43, 3))
        self.line_7.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_7.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_7.setObjectName('line_7')
        self.frame_47 = QtWidgets.QFrame(parent=self.frame)
        self.frame_47.setGeometry(QtCore.QRect(225, 30, 43, 81))
        self.frame_47.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_47.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_47.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_47.setObjectName('frame_47')
        self.frame_48 = QtWidgets.QFrame(parent=self.frame)
        self.frame_48.setGeometry(QtCore.QRect(266, 30, 44, 81))
        self.frame_48.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_48.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_48.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_48.setObjectName('frame_48')
        self.line_9 = QtWidgets.QFrame(parent=self.frame)
        self.line_9.setGeometry(QtCore.QRect(265, 82, 3, 88))
        self.line_9.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_9.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_9.setObjectName('line_9')
        self.frame_50 = QtWidgets.QFrame(parent=self.frame_48)
        self.frame_50.setGeometry(QtCore.QRect(43, 40, 44, 71))
        self.frame_50.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_50.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_50.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_50.setObjectName('frame_50')
        self.frame_19 = QtWidgets.QFrame(parent=self.frame_48)
        self.frame_19.setGeometry(QtCore.QRect(0, 0, 91, 41))
        self.frame_19.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_19.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_19.setObjectName('frame_19')
        self.line_11 = QtWidgets.QFrame(parent=self.frame)
        self.line_11.setGeometry(QtCore.QRect(390, 80, 92, 3))
        self.line_11.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_11.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_11.setObjectName('line_11')
        self.line_12 = QtWidgets.QFrame(parent=self.frame)
        self.line_12.setGeometry(QtCore.QRect(435, 82, 3, 88))
        self.line_12.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_12.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_12.setObjectName('line_12')
        self.line_14 = QtWidgets.QFrame(parent=self.frame)
        self.line_14.setGeometry(QtCore.QRect(390, 0, 3, 83))
        self.line_14.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_14.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_14.setObjectName('line_14')
        self.line_19 = QtWidgets.QFrame(parent=self.frame)
        self.line_19.setGeometry(QtCore.QRect(520, 0, 3, 170))
        self.line_19.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_19.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_19.setObjectName('line_19')
        self.line_15 = QtWidgets.QFrame(parent=self.frame)
        self.line_15.setGeometry(QtCore.QRect(480, 0, 3, 83))
        self.line_15.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_15.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_15.setObjectName('line_15')
        self.frame_49 = QtWidgets.QFrame(parent=self.frame)
        self.frame_49.setGeometry(QtCore.QRect(353, (-3), 37, 50))
        self.frame_49.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_49.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_49.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_49.setObjectName('frame_49')
        self.line_13 = QtWidgets.QFrame(parent=self.frame)
        self.line_13.setGeometry(QtCore.QRect(650, 80, 43, 3))
        self.line_13.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_13.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_13.setObjectName('line_13')
        self.line_20 = QtWidgets.QFrame(parent=self.frame)
        self.line_20.setGeometry(QtCore.QRect(650, 2, 3, 79))
        self.line_20.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_20.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_20.setObjectName('line_20')
        self.line_21 = QtWidgets.QFrame(parent=self.frame)
        self.line_21.setGeometry(QtCore.QRect(522, 80, 43, 3))
        self.line_21.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_21.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_21.setObjectName('line_21')
        self.line_23 = QtWidgets.QFrame(parent=self.frame)
        self.line_23.setGeometry(QtCore.QRect(562, 0, 3, 81))
        self.line_23.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_23.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_23.setObjectName('line_23')
        self.line_24 = QtWidgets.QFrame(parent=self.frame)
        self.line_24.setGeometry(QtCore.QRect(690, 0, 3, 170))
        self.line_24.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_24.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_24.setObjectName('line_24')
        self.frame_52 = QtWidgets.QFrame(parent=self.frame)
        self.frame_52.setGeometry(QtCore.QRect(606, 20, 44, 81))
        self.frame_52.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_52.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_52.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_52.setObjectName('frame_52')
        self.frame_53 = QtWidgets.QFrame(parent=self.frame)
        self.frame_53.setGeometry(QtCore.QRect(565, 20, 43, 81))
        self.frame_53.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_53.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_53.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_53.setObjectName('frame_53')
        self.frame_21 = QtWidgets.QFrame(parent=self.frame)
        self.frame_21.setGeometry(QtCore.QRect(565, (-10), 85, 41))
        self.frame_21.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_21.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_21.setObjectName('frame_21')
        self.line_16 = QtWidgets.QFrame(parent=self.frame)
        self.line_16.setGeometry(QtCore.QRect(606, 81, 3, 88))
        self.line_16.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_16.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_16.setObjectName('line_16')
        self.line_25 = QtWidgets.QFrame(parent=self.frame)
        self.line_25.setGeometry(QtCore.QRect(860, 0, 3, 170))
        self.line_25.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_25.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_25.setObjectName('line_25')
        self.line_26 = QtWidgets.QFrame(parent=self.frame)
        self.line_26.setGeometry(QtCore.QRect(820, 0, 3, 83))
        self.line_26.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_26.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_26.setObjectName('line_26')
        self.line_27 = QtWidgets.QFrame(parent=self.frame)
        self.line_27.setGeometry(QtCore.QRect(730, 0, 3, 83))
        self.line_27.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_27.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_27.setObjectName('line_27')
        self.line_28 = QtWidgets.QFrame(parent=self.frame)
        self.line_28.setGeometry(QtCore.QRect(775, 82, 3, 88))
        self.line_28.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_28.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_28.setObjectName('line_28')
        self.line_29 = QtWidgets.QFrame(parent=self.frame)
        self.line_29.setGeometry(QtCore.QRect(730, 80, 92, 3))
        self.line_29.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_29.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_29.setObjectName('line_29')
        self.line_35 = QtWidgets.QFrame(parent=self.frame)
        self.line_35.setGeometry(QtCore.QRect(990, 2, 3, 79))
        self.line_35.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_35.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_35.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_35.setObjectName('line_35')
        self.frame_22 = QtWidgets.QFrame(parent=self.frame)
        self.frame_22.setGeometry(QtCore.QRect(905, (-10), 85, 41))
        self.frame_22.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_22.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_22.setObjectName('frame_22')
        self.line_30 = QtWidgets.QFrame(parent=self.frame)
        self.line_30.setGeometry(QtCore.QRect(990, 80, 43, 3))
        self.line_30.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_30.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_30.setObjectName('line_30')
        self.frame_55 = QtWidgets.QFrame(parent=self.frame)
        self.frame_55.setGeometry(QtCore.QRect(905, 20, 42, 81))
        self.frame_55.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_55.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_55.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_55.setObjectName('frame_55')
        self.line_34 = QtWidgets.QFrame(parent=self.frame)
        self.line_34.setGeometry(QtCore.QRect(1030, 0, 3, 170))
        self.line_34.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_34.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_34.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_34.setObjectName('line_34')
        self.line_32 = QtWidgets.QFrame(parent=self.frame)
        self.line_32.setGeometry(QtCore.QRect(862, 80, 43, 3))
        self.line_32.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_32.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_32.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_32.setObjectName('line_32')
        self.line_31 = QtWidgets.QFrame(parent=self.frame)
        self.line_31.setGeometry(QtCore.QRect(902, 0, 3, 81))
        self.line_31.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_31.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_31.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_31.setObjectName('line_31')
        self.frame_54 = QtWidgets.QFrame(parent=self.frame)
        self.frame_54.setGeometry(QtCore.QRect(946, 20, 44, 81))
        self.frame_54.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_54.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_54.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_54.setObjectName('frame_54')
        self.line_33 = QtWidgets.QFrame(parent=self.frame)
        self.line_33.setGeometry(QtCore.QRect(946, 81, 3, 88))
        self.line_33.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_33.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_33.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_33.setObjectName('line_33')
        self.line_37 = QtWidgets.QFrame(parent=self.frame)
        self.line_37.setGeometry(QtCore.QRect(1074, 80, 43, 3))
        self.line_37.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_37.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_37.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_37.setObjectName('line_37')
        self.line_38 = QtWidgets.QFrame(parent=self.frame)
        self.line_38.setGeometry(QtCore.QRect(1074, 2, 3, 79))
        self.line_38.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_38.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_38.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_38.setObjectName('line_38')
        self.frame_31 = QtWidgets.QFrame(parent=self.frame)
        self.frame_31.setGeometry(QtCore.QRect(1033, (-3), 41, 50))
        self.frame_31.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_31.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_31.setObjectName('frame_31')
        self.frame_14 = QtWidgets.QFrame(parent=self.frame_tela)
        self.frame_14.setGeometry(QtCore.QRect(19, 41, 435, 171))
        self.frame_14.setStyleSheet('\nbackground-color: rgb(255, 255, 255);\n                border-left: 2px solid black;\n                border-top: 2px solid black;\nborder-right: none;')
        self.frame_14.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_14.setObjectName('frame_14')
        self.line_63 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_63.setGeometry(QtCore.QRect(554, 3, 1, 104))
        self.line_63.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_63.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_63.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_63.setObjectName('line_63')
        self.line_64 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_64.setGeometry(QtCore.QRect(512, 60, 109, 1))
        self.line_64.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_64.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_64.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_64.setObjectName('line_64')
        self.line_17 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_17.setGeometry(QtCore.QRect(510, 0, 3, 108))
        self.line_17.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_17.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_17.setObjectName('line_17')
        self.frame_43 = QtWidgets.QFrame(parent=self.frame_14)
        self.frame_43.setGeometry(QtCore.QRect(513, 61, 41, 50))
        self.frame_43.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_43.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_43.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_43.setObjectName('frame_43')
        self.line_118 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_118.setGeometry(QtCore.QRect(620, 2, 3, 108))
        self.line_118.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_118.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_118.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_118.setObjectName('line_118')
        self.frame_44 = QtWidgets.QFrame(parent=self.frame_14)
        self.frame_44.setGeometry(QtCore.QRect(691, 60, 38, 50))
        self.frame_44.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_44.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_44.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_44.setObjectName('frame_44')
        self.line_119 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_119.setGeometry(QtCore.QRect(620, 60, 109, 1))
        self.line_119.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_119.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_119.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_119.setObjectName('line_119')
        self.line_120 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_120.setGeometry(QtCore.QRect(690, 3, 1, 104))
        self.line_120.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_120.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_120.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_120.setObjectName('line_120')
        self.line_50 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_50.setGeometry(QtCore.QRect(44, 90, 3, 81))
        self.line_50.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_50.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_50.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_50.setObjectName('line_50')
        self.line_80 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_80.setGeometry(QtCore.QRect(261, 90, 44, 3))
        self.line_80.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_80.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_80.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_80.setObjectName('line_80')
        self.frame_36 = QtWidgets.QFrame(parent=self.frame_14)
        self.frame_36.setGeometry(QtCore.QRect(218, 124, 41, 50))
        self.frame_36.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_36.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_36.setObjectName('frame_36')
        self.line_52 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_52.setGeometry(QtCore.QRect(259, 2, 3, 169))
        self.line_52.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_52.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_52.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_52.setObjectName('line_52')
        self.line_53 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_53.setGeometry(QtCore.QRect(305, 90, 3, 80))
        self.line_53.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_53.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_53.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_53.setObjectName('line_53')
        self.frame_37 = QtWidgets.QFrame(parent=self.frame_14)
        self.frame_37.setGeometry(QtCore.QRect(2, 124, 42, 50))
        self.frame_37.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_37.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_37.setObjectName('frame_37')
        self.line_81 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_81.setGeometry(QtCore.QRect(177, 90, 44, 3))
        self.line_81.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_81.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_81.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_81.setObjectName('line_81')
        self.line_84 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_84.setGeometry(QtCore.QRect(45, 90, 44, 3))
        self.line_84.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_84.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_84.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_84.setObjectName('line_84')
        self.line_55 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_55.setGeometry(QtCore.QRect(133, 90, 3, 81))
        self.line_55.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_55.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_55.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_55.setObjectName('line_55')
        self.line_56 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_56.setGeometry(QtCore.QRect(219, 90, 3, 79))
        self.line_56.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_56.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_56.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_56.setObjectName('line_56')
        self.line_58 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_58.setGeometry(QtCore.QRect(175, 0, 3, 170))
        self.line_58.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_58.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_58.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_58.setObjectName('line_58')
        self.line_59 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_59.setGeometry(QtCore.QRect(89, 0, 3, 170))
        self.line_59.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_59.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_59.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_59.setObjectName('line_59')
        self.line_85 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_85.setGeometry(QtCore.QRect(132, 90, 44, 3))
        self.line_85.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_85.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_85.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_85.setObjectName('line_85')
        self.frame_39 = QtWidgets.QFrame(parent=self.frame_14)
        self.frame_39.setGeometry(QtCore.QRect(92, 124, 41, 50))
        self.frame_39.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_39.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_39.setObjectName('frame_39')
        self.line_86 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_86.setGeometry(QtCore.QRect(393, 91, 42, 3))
        self.line_86.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_86.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_86.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_86.setObjectName('line_86')
        self.line_65 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_65.setGeometry(QtCore.QRect(393, 92, 3, 81))
        self.line_65.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_65.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_65.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_65.setObjectName('line_65')
        self.line_66 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_66.setGeometry(QtCore.QRect(432, 0, 3, 92))
        self.line_66.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_66.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_66.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_66.setObjectName('line_66')
        self.frame_56 = QtWidgets.QFrame(parent=self.frame_14)
        self.frame_56.setGeometry(QtCore.QRect(349, 80, 44, 81))
        self.frame_56.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_56.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_56.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_56.setObjectName('frame_56')
        self.frame_57 = QtWidgets.QFrame(parent=self.frame_14)
        self.frame_57.setGeometry(QtCore.QRect(308, 80, 42, 81))
        self.frame_57.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_57.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_57.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_57.setObjectName('frame_57')
        self.frame_23 = QtWidgets.QFrame(parent=self.frame_14)
        self.frame_23.setGeometry(QtCore.QRect(308, 140, 85, 41))
        self.frame_23.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_23.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_23.setObjectName('frame_23')
        self.line_61 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_61.setGeometry(QtCore.QRect(350, 0, 3, 94))
        self.line_61.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_61.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_61.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_61.setObjectName('line_61')
        self.frame_3 = QtWidgets.QFrame(parent=self.frame_tela)
        self.frame_3.setGeometry(QtCore.QRect(454, 60, 244, 151))
        self.frame_3.setStyleSheet('background-color: rgb(255, 255, 255);border: none;')
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName('frame_3')
        self.label = QtWidgets.QLabel(parent=self.frame_3)
        self.label.setGeometry(QtCore.QRect(79, 30, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet('color: white;\nbackground-color:BLACK;\nborder-color: transparent; \ntransform: rotate(270deg);')
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName('label')
        self.frame_20 = QtWidgets.QFrame(parent=self.frame_tela)
        self.frame_20.setGeometry(QtCore.QRect(1150, 260, 147, 157))
        self.frame_20.setStyleSheet('background-color: rgb(255, 255, 255);\nborder: 2px solid #2E3D48')
        self.frame_20.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_20.setObjectName('frame_20')
        self.label_ocupado2_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.label_ocupado2_3.setGeometry(QtCore.QRect(40, 130, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_ocupado2_3.setFont(font)
        self.label_ocupado2_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_ocupado2_3.setObjectName('label_ocupado2_3')
        self.label_bloqueado2_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.label_bloqueado2_3.setGeometry(QtCore.QRect(40, 100, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_bloqueado2_3.setFont(font)
        self.label_bloqueado2_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_bloqueado2_3.setObjectName('label_bloqueado2_3')
        self.label_vago2_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.label_vago2_3.setGeometry(QtCore.QRect(40, 40, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_vago2_3.setFont(font)
        self.label_vago2_3.setStyleSheet('background-color: rgb(255, 255, 255);\nborder: transparent;')
        self.label_vago2_3.setObjectName('label_vago2_3')
        self.label_reservado2_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.label_reservado2_3.setGeometry(QtCore.QRect(40, 70, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_reservado2_3.setFont(font)
        self.label_reservado2_3.setStyleSheet('background-color: rgb(255, 255, 255);\nborder: transparent;')
        self.label_reservado2_3.setObjectName('label_reservado2_3')
        self.cor_legenda_red_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.cor_legenda_red_3.setGeometry(QtCore.QRect(10, 130, 21, 21))
        self.cor_legenda_red_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 0, 0);')
        self.cor_legenda_red_3.setText('')
        self.cor_legenda_red_3.setObjectName('cor_legenda_red_3')
        self.cor_b_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.cor_b_3.setGeometry(QtCore.QRect(10, 100, 21, 21))
        self.cor_b_3.setStyleSheet('\nborder: transparent;background-color: rgb(170, 170, 255);')
        self.cor_b_3.setText('')
        self.cor_b_3.setObjectName('cor_b_3')
        self.cor_legenda_blue_4 = QtWidgets.QLabel(parent=self.frame_20)
        self.cor_legenda_blue_4.setGeometry(QtCore.QRect(10, 40, 21, 21))
        self.cor_legenda_blue_4.setStyleSheet('background-color: rgb(170, 255, 255);\nborder-left-color: rgb(0, 0, 0);\nborder-bottom-color: rgb(0, 0, 0);\nborder-right-color: rgb(0, 0, 0);\nborder-right-color: rgb(0, 0, 0);\nborder-top-color: rgb(0, 0, 0);\nborder-color: rgb(0, 0, 0);\nborder: transparent;')
        self.cor_legenda_blue_4.setText('')
        self.cor_legenda_blue_4.setObjectName('cor_legenda_blue_4')
        self.legenda_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.legenda_3.setGeometry(QtCore.QRect(10, 10, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.legenda_3.setFont(font)
        self.legenda_3.setStyleSheet('background-color: rgb(255, 255, 255);\nborder: transparent;')
        self.legenda_3.setObjectName('legenda_3')
        self.cor_legenda_yellow_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.cor_legenda_yellow_3.setGeometry(QtCore.QRect(10, 70, 21, 21))
        self.cor_legenda_yellow_3.setStyleSheet('\nborder: transparent;\nbackground-color: rgb(255, 255, 0);')
        self.cor_legenda_yellow_3.setText('')
        self.cor_legenda_yellow_3.setObjectName('cor_legenda_yellow_3')
        self.labels = []
        if self.tela.help_sccrol_painel:
            self.tela.monitora = False
            self.tela.abri_cti(Form, 'UNIDADE DE INTERNAÇÃO - 08L')

        for row in range(self.tela.conta_linha()):
            leito = self.tela.leito(row)
            if self.tela.help_sccrol_painel:
                label = QLabel(leito.text(), self.frame_tela)
            else:
                label = QLabel(leito.text(), self.tela.frame_do_monitoramento)

            label.setGeometry(0, 0, 60, 25)
            filename = 'monitora_oitavo_leste.csv'
            if self.tela.help_sccrol_painel:
                filename = 'monitora_oitavo_lestepainel.csv'

            try:
                with open(filename, mode='r') as file:
                    reader = csv.reader(file)
                    data = list(reader)
                    for row in range(len(data)):
                        if data[row][0] == leito.text():
                            x = int(data[row][1])
                            y = int(data[row][2])
                            label.setGeometry(x, y, 70, 25)
                            break
            except FileNotFoundError:
                print("File not found")

            label.setAlignment(Qt.AlignmentFlag.AlignCenter)
            label.setCursor(Qt.CursorShape.OpenHandCursor)
            label.mousePressEvent = lambda event, label=label: self.mousePressEvent(event, label)
            label.mouseMoveEvent = lambda event, label=label: self.mouseMoveEvent(event, label)
            label.setWordWrap(True)
            fonte = QFont()
            fonte.setPointSize(10)
            label.setFont(fonte)
            label.setStyleSheet('background-color: rgb(170, 255, 255);')
            self.labels.append(label)
            self.atualizar_monitoramento(Form)

        else:
            self.conf_layout()
            if self.tela.help_sccrol_painel:
                self.tela.total_bloq += self.bloqueado
                self.tela.total_vago += self.vago
                self.tela.qt_vagos_8leste = self.vago
                self.tela.total_rese += self.reservado
                self.tela.total_ocup += self.ocupado
                self.tela.qt_int_adulto2 += self.ocupado
                self.tela.qt_int_adulto_total2 += self.total

    def atualizar_monitoramento(self, Form):
        self.vago = 0
        self.reservado = 0
        self.ocupado = 0
        self.bloqueado = 0
        self.total = 0
        colum_nome = 0
        colum_status = 0
        for colum in range(1, self.tela.tabela_grade.columnCount()):
            item_pac = self.tela.tabela_grade.horizontalHeaderItem(colum)
            if item_pac.text() == 'NOME DO PACIENTE':
                colum_nome = colum
            if item_pac.text() == 'STATUS DO LEITO':
                colum_status = colum
        for row in range(self.tela.conta_linha()):
            selecao = self.tela.item(row, colum_status)
            leitos = self.tela.leito(row)
            LEITOS = leitos.text()
            paciente = self.tela.item(row, colum_nome).text()
            self.total += 1
            if selecao.text() == 'VAGO':
                print(1)
                self.vago += 1
                for label in self.labels:
                    if label.text() == LEITOS:
                        label.setAlignment(Qt.AlignmentFlag.AlignCenter)
                        tooltip_text = 'Leito Vago'
                        label.setToolTip(tooltip_text)
            if selecao.text() == 'OCUPADO':
                for label in self.labels:
                    if label.text() == LEITOS:
                        label.setAlignment(Qt.AlignmentFlag.AlignCenter)
                        tooltip_text = f'Paciente: {paciente} \n Leito: {LEITOS}'
                        label.setToolTip(tooltip_text)
                        font = QtGui.QFont()
                        font.setBold(True)
                        font.setWeight(75)
                        label.setFont(font)
                        label.setStyleSheet('background-color: rgb(255, 0, 0);')
                self.ocupado += 1
            if selecao.text() == 'RESERVADO':
                print(4145)
                for label in self.labels:
                    if label.text() == LEITOS:
                        print(LEITOS)
                        label.setAlignment(Qt.AlignmentFlag.AlignCenter)
                        tooltip_text = f'Paciente: {paciente} \n Leito: {LEITOS}'
                        label.setToolTip(tooltip_text)
                        font = QtGui.QFont()
                        font.setBold(True)
                        font.setWeight(75)
                        label.setFont(font)
                        label.setStyleSheet('background-color: rgb(255, 255, 0);')
                self.reservado += 1
            if selecao.text() == 'BLOQUEADO':
                for label in self.labels:
                    if label.text() == LEITOS:
                        label.setAlignment(Qt.AlignmentFlag.AlignCenter)
                        tooltip_text = 'Leito Bloqueado'
                        label.setToolTip(tooltip_text)
                        font = QtGui.QFont()
                        font.setBold(True)
                        font.setWeight(75)
                        label.setFont(font)
                        label.setStyleSheet('background-color: rgb(170, 170, 255);')
                self.bloqueado += 1
            if self.tela.help_sccrol_painel == True:
                if selecao.text() == 'BLOQUEADO POR FALTA DE FUNCIONÁRIOS':
                    self.tela.qt_se_fun += 1
                    self.bloqueado += 1
                if selecao.text() == 'PONTUAL - BLOQUEADO POR FALTA DE FUNCIONÁRIOS':
                    self.tela.qt_pront += 1
                    self.bloqueado += 1
                if selecao.text() == 'BLOQUEADO POR MANUTENÇÃO':
                    self.tela.qt_bl_manu += 1
                    self.bloqueado += 1
                if selecao.text() == 'BLOQUEADO POR VM/VNI':
                    self.tela.qt_bl_VM_VNI += 1
                    self.bloqueado += 1
        self.retranslateUi(Form)

    def mousePressEvent(self, event, label):
        label.mouse_offset = event.pos()

    def mouseMoveEvent(self, event, label):
        if event.buttons() == Qt.MouseButton.LeftButton:
            new_pos = label.mapToParent(event.pos() - label.mouse_offset)
            label.move(new_pos)
            x, y = (new_pos.x(), new_pos.y())
            if not self.tela.help_sccrol_painel == True:
                frame = self.tela.frame_do_monitoramento
            else:  # inserted
                frame = self.frame_tela
            if frame:
                frame_rect = frame.rect()
                new_pos.setX(max(frame_rect.left(), min(new_pos.x(), frame_rect.right() - label.width())))
                new_pos.setY(max(frame_rect.top(), min(new_pos.y(), frame_rect.bottom() - label.height())))
                label.move(new_pos)
        filename = 'monitora_oitavo_leste.csv'
        if self.tela.help_sccrol_painel == True:
            filename = 'monitora_oitavo_lestepainel.csv'
        with open(filename, mode='w', newline='') as file:
            writer = csv.writer(file)
            for lisa in self.labels:
                texto = lisa.text()
                posicao = lisa.pos()
                writer.writerow([texto, posicao.x(), posicao.y()])

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.label_ocupado1_3.setText(_translate('Form', 'OCUPADO :'))
        self.label_tabela_3.setText(_translate('Form', 'TABELA :'))
        vago = str(self.vago)
        reservado = str(self.reservado)
        bloqueado = str(self.bloqueado)
        ocupado = str(self.ocupado)
        self.qt_vago_3.setText(_translate('Form', vago))
        self.label_bloq1_3.setText(_translate('Form', 'BLOQUEADO :'))
        self.qt_reservado_3.setText(_translate('Form', reservado))
        self.qt_bloqueado_3.setText(_translate('Form', bloqueado))
        self.label_reser1_3.setText(_translate('Form', 'RESERVADO :'))
        self.qt_ocupado_3.setText(_translate('Form', ocupado))
        self.label_vago1_3.setText(_translate('Form', 'VAGO :'))
        self.label.setText(_translate('Form', 'POSTO'))
        self.label_ocupado2_3.setText(_translate('Form', 'OCUPADO'))
        self.label_bloqueado2_3.setText(_translate('Form', 'BLOQUEADO'))
        self.label_vago2_3.setText(_translate('Form', 'VAGO'))
        self.label_reservado2_3.setText(_translate('Form', 'RESERVADO'))
        self.legenda_3.setText(_translate('Form', 'LEGENDA :'))

    def conf_layout(self):
        if self.settings.contains('tema'):
            font_name = self.settings.value('font', defaultValue='')
            backcolocor = self.settings.value('tema', defaultValue='')
            color = self.settings.value('color', defaultValue='')
            tamanho = int(self.settings.value('tamanho', defaultValue=10))
            self.backcolocor = backcolocor
            self.color = color
            self.font = font_name
            self.tamanho = tamanho
            if not self.tela.help_sccrol_painel == True:
                self.tela.frame_do_monitoramento.setStyleSheet('QFrame { background-color: transparent; border: 1px solid black; border-radius: 10px; box-shadow: 5px 5px 5px grey; }')