# Decompiled with PyLingual (https://pylingual.io)
# Internal filename: segundo_ALA_SUL.py
# Bytecode version: 3.12.0rc2 (3531)
# Source timestamp: 1970-01-01 00:00:00 UTC (0)

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QRect, Qt, QSettings, QStandardPaths, Qt
import csv
from PyQt6.QtWidgets import QLabel

class Ui_Form(object):
    def setupUi(self, Form, frame, tela):
        self.tela = tela
        self.settings = QSettings('HC', 'SGL')
        self.form = Form
        script_directory = QStandardPaths.writableLocation(QStandardPaths.StandardLocation.AppDataLocation)
        config_file_path = f'{script_directory}/config.ini'
        self.settings = QSettings(config_file_path, QSettings.Format.IniFormat)
        self.frame_tela = frame
        self.frame_2 = QtWidgets.QFrame(parent=self.frame_tela)
        self.frame_2.setGeometry(QtCore.QRect(167, 240, 841, 40))
        self.frame_2.setStyleSheet('background-color: #c0c0c0;\n')
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName('frame_2')
        self.frame_20 = QtWidgets.QFrame(parent=self.frame_tela)
        self.frame_20.setGeometry(QtCore.QRect(1016, 280, 147, 157))
        self.frame_20.setStyleSheet('background-color: rgb(255, 255, 255);\nborder: 2px solid #2E3D48')
        self.frame_20.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_20.setObjectName('frame_20')
        self.label_ocupado2_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.label_ocupado2_3.setGeometry(QtCore.QRect(40, 130, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_ocupado2_3.setFont(font)
        self.label_ocupado2_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_ocupado2_3.setObjectName('label_ocupado2_3')
        self.label_bloqueado2_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.label_bloqueado2_3.setGeometry(QtCore.QRect(40, 100, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_bloqueado2_3.setFont(font)
        self.label_bloqueado2_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_bloqueado2_3.setObjectName('label_bloqueado2_3')
        self.label_vago2_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.label_vago2_3.setGeometry(QtCore.QRect(40, 40, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_vago2_3.setFont(font)
        self.label_vago2_3.setStyleSheet('background-color: rgb(255, 255, 255);\nborder: transparent;')
        self.label_vago2_3.setObjectName('label_vago2_3')
        self.label_reservado2_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.label_reservado2_3.setGeometry(QtCore.QRect(40, 70, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_reservado2_3.setFont(font)
        self.label_reservado2_3.setStyleSheet('background-color: rgb(255, 255, 255);\nborder: transparent;')
        self.label_reservado2_3.setObjectName('label_reservado2_3')
        self.cor_legenda_red_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.cor_legenda_red_3.setGeometry(QtCore.QRect(10, 130, 21, 21))
        self.cor_legenda_red_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 0, 0);')
        self.cor_legenda_red_3.setText('')
        self.cor_legenda_red_3.setObjectName('cor_legenda_red_3')
        self.cor_b_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.cor_b_3.setGeometry(QtCore.QRect(10, 100, 21, 21))
        self.cor_b_3.setStyleSheet('\nborder: transparent;background-color: rgb(170, 170, 255);')
        self.cor_b_3.setText('')
        self.cor_b_3.setObjectName('cor_b_3')
        self.cor_legenda_blue_4 = QtWidgets.QLabel(parent=self.frame_20)
        self.cor_legenda_blue_4.setGeometry(QtCore.QRect(10, 40, 21, 21))
        self.cor_legenda_blue_4.setStyleSheet('background-color: rgb(170, 255, 255);\nborder-left-color: rgb(0, 0, 0);\nborder-bottom-color: rgb(0, 0, 0);\nborder-right-color: rgb(0, 0, 0);\nborder-right-color: rgb(0, 0, 0);\nborder-top-color: rgb(0, 0, 0);\nborder-color: rgb(0, 0, 0);\nborder: transparent;')
        self.cor_legenda_blue_4.setText('')
        self.cor_legenda_blue_4.setObjectName('cor_legenda_blue_4')
        self.legenda_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.legenda_3.setGeometry(QtCore.QRect(10, 10, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.legenda_3.setFont(font)
        self.legenda_3.setStyleSheet('background-color: rgb(255, 255, 255);\nborder: transparent;')
        self.legenda_3.setObjectName('legenda_3')
        self.cor_legenda_yellow_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.cor_legenda_yellow_3.setGeometry(QtCore.QRect(10, 70, 21, 21))
        self.cor_legenda_yellow_3.setStyleSheet('\nborder: transparent;\nbackground-color: rgb(255, 255, 0);')
        self.cor_legenda_yellow_3.setText('')
        self.cor_legenda_yellow_3.setObjectName('cor_legenda_yellow_3')
        self.frame_13 = QtWidgets.QFrame(parent=self.frame_tela)
        self.frame_13.setGeometry(QtCore.QRect(716, 280, 291, 161))
        self.frame_13.setStyleSheet('                border-bottom: 2px solid black;\n\nbackground-color: rgb(255, 255, 255);\n                border-left: 2px solid black;\n                border-right: 2px solid black;\n')
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName('frame_13')
        self.frame_30 = QtWidgets.QFrame(parent=self.frame_13)
        self.frame_30.setGeometry(QtCore.QRect(691, 60, 38, 50))
        self.frame_30.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_30.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_30.setObjectName('frame_30')
        self.line_109 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_109.setGeometry(QtCore.QRect(690, 3, 1, 104))
        self.line_109.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_109.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_109.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_109.setObjectName('line_109')
        self.line_22 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_22.setGeometry(QtCore.QRect(169, 0, 3, 160))
        self.line_22.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_22.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_22.setObjectName('line_22')
        self.frame_12 = QtWidgets.QFrame(parent=self.frame_13)
        self.frame_12.setGeometry(QtCore.QRect(172, (-3), 40, 57))
        self.frame_12.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName('frame_12')
        self.line_59 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_59.setGeometry(QtCore.QRect(170, 80, 118, 1))
        self.line_59.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_59.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_59.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_59.setObjectName('line_59')
        self.frame_14 = QtWidgets.QFrame(parent=self.frame_13)
        self.frame_14.setGeometry(QtCore.QRect(79, (-3), 40, 57))
        self.frame_14.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_14.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_14.setObjectName('frame_14')
        self.line_60 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_60.setGeometry(QtCore.QRect(0, 80, 118, 1))
        self.line_60.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_60.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_60.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_60.setObjectName('line_60')
        self.line_78 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_78.setGeometry(QtCore.QRect(78, 1, 1, 158))
        self.line_78.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_78.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_78.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_78.setObjectName('line_78')
        self.line_79 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_79.setGeometry(QtCore.QRect(212, 0, 1, 158))
        self.line_79.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_79.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_79.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_79.setObjectName('line_79')
        self.line_23 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_23.setGeometry(QtCore.QRect(119, 0, 3, 160))
        self.line_23.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_23.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_23.setObjectName('line_23')
        self.frame = QtWidgets.QFrame(parent=self.frame_tela)
        self.frame.setGeometry(QtCore.QRect(166, 70, 841, 171))
        self.frame.setStyleSheet('                border-left: 2px solid black;\nbackground-color: rgb(255, 255, 255);\n                border-top: 2px solid black;\n                border-right: 2px solid black;\n')
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName('frame')
        self.line_40 = QtWidgets.QFrame(parent=self.frame)
        self.line_40.setGeometry(QtCore.QRect(0, 50, 196, 1))
        self.line_40.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_40.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_40.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_40.setObjectName('line_40')
        self.line_42 = QtWidgets.QFrame(parent=self.frame)
        self.line_42.setGeometry(QtCore.QRect(337, 0, 1, 171))
        self.line_42.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_42.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_42.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_42.setObjectName('line_42')
        self.line_5 = QtWidgets.QFrame(parent=self.frame)
        self.line_5.setGeometry(QtCore.QRect(180, 0, 3, 170))
        self.line_5.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_5.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_5.setObjectName('line_5')
        self.frame_8 = QtWidgets.QFrame(parent=self.frame)
        self.frame_8.setGeometry(QtCore.QRect(70, 117, 38, 57))
        self.frame_8.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName('frame_8')
        self.line_18 = QtWidgets.QFrame(parent=self.frame)
        self.line_18.setGeometry(QtCore.QRect(418, 0, 3, 170))
        self.line_18.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_18.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_18.setObjectName('line_18')
        self.line_44 = QtWidgets.QFrame(parent=self.frame)
        self.line_44.setGeometry(QtCore.QRect(420, 0, 200, 2))
        self.line_44.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_44.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_44.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_44.setObjectName('line_44')
        self.line_47 = QtWidgets.QFrame(parent=self.frame)
        self.line_47.setGeometry(QtCore.QRect(70, 0, 1, 171))
        self.line_47.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_47.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_47.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_47.setObjectName('line_47')
        self.line_49 = QtWidgets.QFrame(parent=self.frame)
        self.line_49.setGeometry(QtCore.QRect(0, 114, 197, 1))
        self.line_49.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_49.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_49.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_49.setObjectName('line_49')
        self.line_50 = QtWidgets.QFrame(parent=self.frame)
        self.line_50.setGeometry(QtCore.QRect(160, 50, 115, 1))
        self.line_50.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_50.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_50.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_50.setObjectName('line_50')
        self.line_51 = QtWidgets.QFrame(parent=self.frame)
        self.line_51.setGeometry(QtCore.QRect(160, 114, 118, 1))
        self.line_51.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_51.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_51.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_51.setObjectName('line_51')
        self.line_52 = QtWidgets.QFrame(parent=self.frame)
        self.line_52.setGeometry(QtCore.QRect(280, 50, 139, 1))
        self.line_52.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_52.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_52.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_52.setObjectName('line_52')
        self.line_53 = QtWidgets.QFrame(parent=self.frame)
        self.line_53.setGeometry(QtCore.QRect(278, 114, 141, 1))
        self.line_53.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_53.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_53.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_53.setObjectName('line_53')
        self.line_74 = QtWidgets.QFrame(parent=self.frame)
        self.line_74.setGeometry(QtCore.QRect(220, 0, 3, 170))
        self.line_74.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_74.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_74.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_74.setObjectName('line_74')
        self.line_75 = QtWidgets.QFrame(parent=self.frame)
        self.line_75.setGeometry(QtCore.QRect(180, 168, 44, 3))
        self.line_75.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_75.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_75.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_75.setObjectName('line_75')
        self.line_76 = QtWidgets.QFrame(parent=self.frame)
        self.line_76.setGeometry(QtCore.QRect(594, 0, 3, 170))
        self.line_76.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_76.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_76.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_76.setObjectName('line_76')
        self.frame_26 = QtWidgets.QFrame(parent=self.frame)
        self.frame_26.setGeometry(QtCore.QRect(920, 0, 38, 50))
        self.frame_26.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_26.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_26.setObjectName('frame_26')
        self.line_88 = QtWidgets.QFrame(parent=self.frame)
        self.line_88.setGeometry(QtCore.QRect(640, 0, 3, 170))
        self.line_88.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_88.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_88.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_88.setObjectName('line_88')
        self.line_89 = QtWidgets.QFrame(parent=self.frame)
        self.line_89.setGeometry(QtCore.QRect(723, 0, 73, 2))
        self.line_89.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_89.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_89.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_89.setObjectName('line_89')
        self.line_90 = QtWidgets.QFrame(parent=self.frame)
        self.line_90.setGeometry(QtCore.QRect(846, 110, 111, 1))
        self.line_90.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_90.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_90.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_90.setObjectName('line_90')
        self.line_91 = QtWidgets.QFrame(parent=self.frame)
        self.line_91.setGeometry(QtCore.QRect(920, 0, 1, 170))
        self.line_91.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_91.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_91.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_91.setObjectName('line_91')
        self.line_92 = QtWidgets.QFrame(parent=self.frame)
        self.line_92.setGeometry(QtCore.QRect(845, 50, 111, 1))
        self.line_92.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_92.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_92.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_92.setObjectName('line_92')
        self.line_95 = QtWidgets.QFrame(parent=self.frame)
        self.line_95.setGeometry(QtCore.QRect(843, 0, 3, 170))
        self.line_95.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_95.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_95.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_95.setObjectName('line_95')
        self.line_98 = QtWidgets.QFrame(parent=self.frame)
        self.line_98.setGeometry(QtCore.QRect(960, 110, 71, 1))
        self.line_98.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_98.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_98.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_98.setObjectName('line_98')
        self.line_99 = QtWidgets.QFrame(parent=self.frame)
        self.line_99.setGeometry(QtCore.QRect(958, 0, 1, 170))
        self.line_99.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_99.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_99.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_99.setObjectName('line_99')
        self.line_100 = QtWidgets.QFrame(parent=self.frame)
        self.line_100.setGeometry(QtCore.QRect(960, 50, 69, 1))
        self.line_100.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_100.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_100.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_100.setObjectName('line_100')
        self.line_54 = QtWidgets.QFrame(parent=self.frame)
        self.line_54.setGeometry(QtCore.QRect(107, 0, 1, 171))
        self.line_54.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_54.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_54.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_54.setObjectName('line_54')
        self.line_67 = QtWidgets.QFrame(parent=self.frame)
        self.line_67.setGeometry(QtCore.QRect(300, 0, 1, 171))
        self.line_67.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_67.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_67.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_67.setObjectName('line_67')
        self.line_138 = QtWidgets.QFrame(parent=self.frame)
        self.line_138.setGeometry(QtCore.QRect(844, 0, 76, 2))
        self.line_138.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_138.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_138.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_138.setObjectName('line_138')
        self.line_139 = QtWidgets.QFrame(parent=self.frame)
        self.line_139.setGeometry(QtCore.QRect(958, 0, 73, 2))
        self.line_139.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_139.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_139.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_139.setObjectName('line_139')
        self.label_80 = QtWidgets.QLabel(parent=self.frame)
        self.frame_9 = QtWidgets.QFrame(parent=self.frame)
        self.frame_9.setGeometry(QtCore.QRect(300, 118, 40, 57))
        self.frame_9.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName('frame_9')
        self.line_93 = QtWidgets.QFrame(parent=self.frame)
        self.line_93.setGeometry(QtCore.QRect(490, 0, 1, 170))
        self.line_93.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_93.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_93.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_93.setObjectName('line_93')
        self.line_140 = QtWidgets.QFrame(parent=self.frame)
        self.line_140.setGeometry(QtCore.QRect(528, 0, 1, 170))
        self.line_140.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_140.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_140.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_140.setObjectName('line_140')
        self.line_94 = QtWidgets.QFrame(parent=self.frame)
        self.line_94.setGeometry(QtCore.QRect(421, 110, 175, 1))
        self.line_94.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_94.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_94.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_94.setObjectName('line_94')
        self.line_97 = QtWidgets.QFrame(parent=self.frame)
        self.line_97.setGeometry(QtCore.QRect(421, 50, 173, 1))
        self.line_97.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_97.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_97.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_97.setObjectName('line_97')
        self.frame_10 = QtWidgets.QFrame(parent=self.frame)
        self.frame_10.setGeometry(QtCore.QRect(490, 114, 39, 60))
        self.frame_10.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName('frame_10')
        self.line_55 = QtWidgets.QFrame(parent=self.frame)
        self.line_55.setGeometry(QtCore.QRect(643, 114, 81, 1))
        self.line_55.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_55.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_55.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_55.setObjectName('line_55')
        self.frame_11 = QtWidgets.QFrame(parent=self.frame)
        self.frame_11.setGeometry(QtCore.QRect(723, 118, 40, 57))
        self.frame_11.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName('frame_11')
        self.line_69 = QtWidgets.QFrame(parent=self.frame)
        self.line_69.setGeometry(QtCore.QRect(723, 0, 1, 171))
        self.line_69.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_69.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_69.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_69.setObjectName('line_69')
        self.line_56 = QtWidgets.QFrame(parent=self.frame)
        self.line_56.setGeometry(QtCore.QRect(643, 50, 71, 1))
        self.line_56.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_56.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_56.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_56.setObjectName('line_56')
        self.line_57 = QtWidgets.QFrame(parent=self.frame)
        self.line_57.setGeometry(QtCore.QRect(703, 50, 139, 1))
        self.line_57.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_57.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_57.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_57.setObjectName('line_57')
        self.line_58 = QtWidgets.QFrame(parent=self.frame)
        self.line_58.setGeometry(QtCore.QRect(701, 114, 141, 1))
        self.line_58.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_58.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_58.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_58.setObjectName('line_58')
        self.line_43 = QtWidgets.QFrame(parent=self.frame)
        self.line_43.setGeometry(QtCore.QRect(760, 0, 1, 171))
        self.line_43.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_43.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_43.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_43.setObjectName('line_43')
        self.frame_3 = QtWidgets.QFrame(parent=self.frame_tela)
        self.frame_3.setGeometry(QtCore.QRect(166, 280, 549, 161))
        self.frame_3.setStyleSheet('background-color: rgb(255, 255, 255);border: none;')
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName('frame_3')
        self.label = QtWidgets.QLabel(parent=self.frame_3)
        self.label.setGeometry(QtCore.QRect(180, 50, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet('color: white;\nbackground-color:BLACK;\nborder-color: transparent; \ntransform: rotate(270deg);')
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName('label')
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_tela)
        self.frame_6.setGeometry(QtCore.QRect(1016, 110, 199, 161))
        self.frame_6.setStyleSheet('background-color: rgb(255, 255, 255);\nborder: 2px solid #2E3D48')
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName('frame_6')
        self.label_ocupado1_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_ocupado1_3.setGeometry(QtCore.QRect(10, 130, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_ocupado1_3.setFont(font)
        self.label_ocupado1_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_ocupado1_3.setObjectName('label_ocupado1_3')
        self.label_tabela_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_tabela_3.setGeometry(QtCore.QRect(10, 10, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_tabela_3.setFont(font)
        self.label_tabela_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_tabela_3.setObjectName('label_tabela_3')
        self.qt_vago_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.qt_vago_3.setGeometry(QtCore.QRect(130, 40, 61, 21))
        font = QtGui.QFont()
        self.qt_vago_3.setFont(font)
        self.qt_vago_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.qt_vago_3.setObjectName('qt_vago_3')
        self.label_bloq1_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_bloq1_3.setGeometry(QtCore.QRect(10, 100, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_bloq1_3.setFont(font)
        self.label_bloq1_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_bloq1_3.setObjectName('label_bloq1_3')
        self.qt_reservado_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.qt_reservado_3.setGeometry(QtCore.QRect(130, 70, 61, 21))
        font = QtGui.QFont()
        self.qt_reservado_3.setFont(font)
        self.qt_reservado_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.qt_reservado_3.setObjectName('qt_reservado_3')
        self.qt_bloqueado_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.qt_bloqueado_3.setGeometry(QtCore.QRect(130, 100, 61, 21))
        font = QtGui.QFont()
        self.qt_bloqueado_3.setFont(font)
        self.qt_bloqueado_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.qt_bloqueado_3.setObjectName('qt_bloqueado_3')
        self.label_reser1_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_reser1_3.setGeometry(QtCore.QRect(10, 70, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_reser1_3.setFont(font)
        self.label_reser1_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_reser1_3.setObjectName('label_reser1_3')
        self.qt_ocupado_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.qt_ocupado_3.setGeometry(QtCore.QRect(130, 130, 61, 21))
        font = QtGui.QFont()
        self.qt_ocupado_3.setFont(font)
        self.qt_ocupado_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.qt_ocupado_3.setObjectName('qt_ocupado_3')
        self.label_vago1_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_vago1_3.setGeometry(QtCore.QRect(10, 40, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_vago1_3.setFont(font)
        self.label_vago1_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_vago1_3.setObjectName('label_vago1_3')
        self.line_110 = QtWidgets.QFrame(parent=self.frame_2)
        self.line_110.setGeometry(QtCore.QRect(834, 40, 191, 2))
        self.line_110.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_110.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_110.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_110.setObjectName('line_110')
        self.lisa = self.tela.retornar_frame()
        if self.tela.help_sccrol_painel == True:
            self.tela.monitora = False
            # self.tela.abri_cti(Form, 'UNIDADE DE INTERNAÇÃO - 02S')
            for cont, id in enumerate(self.tela.lista_titulo):
                if id == 'UNIDADE DE INTERNAÇÃO - 02S':
                    self.tela.abri_cti(Form, self.tela.lista_ids[cont], self.tela.lista_titulo[cont], self.tela.lista_dos_btn[cont])
                    break
        for row in range(self.tela.conta_linha()):
            leito = self.tela.leito(row)
            if 'aguardando' in leito.text():
                continue

            if self.tela.help_sccrol_painel:
                label = QLabel(leito.text(), self.frame_tela)
            else:
                label = QLabel(leito.text(), self.tela.frame_do_monitoramento)

            label.setGeometry(0, 0, 60, 25)
            filename = 'monitora_segundo_sul.csv'

            if self.tela.help_sccrol_painel:
                filename = 'monitora_segundo_sulpainel.csv'

            try:
                with open(filename, mode='r') as file:
                    reader = csv.reader(file)
                    data = list(reader)
                    for data_row in data:
                        if data_row[0] == leito.text():
                            x = int(data_row[1])
                            y = int(data_row[2])
                            label.setGeometry(x, y, 60, 30)
                            break
            except FileNotFoundError:
                print("Arquivo não encontrado:", filename)

            label.setAlignment(Qt.AlignmentFlag.AlignCenter)
            label.setCursor(Qt.CursorShape.OpenHandCursor)
            label.mousePressEvent = lambda event, label_aux=label: self.mousePressEvent(event, label_aux)
            label.mouseMoveEvent = lambda event, label_aux=label: self.mouseMoveEvent(event, label_aux)
            label.setStyleSheet('background-color: rgb(170, 255, 255);')
            label.setWordWrap(True)
            self.lisa.append(label)
            self.atualizar_monitoramento(Form)

            self.conf_layout()
            if self.tela.help_sccrol_painel:
                self.frame.move(153, 23)
                self.frame_3.move(153, 233)
                self.frame_2.move(153, 193)
                self.frame_13.move(703, 230)
                self.tela.qt_int_adulto2 += self.ocupado
                self.tela.qt_int_adulto_total2 += self.total
                self.tela.qt_vagos_2sul = self.vago
                self.frame_6.hide()
                self.frame_20.hide()
                self.tela.total_bloq += self.bloqueado
                self.tela.total_vago += self.vago
                self.tela.total_rese += self.reservado
                self.tela.total_ocup += self.ocupado

    def atualizar_monitoramento(self, Form):
        self.vago = 0
        self.reservado = 0
        self.ocupado = 0
        self.bloqueado = 0
        self.total = 0
        colum_nome = 0
        colum_status = 0
        for colum in range(1, self.tela.tabela_grade.columnCount()):
            item_pac = self.tela.tabela_grade.horizontalHeaderItem(colum)
            if item_pac.text() == 'NOME DO PACIENTE':
                colum_nome = colum
            if item_pac.text() == 'STATUS DO LEITO':
                colum_status = colum
        for row in range(self.tela.conta_linha()):
            selecao = self.tela.item(row, colum_status)
            leitos = self.tela.leito(row)
            LEITOS = leitos.text()
            paciente = self.tela.item(row, colum_nome).text()
            self.total += 1
            if selecao.text() == 'VAGO':
                self.vago += 1
                for label in self.lisa:
                    if label.text() == LEITOS:
                        label.setAlignment(Qt.AlignmentFlag.AlignCenter)
                        tooltip_text = 'Leito Vago'
                        label.setToolTip(tooltip_text)
            if selecao.text() == 'OCUPADO':
                for label in self.lisa:
                    if label.text() == LEITOS:
                        label.setAlignment(Qt.AlignmentFlag.AlignCenter)
                        tooltip_text = f'Paciente: {paciente} \n Leito: {LEITOS}'
                        label.setToolTip(tooltip_text)
                        font = QtGui.QFont()
                        font.setBold(True)
                        font.setWeight(75)
                        label.setFont(font)
                        label.setStyleSheet('background-color: rgb(255, 0, 0);')
                self.ocupado += 1
            if selecao.text() == 'RESERVADO':
                for label in self.lisa:
                    if label.text() == LEITOS:
                        label.setAlignment(Qt.AlignmentFlag.AlignCenter)
                        tooltip_text = f'Paciente: {paciente} \n Leito: {LEITOS}'
                        label.setToolTip(tooltip_text)
                        font = QtGui.QFont()
                        font.setBold(True)
                        font.setWeight(75)
                        label.setFont(font)
                        label.setStyleSheet('background-color: rgb(255, 255, 0);')
                self.reservado += 1
            if selecao.text() == 'BLOQUEADO':
                for label in self.lisa:
                    if label.text() == LEITOS:
                        label.setAlignment(Qt.AlignmentFlag.AlignCenter)
                        tooltip_text = 'Leito Bloqueado'
                        label.setToolTip(tooltip_text)
                        font = QtGui.QFont()
                        font.setBold(True)
                        font.setWeight(75)
                        label.setFont(font)
                        label.setStyleSheet('background-color: rgb(170, 170, 255);')
                self.bloqueado += 1
            if self.tela.help_sccrol_painel == True:
                if selecao.text() == 'BLOQUEADO POR FALTA DE FUNCIONÁRIOS':
                    self.tela.qt_se_fun += 1
                    self.bloqueado += 1
                if selecao.text() == 'PONTUAL - BLOQUEADO POR FALTA DE FUNCIONÁRIOS':
                    self.tela.qt_pront += 1
                    self.bloqueado += 1
                if selecao.text() == 'BLOQUEADO POR MANUTENÇÃO':
                    self.tela.qt_bl_manu += 1
                    self.bloqueado += 1
                if selecao.text() == 'BLOQUEADO POR VM/VNI':
                    self.tela.qt_bl_VM_VNI += 1
                    self.bloqueado += 1
        self.retranslateUi(self.frame_tela)

    def mousePressEvent(self, event, label):
        label.mouse_offset = event.pos()

    def mouseMoveEvent(self, event, label):
        if event.buttons() == Qt.MouseButton.LeftButton:
            new_pos = label.mapToParent(event.pos() - label.mouse_offset)
            label.move(new_pos)
            x, y = (new_pos.x(), new_pos.y())
            if not self.tela.help_sccrol_painel == True:
                frame = self.tela.frame_do_monitoramento
            else:  # inserted
                frame = self.frame_tela
            if frame:
                frame_rect = frame.rect()
                new_pos.setX(max(frame_rect.left(), min(new_pos.x(), frame_rect.right() - label.width())))
                new_pos.setY(max(frame_rect.top(), min(new_pos.y(), frame_rect.bottom() - label.height())))
                label.move(new_pos)
        filename = 'monitora_segundo_sul.csv'
        if self.tela.help_sccrol_painel == True:
            filename = 'monitora_segundo_sulpainel.csv'
        with open(filename, mode='w', newline='') as file:
            writer = csv.writer(file)
            for lisa in self.lisa:
                texto = lisa.text()
                posicao = lisa.pos()
                writer.writerow([texto, posicao.x(), posicao.y()])

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.label_ocupado2_3.setText(_translate('Form', 'OCUPADO'))
        self.label_bloqueado2_3.setText(_translate('Form', 'BLOQUEADO'))
        self.label_vago2_3.setText(_translate('Form', 'VAGO'))
        self.label_reservado2_3.setText(_translate('Form', 'RESERVADO'))
        self.legenda_3.setText(_translate('Form', 'LEGENDA :'))
        self.label.setText(_translate('Form', 'POSTO'))
        vago = str(self.vago)
        reservado = str(self.reservado)
        bloqueado = str(self.bloqueado)
        ocupado = str(self.ocupado)
        self.label_ocupado1_3.setText(_translate('Form', 'OCUPADO :'))
        self.label_tabela_3.setText(_translate('Form', 'TABELA :'))
        self.qt_vago_3.setText(_translate('Form', vago))
        self.label_bloq1_3.setText(_translate('Form', 'BLOQUEADO :'))
        self.qt_reservado_3.setText(_translate('Form', reservado))
        self.qt_bloqueado_3.setText(_translate('Form', bloqueado))
        self.label_reser1_3.setText(_translate('Form', 'RESERVADO :'))
        self.qt_ocupado_3.setText(_translate('Form', ocupado))
        self.label_vago1_3.setText(_translate('Form', 'VAGO :'))

    def conf_layout(self):
        if self.settings.contains('tema'):
            font_name = self.settings.value('font', defaultValue='')
            backcolocor = self.settings.value('tema', defaultValue='')
            color = self.settings.value('color', defaultValue='')
            tamanho = int(self.settings.value('tamanho', defaultValue=10))
            self.backcolocor = backcolocor
            self.color = color
            self.font = font_name
            self.tamanho = tamanho
            if not self.tela.help_sccrol_painel == True:
                self.tela.frame_do_monitoramento.setStyleSheet('QFrame { background-color: transparent; border: 1px solid black; border-radius: 10px; box-shadow: 5px 5px 5px grey; }')