# Decompiled with PyLingual (https://pylingual.io)
# Internal filename: setimo_ALA_LESTE.py
# Bytecode version: 3.12.0rc2 (3531)
# Source timestamp: 1970-01-01 00:00:00 UTC (0)

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6 import QtCore, QtGui, QtWidgets
import csv
from PyQt6.QtCore import QRect, Qt, QSettings, QStandardPaths, Qt
from PyQt6.QtWidgets import QLabel

class Ui_Form(object):
    def setupUi(self, Form, frame, tela):
        self.tela = tela
        self.form = Form
        self.settings = QSettings('HC', 'SGL')
        script_directory = QStandardPaths.writableLocation(QStandardPaths.StandardLocation.AppDataLocation)
        config_file_path = f'{script_directory}/config.ini'
        self.settings = QSettings(config_file_path, QSettings.Format.IniFormat)
        self.frame_tela = frame
        self.frame_2 = QtWidgets.QFrame(parent=self.frame_tela)
        self.frame_2.setGeometry(QtCore.QRect(11, 220, 1096, 40))
        self.frame_2.setStyleSheet('background-color: #c0c0c0;\n')
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName('frame_2')
        self.frame_13 = QtWidgets.QFrame(parent=self.frame_tela)
        self.frame_13.setGeometry(QtCore.QRect(725, 50, 341, 171))
        self.frame_13.setStyleSheet('\nbackground-color: rgb(255, 255, 255);\n                border-left: 2px solid black;\n                border-right: 2px solid black;\n                border-top: 2px solid black;\n')
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName('frame_13')
        self.line_36 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_36.setGeometry(QtCore.QRect(512, 60, 109, 1))
        self.line_36.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_36.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_36.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_36.setObjectName('line_36')
        self.frame_29 = QtWidgets.QFrame(parent=self.frame_13)
        self.frame_29.setGeometry(QtCore.QRect(513, 61, 41, 50))
        self.frame_29.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_29.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_29.setObjectName('frame_29')
        self.frame_30 = QtWidgets.QFrame(parent=self.frame_13)
        self.frame_30.setGeometry(QtCore.QRect(691, 60, 38, 50))
        self.frame_30.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent;')
        self.frame_30.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_30.setObjectName('frame_30')
        self.line_108 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_108.setGeometry(QtCore.QRect(620, 60, 109, 1))
        self.line_108.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_108.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_108.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_108.setObjectName('line_108')
        self.line_109 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_109.setGeometry(QtCore.QRect(690, 3, 1, 104))
        self.line_109.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_109.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_109.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_109.setObjectName('line_109')
        self.line_22 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_22.setGeometry(QtCore.QRect(170, 2, 3, 169))
        self.line_22.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_22.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_22.setObjectName('line_22')
        self.frame_27 = QtWidgets.QFrame(parent=self.frame_13)
        self.frame_27.setGeometry(QtCore.QRect(132, 131, 38, 50))
        self.frame_27.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_27.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_27.setObjectName('frame_27')
        self.frame_28 = QtWidgets.QFrame(parent=self.frame_13)
        self.frame_28.setGeometry(QtCore.QRect(173, 131, 38, 50))
        self.frame_28.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_28.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_28.setObjectName('frame_28')
        self.line_100 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_100.setGeometry(QtCore.QRect(174, 50, 164, 1))
        self.line_100.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_100.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_100.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_100.setObjectName('line_100')
        self.line_101 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_101.setGeometry(QtCore.QRect(172, 110, 166, 1))
        self.line_101.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_101.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_101.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_101.setObjectName('line_101')
        self.line_103 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_103.setGeometry(QtCore.QRect(260, 0, 1, 170))
        self.line_103.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_103.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_103.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_103.setObjectName('line_103')
        self.line_104 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_104.setGeometry(QtCore.QRect(4, 110, 166, 1))
        self.line_104.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_104.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_104.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_104.setObjectName('line_104')
        self.line_106 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_106.setGeometry(QtCore.QRect(90, 2, 1, 170))
        self.line_106.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_106.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_106.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_106.setObjectName('line_106')
        self.line_107 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_107.setGeometry(QtCore.QRect(4, 50, 164, 1))
        self.line_107.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_107.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_107.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_107.setObjectName('line_107')
        self.frame = QtWidgets.QFrame(parent=self.frame_tela)
        self.frame.setGeometry(QtCore.QRect(10, 259, 1096, 171))
        self.frame.setStyleSheet('                border-left: 2px solid black;\nbackground-color: rgb(255, 255, 255);\n                border-bottom: 2px solid black;\n                border-right: 2px solid black;\n')
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName('frame')
        self.line_5 = QtWidgets.QFrame(parent=self.frame)
        self.line_5.setGeometry(QtCore.QRect(180, 0, 3, 170))
        self.line_5.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_5.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_5.setObjectName('line_5')
        self.frame_18 = QtWidgets.QFrame(parent=self.frame)
        self.frame_18.setGeometry(QtCore.QRect(182, (-5), 192, 46))
        self.frame_18.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_18.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_18.setObjectName('frame_18')
        self.line_18 = QtWidgets.QFrame(parent=self.frame)
        self.line_18.setGeometry(QtCore.QRect(370, 0, 3, 170))
        self.line_18.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_18.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_18.setObjectName('line_18')
        self.line_51 = QtWidgets.QFrame(parent=self.frame)
        self.line_51.setGeometry(QtCore.QRect(160, 114, 118, 1))
        self.line_51.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_51.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_51.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_51.setObjectName('line_51')
        self.line_53 = QtWidgets.QFrame(parent=self.frame)
        self.line_53.setGeometry(QtCore.QRect(278, 114, 94, 1))
        self.line_53.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_53.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_53.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_53.setObjectName('line_53')
        self.line_39 = QtWidgets.QFrame(parent=self.frame)
        self.line_39.setGeometry(QtCore.QRect(310, 40, 62, 3))
        self.line_39.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_39.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_39.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_39.setObjectName('line_39')
        self.line_74 = QtWidgets.QFrame(parent=self.frame)
        self.line_74.setGeometry(QtCore.QRect(267, 40, 3, 130))
        self.line_74.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_74.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_74.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_74.setObjectName('line_74')
        self.line_76 = QtWidgets.QFrame(parent=self.frame)
        self.line_76.setGeometry(QtCore.QRect(580, 0, 3, 170))
        self.line_76.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_76.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_76.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_76.setObjectName('line_76')
        self.frame_25 = QtWidgets.QFrame(parent=self.frame)
        self.frame_25.setGeometry(QtCore.QRect(713, (-5), 38, 50))
        self.frame_25.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_25.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_25.setObjectName('frame_25')
        self.line_84 = QtWidgets.QFrame(parent=self.frame)
        self.line_84.setGeometry(QtCore.QRect(670, 2, 1, 168))
        self.line_84.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_84.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_84.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_84.setObjectName('line_84')
        self.line_85 = QtWidgets.QFrame(parent=self.frame)
        self.line_85.setGeometry(QtCore.QRect(500, 0, 1, 170))
        self.line_85.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_85.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_85.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_85.setObjectName('line_85')
        self.line_86 = QtWidgets.QFrame(parent=self.frame)
        self.line_86.setGeometry(QtCore.QRect(583, 110, 169, 1))
        self.line_86.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_86.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_86.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_86.setObjectName('line_86')
        self.line_87 = QtWidgets.QFrame(parent=self.frame)
        self.line_87.setGeometry(QtCore.QRect(420, 50, 161, 1))
        self.line_87.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_87.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_87.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_87.setObjectName('line_87')
        self.frame_26 = QtWidgets.QFrame(parent=self.frame)
        self.frame_26.setGeometry(QtCore.QRect(753, (-5), 38, 50))
        self.frame_26.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_26.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_26.setObjectName('frame_26')
        self.line_88 = QtWidgets.QFrame(parent=self.frame)
        self.line_88.setGeometry(QtCore.QRect(750, 0, 3, 170))
        self.line_88.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_88.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_88.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_88.setObjectName('line_88')
        self.line_91 = QtWidgets.QFrame(parent=self.frame)
        self.line_91.setGeometry(QtCore.QRect(920, 0, 1, 170))
        self.line_91.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_91.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_91.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_91.setObjectName('line_91')
        self.line_92 = QtWidgets.QFrame(parent=self.frame)
        self.line_92.setGeometry(QtCore.QRect(754, 50, 166, 1))
        self.line_92.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_92.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_92.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_92.setObjectName('line_92')
        self.line_95 = QtWidgets.QFrame(parent=self.frame)
        self.line_95.setGeometry(QtCore.QRect(920, 0, 3, 170))
        self.line_95.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_95.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_95.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_95.setObjectName('line_95')
        self.line_99 = QtWidgets.QFrame(parent=self.frame)
        self.line_99.setGeometry(QtCore.QRect(1010, 0, 1, 170))
        self.line_99.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_99.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_99.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_99.setObjectName('line_99')
        self.line_6 = QtWidgets.QFrame(parent=self.frame)
        self.line_6.setGeometry(QtCore.QRect(182, 39, 43, 3))
        self.line_6.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_6.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_6.setObjectName('line_6')
        self.line_34 = QtWidgets.QFrame(parent=self.frame)
        self.line_34.setGeometry(QtCore.QRect(420, 0, 3, 170))
        self.line_34.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_34.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_34.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_34.setObjectName('line_34')
        self.frame_45 = QtWidgets.QFrame(parent=self.frame)
        self.frame_45.setGeometry(QtCore.QRect(423, (-5), 38, 50))
        self.frame_45.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_45.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_45.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_45.setObjectName('frame_45')
        self.line_54 = QtWidgets.QFrame(parent=self.frame)
        self.line_54.setGeometry(QtCore.QRect(420, 110, 160, 1))
        self.line_54.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_54.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_54.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_54.setObjectName('line_54')
        self.line_93 = QtWidgets.QFrame(parent=self.frame)
        self.line_93.setGeometry(QtCore.QRect(583, 50, 166, 1))
        self.line_93.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_93.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_93.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_93.setObjectName('line_93')
        self.line_89 = QtWidgets.QFrame(parent=self.frame)
        self.line_89.setGeometry(QtCore.QRect(752, 110, 169, 1))
        self.line_89.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_89.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_89.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_89.setObjectName('line_89')
        self.line_94 = QtWidgets.QFrame(parent=self.frame)
        self.line_94.setGeometry(QtCore.QRect(839, 3, 1, 165))
        self.line_94.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_94.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_94.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_94.setObjectName('line_94')
        self.line_90 = QtWidgets.QFrame(parent=self.frame)
        self.line_90.setGeometry(QtCore.QRect(923, 110, 169, 1))
        self.line_90.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_90.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_90.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_90.setObjectName('line_90')
        self.frame_31 = QtWidgets.QFrame(parent=self.frame)
        self.frame_31.setGeometry(QtCore.QRect(1056, (-5), 38, 50))
        self.frame_31.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_31.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_31.setObjectName('frame_31')
        self.line_98 = QtWidgets.QFrame(parent=self.frame)
        self.line_98.setGeometry(QtCore.QRect(925, 50, 166, 1))
        self.line_98.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_98.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_98.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_98.setObjectName('line_98')
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_tela)
        self.frame_6.setGeometry(QtCore.QRect(1141, 100, 199, 161))
        self.frame_6.setStyleSheet('background-color: rgb(255, 255, 255);\nborder: 2px solid #2E3D48')
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName('frame_6')
        self.label_ocupado1_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_ocupado1_3.setGeometry(QtCore.QRect(10, 130, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_ocupado1_3.setFont(font)
        self.label_ocupado1_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_ocupado1_3.setObjectName('label_ocupado1_3')
        self.label_tabela_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_tabela_3.setGeometry(QtCore.QRect(10, 10, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_tabela_3.setFont(font)
        self.label_tabela_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_tabela_3.setObjectName('label_tabela_3')
        self.qt_vago_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.qt_vago_3.setGeometry(QtCore.QRect(130, 40, 61, 21))
        font = QtGui.QFont()
        self.qt_vago_3.setFont(font)
        self.qt_vago_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.qt_vago_3.setObjectName('qt_vago_3')
        self.label_bloq1_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_bloq1_3.setGeometry(QtCore.QRect(10, 100, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_bloq1_3.setFont(font)
        self.label_bloq1_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_bloq1_3.setObjectName('label_bloq1_3')
        self.qt_reservado_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.qt_reservado_3.setGeometry(QtCore.QRect(130, 70, 61, 21))
        font = QtGui.QFont()
        self.qt_reservado_3.setFont(font)
        self.qt_reservado_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.qt_reservado_3.setObjectName('qt_reservado_3')
        self.qt_bloqueado_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.qt_bloqueado_3.setGeometry(QtCore.QRect(130, 100, 61, 21))
        font = QtGui.QFont()
        self.qt_bloqueado_3.setFont(font)
        self.qt_bloqueado_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.qt_bloqueado_3.setObjectName('qt_bloqueado_3')
        self.label_reser1_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_reser1_3.setGeometry(QtCore.QRect(10, 70, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_reser1_3.setFont(font)
        self.label_reser1_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_reser1_3.setObjectName('label_reser1_3')
        self.qt_ocupado_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.qt_ocupado_3.setGeometry(QtCore.QRect(130, 130, 61, 21))
        font = QtGui.QFont()
        self.qt_ocupado_3.setFont(font)
        self.qt_ocupado_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.qt_ocupado_3.setObjectName('qt_ocupado_3')
        self.label_vago1_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_vago1_3.setGeometry(QtCore.QRect(10, 40, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_vago1_3.setFont(font)
        self.label_vago1_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_vago1_3.setObjectName('label_vago1_3')
        self.frame_20 = QtWidgets.QFrame(parent=self.frame_tela)
        self.frame_20.setGeometry(QtCore.QRect(1141, 270, 147, 157))
        self.frame_20.setStyleSheet('background-color: rgb(255, 255, 255);\nborder: 2px solid #2E3D48')
        self.frame_20.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_20.setObjectName('frame_20')
        self.label_ocupado2_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.label_ocupado2_3.setGeometry(QtCore.QRect(40, 130, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_ocupado2_3.setFont(font)
        self.label_ocupado2_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_ocupado2_3.setObjectName('label_ocupado2_3')
        self.label_bloqueado2_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.label_bloqueado2_3.setGeometry(QtCore.QRect(40, 100, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_bloqueado2_3.setFont(font)
        self.label_bloqueado2_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_bloqueado2_3.setObjectName('label_bloqueado2_3')
        self.label_vago2_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.label_vago2_3.setGeometry(QtCore.QRect(40, 40, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_vago2_3.setFont(font)
        self.label_vago2_3.setStyleSheet('background-color: rgb(255, 255, 255);\nborder: transparent;')
        self.label_vago2_3.setObjectName('label_vago2_3')
        self.label_reservado2_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.label_reservado2_3.setGeometry(QtCore.QRect(40, 70, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_reservado2_3.setFont(font)
        self.label_reservado2_3.setStyleSheet('background-color: rgb(255, 255, 255);\nborder: transparent;')
        self.label_reservado2_3.setObjectName('label_reservado2_3')
        self.cor_legenda_red_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.cor_legenda_red_3.setGeometry(QtCore.QRect(10, 130, 21, 21))
        self.cor_legenda_red_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 0, 0);')
        self.cor_legenda_red_3.setText('')
        self.cor_legenda_red_3.setObjectName('cor_legenda_red_3')
        self.cor_b_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.cor_b_3.setGeometry(QtCore.QRect(10, 100, 21, 21))
        self.cor_b_3.setStyleSheet('\nborder: transparent;background-color: rgb(170, 170, 255);')
        self.cor_b_3.setText('')
        self.cor_b_3.setObjectName('cor_b_3')
        self.cor_legenda_blue_4 = QtWidgets.QLabel(parent=self.frame_20)
        self.cor_legenda_blue_4.setGeometry(QtCore.QRect(10, 40, 21, 21))
        self.cor_legenda_blue_4.setStyleSheet('background-color: rgb(170, 255, 255);\nborder-left-color: rgb(0, 0, 0);\nborder-bottom-color: rgb(0, 0, 0);\nborder-right-color: rgb(0, 0, 0);\nborder-right-color: rgb(0, 0, 0);\nborder-top-color: rgb(0, 0, 0);\nborder-color: rgb(0, 0, 0);\nborder: transparent;')
        self.cor_legenda_blue_4.setText('')
        self.cor_legenda_blue_4.setObjectName('cor_legenda_blue_4')
        self.legenda_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.legenda_3.setGeometry(QtCore.QRect(10, 10, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.legenda_3.setFont(font)
        self.legenda_3.setStyleSheet('background-color: rgb(255, 255, 255);\nborder: transparent;')
        self.legenda_3.setObjectName('legenda_3')
        self.cor_legenda_yellow_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.cor_legenda_yellow_3.setGeometry(QtCore.QRect(10, 70, 21, 21))
        self.cor_legenda_yellow_3.setStyleSheet('\nborder: transparent;\nbackground-color: rgb(255, 255, 0);')
        self.cor_legenda_yellow_3.setText('')
        self.cor_legenda_yellow_3.setObjectName('cor_legenda_yellow_3')
        self.frame_3 = QtWidgets.QFrame(parent=self.frame_tela)
        self.frame_3.setGeometry(QtCore.QRect(370, 59, 354, 161))
        self.frame_3.setStyleSheet('background-color: rgb(255, 255, 255);border:none;')
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName('frame_3')
        self.label = QtWidgets.QLabel(parent=self.frame_3)
        self.label.setGeometry(QtCore.QRect(70, 40, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet('color: white;\nbackground-color:BLACK;\nborder-color: transparent; \ntransform: rotate(270deg);')
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName('label')
        self.frame_14 = QtWidgets.QFrame(parent=self.frame_tela)
        self.frame_14.setGeometry(QtCore.QRect(10, 40, 181, 181))
        self.frame_14.setStyleSheet('\nbackground-color: rgb(255, 255, 255);\n                border-left: 2px solid black;\n                border-right: 2px solid black;\n                border-top: 2px solid black;\n')
        self.frame_14.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_14.setObjectName('frame_14')
        self.line_63 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_63.setGeometry(QtCore.QRect(554, 3, 1, 104))
        self.line_63.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_63.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_63.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_63.setObjectName('line_63')
        self.line_64 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_64.setGeometry(QtCore.QRect(512, 60, 109, 1))
        self.line_64.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_64.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_64.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_64.setObjectName('line_64')
        self.line_17 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_17.setGeometry(QtCore.QRect(510, 0, 3, 108))
        self.line_17.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_17.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_17.setObjectName('line_17')
        self.frame_43 = QtWidgets.QFrame(parent=self.frame_14)
        self.frame_43.setGeometry(QtCore.QRect(513, 61, 41, 50))
        self.frame_43.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_43.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_43.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_43.setObjectName('frame_43')
        self.line_118 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_118.setGeometry(QtCore.QRect(620, 2, 3, 108))
        self.line_118.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_118.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_118.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_118.setObjectName('line_118')
        self.frame_44 = QtWidgets.QFrame(parent=self.frame_14)
        self.frame_44.setGeometry(QtCore.QRect(691, 60, 38, 50))
        self.frame_44.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_44.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_44.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_44.setObjectName('frame_44')
        self.line_119 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_119.setGeometry(QtCore.QRect(620, 60, 109, 1))
        self.line_119.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_119.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_119.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_119.setObjectName('line_119')
        self.line_120 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_120.setGeometry(QtCore.QRect(690, 3, 1, 104))
        self.line_120.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_120.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_120.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_120.setObjectName('line_120')
        self.frame_46 = QtWidgets.QFrame(parent=self.frame_14)
        self.frame_46.setGeometry(QtCore.QRect(142, 138, 38, 50))
        self.frame_46.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_46.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_46.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_46.setObjectName('frame_46')
        self.line_65 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_65.setGeometry(QtCore.QRect(90, 3, 1, 179))
        self.line_65.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_65.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_65.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_65.setObjectName('line_65')
        self.line_66 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_66.setGeometry(QtCore.QRect(0, 60, 181, 1))
        self.line_66.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_66.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_66.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_66.setObjectName('line_66')
        self.line_69 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_69.setGeometry(QtCore.QRect(0, 120, 181, 1))
        self.line_69.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_69.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_69.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_69.setObjectName('line_69')
        self.lisa = self.tela.retornar_frame()
        if self.tela.help_sccrol_painel == True:
            self.tela.monitora = False
            self.tela.abri_cti(Form, 'UNIDADE DE INTERNAÇÃO - 07L')
        for row in range(self.tela.conta_linha()):
            leito = self.tela.leito(row)
            if self.tela.help_sccrol_painel == True:
                label = QLabel(leito.text(), self.frame_tela)
            else:  # inserted
                label = QLabel(leito.text(), self.tela.frame_do_monitoramento)
            label.setGeometry(0, 0, 60, 25)
            filename = 'monitora_setimo_leste.csv'
            if self.tela.help_sccrol_painel == True:
                filename = 'monitora_setimo_lestepainel.csv'
            try:
                with open(filename, mode='r') as file:
                    pass  # postinserted
            except FileNotFoundError:
                print(1)
                    reader = csv.reader(file)
                    data = list(reader)
                    for row in range(len(data)):
                        if data[row][0] == leito.text():
                            x = int(data[row][1])
                            y = int(data[row][2])
                            label.setGeometry(x, y, 60, 30)
                            break
                        label.setAlignment(Qt.AlignmentFlag.AlignCenter)
                        label.setCursor(Qt.CursorShape.OpenHandCursor)
                        label.mousePressEvent = lambda event, label=label: self.mousePressEvent(event, label)
                        label.mouseMoveEvent = lambda event, label=label: self.mouseMoveEvent(event, label)
                        label.setStyleSheet('background-color: rgb(170, 255, 255)')
                        label.setWordWrap(True)
                        self.lisa.append(label)
                        self.atualizar_monitoramento(Form)
        else:  # inserted
            self.conf_layout()
            if self.tela.help_sccrol_painel == True:
                self.tela.qt_int_adulto2 += self.ocupado
                self.tela.qt_int_adulto_total2 += self.total
                self.tela.total_bloq += self.bloqueado
                self.tela.total_vago += self.vago
                self.tela.total_rese += self.reservado
                self.tela.total_ocup += self.ocupado
                self.tela.qt_vagos_7leste = self.vago

    def atualizar_monitoramento(self, Form):
        self.vago = 0
        self.reservado = 0
        self.ocupado = 0
        self.bloqueado = 0
        self.total = 0
        colum_nome = 0
        colum_status = 0
        for colum in range(1, self.tela.tabela_grade.columnCount()):
            item_pac = self.tela.tabela_grade.horizontalHeaderItem(colum)
            if item_pac.text() == 'NOME DO PACIENTE':
                colum_nome = colum
            if item_pac.text() == 'STATUS DO LEITO':
                colum_status = colum
        for row in range(self.tela.conta_linha()):
            selecao = self.tela.item(row, colum_status)
            leitos = self.tela.leito(row)
            LEITOS = leitos.text()
            paciente = self.tela.item(row, colum_nome).text()
            self.total += 1
            if selecao.text() == 'VAGO':
                self.vago += 1
                for label in self.lisa:
                    if label.text() == LEITOS:
                        label.setAlignment(Qt.AlignmentFlag.AlignCenter)
                        tooltip_text = 'Leito Vago'
                        label.setToolTip(tooltip_text)
            if selecao.text() == 'OCUPADO':
                for label in self.lisa:
                    if label.text() == LEITOS:
                        label.setAlignment(Qt.AlignmentFlag.AlignCenter)
                        tooltip_text = f'Paciente: {paciente} \n Leito: {LEITOS}'
                        label.setToolTip(tooltip_text)
                        font = QtGui.QFont()
                        font.setBold(True)
                        font.setWeight(75)
                        label.setFont(font)
                        label.setStyleSheet('background-color: rgb(255, 0, 0);')
                self.ocupado += 1
            if selecao.text() == 'RESERVADO':
                for label in self.lisa:
                    if label.text() == LEITOS:
                        label.setAlignment(Qt.AlignmentFlag.AlignCenter)
                        tooltip_text = f'Paciente: {paciente} \n Leito: {LEITOS}'
                        label.setToolTip(tooltip_text)
                        font = QtGui.QFont()
                        font.setBold(True)
                        font.setWeight(75)
                        label.setFont(font)
                        label.setStyleSheet('background-color: rgb(255, 255, 0);')
                self.reservado += 1
            if selecao.text() == 'BLOQUEADO':
                for label in self.lisa:
                    if label.text() == LEITOS:
                        label.setAlignment(Qt.AlignmentFlag.AlignCenter)
                        tooltip_text = 'Leito Bloqueado'
                        label.setToolTip(tooltip_text)
                        font = QtGui.QFont()
                        font.setBold(True)
                        font.setWeight(75)
                        label.setFont(font)
                        label.setStyleSheet('background-color: rgb(170, 170, 255);')
                self.bloqueado += 1
            if self.tela.help_sccrol_painel == True:
                if selecao.text() == 'BLOQUEADO POR FALTA DE FUNCIONÁRIOS':
                    self.tela.qt_se_fun += 1
                    self.bloqueado += 1
                if selecao.text() == 'PONTUAL - BLOQUEADO POR FALTA DE FUNCIONÁRIOS':
                    self.tela.qt_pront += 1
                    self.bloqueado += 1
                if selecao.text() == 'BLOQUEADO POR MANUTENÇÃO':
                    self.tela.qt_bl_manu += 1
                    self.bloqueado += 1
                if selecao.text() == 'BLOQUEADO POR VM/VNI':
                    self.tela.qt_bl_VM_VNI += 1
                    self.bloqueado += 1
        self.retranslateUi(Form)

    def mousePressEvent(self, event, label):
        label.mouse_offset = event.pos()

    def mouseMoveEvent(self, event, label):
        if event.buttons() == Qt.MouseButton.LeftButton:
            new_pos = label.mapToParent(event.pos() - label.mouse_offset)
            label.move(new_pos)
            x, y = (new_pos.x(), new_pos.y())
            if not self.tela.help_sccrol_painel == True:
                frame = self.tela.frame_do_monitoramento
            else:  # inserted
                frame = self.frame_tela
            if frame:
                frame_rect = frame.rect()
                new_pos.setX(max(frame_rect.left(), min(new_pos.x(), frame_rect.right() - label.width())))
                new_pos.setY(max(frame_rect.top(), min(new_pos.y(), frame_rect.bottom() - label.height())))
                label.move(new_pos)
        filename = 'monitora_setimo_leste.csv'
        if self.tela.help_sccrol_painel == True:
            filename = 'monitora_setimo_lestepainel.csv'
        with open(filename, mode='w', newline='') as file:
            writer = csv.writer(file)
            for lisa in self.lisa:
                texto = lisa.text()
                posicao = lisa.pos()
                writer.writerow([texto, posicao.x(), posicao.y()])

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        vago = str(self.vago)
        reservado = str(self.reservado)
        bloqueado = str(self.bloqueado)
        ocupado = str(self.ocupado)
        self.label_ocupado1_3.setText(_translate('Form', 'OCUPADO :'))
        self.label_tabela_3.setText(_translate('Form', 'TABELA :'))
        self.qt_vago_3.setText(_translate('Form', vago))
        self.label_bloq1_3.setText(_translate('Form', 'BLOQUEADO :'))
        self.qt_reservado_3.setText(_translate('Form', reservado))
        self.qt_bloqueado_3.setText(_translate('Form', bloqueado))
        self.label_reser1_3.setText(_translate('Form', 'RESERVADO :'))
        self.qt_ocupado_3.setText(_translate('Form', ocupado))
        self.label_vago1_3.setText(_translate('Form', 'VAGO :'))
        self.label_ocupado2_3.setText(_translate('Form', 'OCUPADO'))
        self.label_bloqueado2_3.setText(_translate('Form', 'BLOQUEADO'))
        self.label_vago2_3.setText(_translate('Form', 'VAGO'))
        self.label_reservado2_3.setText(_translate('Form', 'RESERVADO'))
        self.legenda_3.setText(_translate('Form', 'LEGENDA :'))
        self.label.setText(_translate('Form', 'POSTO'))

    def conf_layout(self):
        if self.settings.contains('tema'):
            font_name = self.settings.value('font', defaultValue='')
            backcolocor = self.settings.value('tema', defaultValue='')
            color = self.settings.value('color', defaultValue='')
            tamanho = int(self.settings.value('tamanho', defaultValue=10))
            self.backcolocor = backcolocor
            self.color = color
            self.font = font_name
            self.tamanho = tamanho
            if not self.tela.help_sccrol_painel == True:
                self.tela.frame_do_monitoramento.setStyleSheet('QFrame { background-color: transparent; border: 1px solid black; border-radius: 10px; box-shadow: 5px 5px 5px grey; }')