# Decompiled with PyLingual (https://pylingual.io)
# Internal filename: sexto_LESTE_monitoramento.py
# Bytecode version: 3.12.0rc2 (3531)
# Source timestamp: 1970-01-01 00:00:00 UTC (0)

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QRect, Qt, QSettings, QStandardPaths, Qt
from PyQt6.QtWidgets import QLabel
import csv
from PyQt6.QtGui import QFont

class Ui_Form(object):
    def setupUi(self, Form, frame, tela):
        self.tela = tela
        self.settings = QSettings('HC', 'SGL')
        self.form = Form
        self.frame_tela = frame
        script_directory = QStandardPaths.writableLocation(QStandardPaths.StandardLocation.AppDataLocation)
        config_file_path = f'{script_directory}/config.ini'
        self.settings = QSettings(config_file_path, QSettings.Format.IniFormat)
        self.frame_2 = QtWidgets.QFrame(parent=self.frame_tela)
        self.frame_2.setGeometry(QtCore.QRect(12, 160, 1311, 40))
        self.frame_2.setStyleSheet('background-color: #c0c0c0;\n')
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName('frame_2')
        self.frame = QtWidgets.QFrame(parent=self.frame_tela)
        self.frame.setGeometry(QtCore.QRect(10, 201, 1313, 171))
        self.frame.setStyleSheet('                border-left: 2px solid black;\nbackground-color: rgb(255, 255, 255);\n                border-bottom: 2px solid black;\n                border-right: 2px solid black;\n')
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName('frame')
        self.line_40 = QtWidgets.QFrame(parent=self.frame)
        self.line_40.setGeometry(QtCore.QRect(0, 50, 118, 1))
        self.line_40.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_40.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_40.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_40.setObjectName('line_40')
        self.line_41 = QtWidgets.QFrame(parent=self.frame)
        self.line_41.setGeometry(QtCore.QRect(158, 0, 1, 170))
        self.line_41.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_41.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_41.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_41.setObjectName('line_41')
        self.line_42 = QtWidgets.QFrame(parent=self.frame)
        self.line_42.setGeometry(QtCore.QRect(280, 0, 1, 170))
        self.line_42.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_42.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_42.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_42.setObjectName('line_42')
        self.line_43 = QtWidgets.QFrame(parent=self.frame)
        self.line_43.setGeometry(QtCore.QRect(477, 0, 1, 179))
        self.line_43.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_43.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_43.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_43.setObjectName('line_43')
        self.line_5 = QtWidgets.QFrame(parent=self.frame)
        self.line_5.setGeometry(QtCore.QRect(117, 0, 3, 170))
        self.line_5.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_5.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_5.setObjectName('line_5')
        self.line_14 = QtWidgets.QFrame(parent=self.frame)
        self.line_14.setGeometry(QtCore.QRect(239, 0, 3, 170))
        self.line_14.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_14.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_14.setObjectName('line_14')
        self.frame_8 = QtWidgets.QFrame(parent=self.frame)
        self.frame_8.setGeometry(QtCore.QRect(79, (-3), 38, 50))
        self.frame_8.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName('frame_8')
        self.frame_12 = QtWidgets.QFrame(parent=self.frame)
        self.frame_12.setGeometry(QtCore.QRect(120, (-3), 38, 50))
        self.frame_12.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName('frame_12')
        self.frame_18 = QtWidgets.QFrame(parent=self.frame)
        self.frame_18.setGeometry(QtCore.QRect(242, (-3), 38, 50))
        self.frame_18.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_18.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_18.setObjectName('frame_18')
        self.line_18 = QtWidgets.QFrame(parent=self.frame)
        self.line_18.setGeometry(QtCore.QRect(359, 0, 3, 170))
        self.line_18.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_18.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_18.setObjectName('line_18')
        self.frame_19 = QtWidgets.QFrame(parent=self.frame)
        self.frame_19.setGeometry(QtCore.QRect(440, (-3), 38, 50))
        self.frame_19.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_19.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_19.setObjectName('frame_19')
        self.line_47 = QtWidgets.QFrame(parent=self.frame)
        self.line_47.setGeometry(QtCore.QRect(78, 0, 1, 171))
        self.line_47.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_47.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_47.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_47.setObjectName('line_47')
        self.line_49 = QtWidgets.QFrame(parent=self.frame)
        self.line_49.setGeometry(QtCore.QRect(0, 114, 118, 1))
        self.line_49.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_49.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_49.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_49.setObjectName('line_49')
        self.line_74 = QtWidgets.QFrame(parent=self.frame)
        self.line_74.setGeometry(QtCore.QRect(478, 0, 3, 170))
        self.line_74.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_74.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_74.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_74.setObjectName('line_74')
        self.line_83 = QtWidgets.QFrame(parent=self.frame)
        self.line_83.setGeometry(QtCore.QRect(710, 0, 3, 170))
        self.line_83.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_83.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_83.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_83.setObjectName('line_83')
        self.line_88 = QtWidgets.QFrame(parent=self.frame)
        self.line_88.setGeometry(QtCore.QRect(830, 0, 3, 170))
        self.line_88.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_88.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_88.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_88.setObjectName('line_88')
        self.line_95 = QtWidgets.QFrame(parent=self.frame)
        self.line_95.setGeometry(QtCore.QRect(950, 0, 3, 170))
        self.line_95.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_95.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_95.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_95.setObjectName('line_95')
        self.frame_27 = QtWidgets.QFrame(parent=self.frame)
        self.frame_27.setGeometry(QtCore.QRect(1030, (-3), 38, 50))
        self.frame_27.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_27.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_27.setObjectName('frame_27')
        self.line_99 = QtWidgets.QFrame(parent=self.frame)
        self.line_99.setGeometry(QtCore.QRect(1030, 0, 1, 170))
        self.line_99.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_99.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_99.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_99.setObjectName('line_99')
        self.line_50 = QtWidgets.QFrame(parent=self.frame)
        self.line_50.setGeometry(QtCore.QRect(119, 50, 118, 1))
        self.line_50.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_50.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_50.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_50.setObjectName('line_50')
        self.line_52 = QtWidgets.QFrame(parent=self.frame)
        self.line_52.setGeometry(QtCore.QRect(243, 113, 118, 1))
        self.line_52.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_52.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_52.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_52.setObjectName('line_52')
        self.line_53 = QtWidgets.QFrame(parent=self.frame)
        self.line_53.setGeometry(QtCore.QRect(240, 50, 118, 1))
        self.line_53.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_53.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_53.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_53.setObjectName('line_53')
        self.line_54 = QtWidgets.QFrame(parent=self.frame)
        self.line_54.setGeometry(QtCore.QRect(360, 90, 118, 1))
        self.line_54.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_54.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_54.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_54.setObjectName('line_54')
        self.line_56 = QtWidgets.QFrame(parent=self.frame)
        self.line_56.setGeometry(QtCore.QRect(440, 0, 1, 170))
        self.line_56.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_56.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_56.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_56.setObjectName('line_56')
        self.line_57 = QtWidgets.QFrame(parent=self.frame)
        self.line_57.setGeometry(QtCore.QRect(559, 0, 1, 171))
        self.line_57.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_57.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_57.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_57.setObjectName('line_57')
        self.line_44 = QtWidgets.QFrame(parent=self.frame)
        self.line_44.setGeometry(QtCore.QRect(481, 90, 118, 1))
        self.line_44.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_44.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_44.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_44.setObjectName('line_44')
        self.line_6 = QtWidgets.QFrame(parent=self.frame)
        self.line_6.setGeometry(QtCore.QRect(598, 0, 3, 170))
        self.line_6.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_6.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_6.setObjectName('line_6')
        self.frame_14 = QtWidgets.QFrame(parent=self.frame)
        self.frame_14.setGeometry(QtCore.QRect(601, (-3), 38, 50))
        self.frame_14.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_14.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_14.setObjectName('frame_14')
        self.line_59 = QtWidgets.QFrame(parent=self.frame)
        self.line_59.setGeometry(QtCore.QRect(639, 0, 1, 170))
        self.line_59.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_59.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_59.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_59.setObjectName('line_59')
        self.line_61 = QtWidgets.QFrame(parent=self.frame)
        self.line_61.setGeometry(QtCore.QRect(612, 383, 118, 1))
        self.line_61.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_61.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_61.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_61.setObjectName('line_61')
        self.frame_9 = QtWidgets.QFrame(parent=self.frame)
        self.frame_9.setGeometry(QtCore.QRect(560, (-3), 38, 50))
        self.frame_9.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName('frame_9')
        self.line_58 = QtWidgets.QFrame(parent=self.frame)
        self.line_58.setGeometry(QtCore.QRect(590, 90, 118, 1))
        self.line_58.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_58.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_58.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_58.setObjectName('line_58')
        self.frame_15 = QtWidgets.QFrame(parent=self.frame)
        self.frame_15.setGeometry(QtCore.QRect(713, (-3), 38, 50))
        self.frame_15.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_15.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_15.setObjectName('frame_15')
        self.line_60 = QtWidgets.QFrame(parent=self.frame)
        self.line_60.setGeometry(QtCore.QRect(750, 0, 1, 170))
        self.line_60.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_60.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_60.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_60.setObjectName('line_60')
        self.line_62 = QtWidgets.QFrame(parent=self.frame)
        self.line_62.setGeometry(QtCore.QRect(710, 90, 118, 1))
        self.line_62.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_62.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_62.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_62.setObjectName('line_62')
        self.line_63 = QtWidgets.QFrame(parent=self.frame)
        self.line_63.setGeometry(QtCore.QRect(910, 0, 1, 170))
        self.line_63.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_63.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_63.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_63.setObjectName('line_63')
        self.line_64 = QtWidgets.QFrame(parent=self.frame)
        self.line_64.setGeometry(QtCore.QRect(833, 90, 118, 1))
        self.line_64.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_64.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_64.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_64.setObjectName('line_64')
        self.frame_21 = QtWidgets.QFrame(parent=self.frame)
        self.frame_21.setGeometry(QtCore.QRect(910, (-3), 40, 50))
        self.frame_21.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_21.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_21.setObjectName('frame_21')
        self.line_65 = QtWidgets.QFrame(parent=self.frame)
        self.line_65.setGeometry(QtCore.QRect(953, 90, 118, 1))
        self.line_65.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_65.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_65.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_65.setObjectName('line_65')
        self.line_97 = QtWidgets.QFrame(parent=self.frame)
        self.line_97.setGeometry(QtCore.QRect(1068, 0, 3, 170))
        self.line_97.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_97.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_97.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_97.setObjectName('line_97')
        self.frame_28 = QtWidgets.QFrame(parent=self.frame)
        self.frame_28.setGeometry(QtCore.QRect(1071, (-3), 38, 50))
        self.frame_28.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_28.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_28.setObjectName('frame_28')
        self.frame_31 = QtWidgets.QFrame(parent=self.frame_28)
        self.frame_31.setGeometry(QtCore.QRect(40, 0, 38, 50))
        self.frame_31.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_31.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_31.setObjectName('frame_31')
        self.line_100 = QtWidgets.QFrame(parent=self.frame)
        self.line_100.setGeometry(QtCore.QRect(1109, 0, 1, 170))
        self.line_100.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_100.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_100.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_100.setObjectName('line_100')
        self.line_66 = QtWidgets.QFrame(parent=self.frame)
        self.line_66.setGeometry(QtCore.QRect(1070, 90, 118, 1))
        self.line_66.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_66.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_66.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_66.setObjectName('line_66')
        self.line_98 = QtWidgets.QFrame(parent=self.frame)
        self.line_98.setGeometry(QtCore.QRect(1190, 0, 3, 170))
        self.line_98.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_98.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_98.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_98.setObjectName('line_98')
        self.frame_32 = QtWidgets.QFrame(parent=self.frame)
        self.frame_32.setGeometry(QtCore.QRect(1193, (-3), 38, 50))
        self.frame_32.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_32.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_32.setObjectName('frame_32')
        self.frame_33 = QtWidgets.QFrame(parent=self.frame_32)
        self.frame_33.setGeometry(QtCore.QRect(40, 0, 38, 50))
        self.frame_33.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_33.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_33.setObjectName('frame_33')
        self.line_67 = QtWidgets.QFrame(parent=self.frame)
        self.line_67.setGeometry(QtCore.QRect(1192, 49, 118, 1))
        self.line_67.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_67.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_67.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_67.setObjectName('line_67')
        self.line_68 = QtWidgets.QFrame(parent=self.frame)
        self.line_68.setGeometry(QtCore.QRect(1200, 380, 118, 1))
        self.line_68.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_68.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_68.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_68.setObjectName('line_68')
        self.line_69 = QtWidgets.QFrame(parent=self.frame)
        self.line_69.setGeometry(QtCore.QRect(1190, 110, 118, 1))
        self.line_69.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_69.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_69.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_69.setObjectName('line_69')
        self.line_112 = QtWidgets.QFrame(parent=self.frame)
        self.line_112.setGeometry(QtCore.QRect(1230, 0, 1, 170))
        self.line_112.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_112.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_112.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_112.setObjectName('line_112')
        self.frame_13 = QtWidgets.QFrame(parent=self.frame_tela)
        self.frame_13.setGeometry(QtCore.QRect(472, 56, 731, 111))
        self.frame_13.setStyleSheet('\nbackground-color: rgb(255, 255, 255);\n                border-right: 2px solid black;\n')
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName('frame_13')
        self.frame_17 = QtWidgets.QFrame(parent=self.frame_13)
        self.frame_17.setGeometry(QtCore.QRect(180, 140, 38, 50))
        self.frame_17.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_17.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_17.setObjectName('frame_17')
        self.line_35 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_35.setGeometry(QtCore.QRect(530, 3, 1, 104))
        self.line_35.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_35.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_35.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_35.setObjectName('line_35')
        self.line_36 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_36.setGeometry(QtCore.QRect(460, 60, 109, 1))
        self.line_36.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_36.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_36.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_36.setObjectName('line_36')
        self.label = QtWidgets.QLabel(parent=self.frame_13)
        self.label.setGeometry(QtCore.QRect(20, 10, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet('color: white;\nbackground-color:BLACK;\nborder-color: transparent; \ntransform: rotate(270deg);')
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName('label')
        self.line_13 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_13.setGeometry(QtCore.QRect(460, 0, 3, 112))
        self.line_13.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_13.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_13.setObjectName('line_13')
        self.frame_29 = QtWidgets.QFrame(parent=self.frame_13)
        self.frame_29.setGeometry(QtCore.QRect(530, 64, 41, 50))
        self.frame_29.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_29.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_29.setObjectName('frame_29')
        self.line_105 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_105.setGeometry(QtCore.QRect(620, 2, 3, 108))
        self.line_105.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_105.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_105.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_105.setObjectName('line_105')
        self.frame_30 = QtWidgets.QFrame(parent=self.frame_13)
        self.frame_30.setGeometry(QtCore.QRect(691, 63, 38, 50))
        self.frame_30.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.frame_30.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_30.setObjectName('frame_30')
        self.line_108 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_108.setGeometry(QtCore.QRect(620, 60, 109, 1))
        self.line_108.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_108.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_108.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_108.setObjectName('line_108')
        self.line_109 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_109.setGeometry(QtCore.QRect(690, 3, 1, 104))
        self.line_109.setStyleSheet('background-color: #c0c0c0;\nborder-color: transparent; ')
        self.line_109.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_109.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_109.setObjectName('line_109')
        self.line_113 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_113.setGeometry(QtCore.QRect(570, 2, 3, 110))
        self.line_113.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_113.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_113.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_113.setObjectName('line_113')
        self.line_103 = QtWidgets.QFrame(parent=self.frame_13)
        self.line_103.setGeometry(QtCore.QRect(460, 0, 271, 3))
        self.line_103.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.line_103.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_103.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_103.setObjectName('line_103')
        self.frame_20 = QtWidgets.QFrame(parent=self.frame_tela)
        self.frame_20.setGeometry(QtCore.QRect(10, 0, 147, 157))
        self.frame_20.setStyleSheet('background-color: rgb(255, 255, 255);\nborder: 2px solid #2E3D48')
        self.frame_20.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_20.setObjectName('frame_20')
        self.label_ocupado2_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.label_ocupado2_3.setGeometry(QtCore.QRect(40, 130, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_ocupado2_3.setFont(font)
        self.label_ocupado2_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_ocupado2_3.setObjectName('label_ocupado2_3')
        self.label_bloqueado2_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.label_bloqueado2_3.setGeometry(QtCore.QRect(40, 100, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_bloqueado2_3.setFont(font)
        self.label_bloqueado2_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_bloqueado2_3.setObjectName('label_bloqueado2_3')
        self.label_vago2_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.label_vago2_3.setGeometry(QtCore.QRect(40, 40, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_vago2_3.setFont(font)
        self.label_vago2_3.setStyleSheet('background-color: rgb(255, 255, 255);\nborder: transparent;')
        self.label_vago2_3.setObjectName('label_vago2_3')
        self.label_reservado2_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.label_reservado2_3.setGeometry(QtCore.QRect(40, 70, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_reservado2_3.setFont(font)
        self.label_reservado2_3.setStyleSheet('background-color: rgb(255, 255, 255);\nborder: transparent;')
        self.label_reservado2_3.setObjectName('label_reservado2_3')
        self.cor_legenda_red_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.cor_legenda_red_3.setGeometry(QtCore.QRect(10, 130, 21, 21))
        self.cor_legenda_red_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 0, 0);')
        self.cor_legenda_red_3.setText('')
        self.cor_legenda_red_3.setObjectName('cor_legenda_red_3')
        self.cor_b_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.cor_b_3.setGeometry(QtCore.QRect(10, 100, 21, 21))
        self.cor_b_3.setStyleSheet('\nborder: transparent;background-color: rgb(170, 170, 255);')
        self.cor_b_3.setText('')
        self.cor_b_3.setObjectName('cor_b_3')
        self.cor_legenda_blue_4 = QtWidgets.QLabel(parent=self.frame_20)
        self.cor_legenda_blue_4.setGeometry(QtCore.QRect(10, 40, 21, 21))
        self.cor_legenda_blue_4.setStyleSheet('background-color: rgb(170, 255, 255);\nborder-left-color: rgb(0, 0, 0);\nborder-bottom-color: rgb(0, 0, 0);\nborder-right-color: rgb(0, 0, 0);\nborder-right-color: rgb(0, 0, 0);\nborder-top-color: rgb(0, 0, 0);\nborder-color: rgb(0, 0, 0);\nborder: transparent;')
        self.cor_legenda_blue_4.setText('')
        self.cor_legenda_blue_4.setObjectName('cor_legenda_blue_4')
        self.legenda_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.legenda_3.setGeometry(QtCore.QRect(10, 10, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.legenda_3.setFont(font)
        self.legenda_3.setStyleSheet('background-color: rgb(255, 255, 255);\nborder: transparent;')
        self.legenda_3.setObjectName('legenda_3')
        self.cor_legenda_yellow_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.cor_legenda_yellow_3.setGeometry(QtCore.QRect(10, 70, 21, 21))
        self.cor_legenda_yellow_3.setStyleSheet('\nborder: transparent;\nbackground-color: rgb(255, 255, 0);')
        self.cor_legenda_yellow_3.setText('')
        self.cor_legenda_yellow_3.setObjectName('cor_legenda_yellow_3')
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_tela)
        self.frame_6.setGeometry(QtCore.QRect(180, 0, 199, 161))
        self.frame_6.setStyleSheet('background-color: rgb(255, 255, 255);\nborder: 2px solid #2E3D48')
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName('frame_6')
        self.label_ocupado1_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_ocupado1_3.setGeometry(QtCore.QRect(10, 130, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_ocupado1_3.setFont(font)
        self.label_ocupado1_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_ocupado1_3.setObjectName('label_ocupado1_3')
        self.label_tabela_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_tabela_3.setGeometry(QtCore.QRect(10, 10, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_tabela_3.setFont(font)
        self.label_tabela_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_tabela_3.setObjectName('label_tabela_3')
        self.qt_vago_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.qt_vago_3.setGeometry(QtCore.QRect(130, 40, 61, 21))
        font = QtGui.QFont()
        self.qt_vago_3.setFont(font)
        self.qt_vago_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.qt_vago_3.setObjectName('qt_vago_3')
        self.label_bloq1_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_bloq1_3.setGeometry(QtCore.QRect(10, 100, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_bloq1_3.setFont(font)
        self.label_bloq1_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_bloq1_3.setObjectName('label_bloq1_3')
        self.qt_reservado_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.qt_reservado_3.setGeometry(QtCore.QRect(130, 70, 61, 21))
        font = QtGui.QFont()
        self.qt_reservado_3.setFont(font)
        self.qt_reservado_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.qt_reservado_3.setObjectName('qt_reservado_3')
        self.qt_bloqueado_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.qt_bloqueado_3.setGeometry(QtCore.QRect(130, 100, 61, 21))
        font = QtGui.QFont()
        self.qt_bloqueado_3.setFont(font)
        self.qt_bloqueado_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.qt_bloqueado_3.setObjectName('qt_bloqueado_3')
        self.label_reser1_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_reser1_3.setGeometry(QtCore.QRect(10, 70, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_reser1_3.setFont(font)
        self.label_reser1_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_reser1_3.setObjectName('label_reser1_3')
        self.qt_ocupado_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.qt_ocupado_3.setGeometry(QtCore.QRect(130, 130, 61, 21))
        font = QtGui.QFont()
        self.qt_ocupado_3.setFont(font)
        self.qt_ocupado_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.qt_ocupado_3.setObjectName('qt_ocupado_3')
        self.label_vago1_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_vago1_3.setGeometry(QtCore.QRect(10, 40, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_vago1_3.setFont(font)
        self.label_vago1_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_vago1_3.setObjectName('label_vago1_3')
        self.labels = []
        if self.tela.help_sccrol_painel == True:
            self.tela.monitora = False
 #           self.tela.abri_cti(Form, 'UNIDADE DE INTERNAÇÃO - 06L')
            for cont, id in enumerate(self.tela.lista_titulo):
                if id == 'UNIDADE DE INTERNAÇÃO - 06L':
                    self.tela.abri_cti(Form, self.tela.lista_ids[cont], self.tela.lista_titulo[cont], self.tela.lista_dos_btn[cont])
                    break
        for row in range(self.tela.conta_linha()):
            leito = self.tela.leito(row)
            if 'aguardando' in leito.text():
                continue
            if self.tela.help_sccrol_painel == True:
                label = QLabel(leito.text(), self.frame_tela)
            else:
                label = QLabel(leito.text(), self.tela.frame_do_monitoramento)

            label.setGeometry(0, 0, 60, 25)
            filename = 'monitora_sexto_leste.csv'

            if self.tela.help_sccrol_painel == True:
                filename = 'monitora_sexto_lestepainel.csv'

            try:
                with open(filename, mode='r') as file:
                    reader = csv.reader(file)
                    data = list(reader)
                    for row in range(len(data)):
                        if data[row][0] == leito.text():
                            x = int(data[row][1])
                            y = int(data[row][2])
                            label.setGeometry(x, y, 70, 40)
                            break
            except FileNotFoundError:
                print('Arquivo não encontrado:', filename)

            label.setAlignment(Qt.AlignmentFlag.AlignCenter)
            label.setCursor(Qt.CursorShape.OpenHandCursor)
            label.mousePressEvent = lambda event, label_aux=label: self.mousePressEvent(event, label_aux)
            label.mouseMoveEvent = lambda event, label_aux=label: self.mouseMoveEvent(event, label_aux)
            label.setWordWrap(True)

            fonte = QFont()
            fonte.setPointSize(10)
            label.setFont(fonte)
            label.setStyleSheet('background-color: rgb(170, 255, 255);')
            self.labels.append(label)

            self.atualizar_monitoramento(Form)
            self.conf_layout()
            if self.tela.help_sccrol_painel == True:
                self.frame.move(3, 172)
                self.frame_2.move(3, 133)
                self.frame_13.move(463, 24)
                self.tela.qt_int_ped2 += self.ocupado
                self.tela.qt_int_ped_total2 += self.total
                self.frame_6.hide()
                self.frame_20.hide()
                self.tela.qt_vagos_6leste = self.vago
                self.tela.total_bloq += self.bloqueado
                self.tela.total_vago += self.vago
                self.tela.total_rese += self.reservado
                self.tela.total_ocup += self.ocupado

    def atualizar_monitoramento(self, Form):
        self.vago = 0
        self.reservado = 0
        self.ocupado = 0
        self.bloqueado = 0
        self.total = 0
        colum_nome = 0
        colum_status = 0
        for colum in range(1, self.tela.tabela_grade.columnCount()):
            item_pac = self.tela.tabela_grade.horizontalHeaderItem(colum)
            if item_pac.text() == 'NOME DO PACIENTE':
                colum_nome = colum
            if item_pac.text() == 'STATUS DO LEITO':
                colum_status = colum
        for row in range(self.tela.conta_linha()):
            selecao = self.tela.item(row, colum_status)
            leitos = self.tela.leito(row)
            LEITOS = leitos.text()
            paciente = self.tela.item(row, colum_nome).text()
            self.total += 1
            if selecao.text() == 'VAGO':
                self.vago += 1
                for label in self.labels:
                    if label.text() == LEITOS:
                        label.setAlignment(Qt.AlignmentFlag.AlignCenter)
                        tooltip_text = 'Leito Vago'
                        label.setToolTip(tooltip_text)
            if selecao.text() == 'OCUPADO':
                for label in self.labels:
                    if label.text() == LEITOS:
                        label.setAlignment(Qt.AlignmentFlag.AlignCenter)
                        tooltip_text = f'Paciente: {paciente} \n Leito: {LEITOS}'
                        label.setToolTip(tooltip_text)
                        font = QtGui.QFont()
                        font.setBold(True)
                        font.setWeight(75)
                        label.setFont(font)
                        label.setStyleSheet('background-color: rgb(255, 0, 0);')
                self.ocupado += 1
            if selecao.text() == 'RESERVADO':
                for label in self.labels:
                    if label.text() == LEITOS:
                        label.setAlignment(Qt.AlignmentFlag.AlignCenter)
                        tooltip_text = f'Paciente: {paciente} \n Leito: {LEITOS}'
                        label.setToolTip(tooltip_text)
                        font = QtGui.QFont()
                        font.setBold(True)
                        font.setWeight(75)
                        label.setFont(font)
                        label.setStyleSheet('background-color: rgb(255, 255, 0);')
                self.reservado += 1
            if selecao.text() == 'BLOQUEADO':
                for label in self.labels:
                    if label.text() == LEITOS:
                        label.setAlignment(Qt.AlignmentFlag.AlignCenter)
                        tooltip_text = 'Leito Bloqueado'
                        label.setToolTip(tooltip_text)
                        font = QtGui.QFont()
                        font.setBold(True)
                        font.setWeight(75)
                        label.setFont(font)
                        label.setStyleSheet('background-color: rgb(170, 170, 255);')
                self.bloqueado += 1
            if self.tela.help_sccrol_painel == True:
                if selecao.text() == 'BLOQUEADO POR FALTA DE FUNCIONÁRIOS':
                    self.tela.qt_se_fun += 1
                    self.bloqueado += 1
                if selecao.text() == 'PONTUAL - BLOQUEADO POR FALTA DE FUNCIONÁRIOS':
                    self.tela.qt_pront += 1
                    self.bloqueado += 1
                if selecao.text() == 'BLOQUEADO POR MANUTENÇÃO':
                    self.tela.qt_bl_manu += 1
                    self.bloqueado += 1
                if selecao.text() == 'BLOQUEADO POR VM/VNI':
                    self.tela.qt_bl_VM_VNI += 1
                    self.bloqueado += 1
        self.retranslateUi(Form)

    def mousePressEvent(self, event, label):
        label.mouse_offset = event.pos()

    def mouseMoveEvent(self, event, label):
        if event.buttons() == Qt.MouseButton.LeftButton:
            new_pos = label.mapToParent(event.pos() - label.mouse_offset)
            label.move(new_pos)
            x, y = (new_pos.x(), new_pos.y())
            if not self.tela.help_sccrol_painel == True:
                frame = self.tela.frame_do_monitoramento
            else:  # inserted
                frame = self.frame_tela
            if frame:
                frame_rect = frame.rect()
                new_pos.setX(max(frame_rect.left(), min(new_pos.x(), frame_rect.right() - label.width())))
                new_pos.setY(max(frame_rect.top(), min(new_pos.y(), frame_rect.bottom() - label.height())))
                label.move(new_pos)
        filename = 'monitora_sexto_leste.csv'
        if self.tela.help_sccrol_painel == True:
            filename = 'monitora_sexto_lestepainel.csv'
        with open(filename, mode='w', newline='') as file:
            writer = csv.writer(file)
            for lisa in self.labels:
                texto = lisa.text()
                posicao = lisa.pos()
                writer.writerow([texto, posicao.x(), posicao.y()])

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate('Form', 'POSTO'))
        self.label_ocupado2_3.setText(_translate('Form', 'OCUPADO'))
        self.label_bloqueado2_3.setText(_translate('Form', 'BLOQUEADO'))
        self.label_vago2_3.setText(_translate('Form', 'VAGO'))
        self.label_reservado2_3.setText(_translate('Form', 'RESERVADO'))
        self.legenda_3.setText(_translate('Form', 'LEGENDA :'))
        self.label_ocupado1_3.setText(_translate('Form', 'OCUPADO :'))
        self.label_tabela_3.setText(_translate('Form', 'TABELA :'))
        vago = str(self.vago)
        reservado = str(self.reservado)
        bloqueado = str(self.bloqueado)
        ocupado = str(self.ocupado)
        self.qt_vago_3.setText(_translate('Form', vago))
        self.label_bloq1_3.setText(_translate('Form', 'BLOQUEADO :'))
        self.qt_reservado_3.setText(_translate('Form', reservado))
        self.qt_bloqueado_3.setText(_translate('Form', bloqueado))
        self.label_reser1_3.setText(_translate('Form', 'RESERVADO :'))
        self.qt_ocupado_3.setText(_translate('Form', ocupado))
        self.label_vago1_3.setText(_translate('Form', 'VAGO :'))

    def conf_layout(self):
        if self.settings.contains('tema'):
            font_name = self.settings.value('font', defaultValue='')
            backcolocor = self.settings.value('tema', defaultValue='')
            color = self.settings.value('color', defaultValue='')
            tamanho = int(self.settings.value('tamanho', defaultValue=10))
            self.backcolocor = backcolocor
            self.color = color
            self.font = font_name
            self.tamanho = tamanho
            if not self.tela.help_sccrol_painel == True:
                self.tela.frame_do_monitoramento.setStyleSheet('QFrame { background-color: transparent; border: 1px solid black; border-radius: 10px; box-shadow: 5px 5px 5px grey; }')