import csv
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QRect, Qt, QSettings, QStandardPaths, Qt
from PyQt6.QtWidgets import QLabel
from PyQt6.QtGui import QFont

class Ui_Form(object):
    def setupUi(self, Form, frame, tela):
        self.tela = tela
        self.frame_2 = frame
        self.settings = QSettings('HC', 'SGL')
        self.form = Form
        script_directory = QStandardPaths.writableLocation(QStandardPaths.StandardLocation.AppDataLocation)
        config_file_path = f'{script_directory}/config.ini'
        self.settings = QSettings(config_file_path, QSettings.Format.IniFormat)
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(312, 40, 528, 380))
        self.frame_4.setStyleSheet('background-color: rgb(255, 255, 255);border: 1px solid black; border-radius: 10px;')
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName('frame_4')
        self.parede1_3 = QtWidgets.QLabel(parent=self.frame_4)
        self.parede1_3.setGeometry(QtCore.QRect(0, 70, 215, 3))
        self.parede1_3.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.parede1_3.setText('')
        self.parede1_3.setObjectName('parede1_3')
        self.parede2_3 = QtWidgets.QLabel(parent=self.frame_4)
        self.parede2_3.setGeometry(QtCore.QRect(170, 240, 3, 141))
        self.parede2_3.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.parede2_3.setText('')
        self.parede2_3.setObjectName('parede2_3')
        self.parede1_5 = QtWidgets.QLabel(parent=self.frame_4)
        self.parede1_5.setGeometry(QtCore.QRect(232, 190, 125, 3))
        self.parede1_5.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.parede1_5.setText('')
        self.parede1_5.setObjectName('parede1_5')
        self.parede1_8 = QtWidgets.QLabel(parent=self.frame_4)
        self.parede1_8.setGeometry(QtCore.QRect(263, 158, 92, 3))
        self.parede1_8.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.parede1_8.setText('')
        self.parede1_8.setObjectName('parede1_8')
        self.parede2_4 = QtWidgets.QLabel(parent=self.frame_4)
        self.parede2_4.setGeometry(QtCore.QRect(231, 122, 3, 71))
        self.parede2_4.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.parede2_4.setText('')
        self.parede2_4.setObjectName('parede2_4')
        self.parede2_5 = QtWidgets.QLabel(parent=self.frame_4)
        self.parede2_5.setGeometry(QtCore.QRect(260, 90, 3, 101))
        self.parede2_5.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.parede2_5.setText('')
        self.parede2_5.setObjectName('parede2_5')
        self.posto_2 = QtWidgets.QLabel(parent=self.frame_4)
        self.posto_2.setGeometry(QtCore.QRect(316, 0, 40, 70))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.posto_2.setFont(font)
        self.posto_2.setAutoFillBackground(False)
        self.posto_2.setStyleSheet('background-color: rgb(0, 0, 0);\nbackground-color: rgb(127, 127, 127);')
        self.posto_2.setWordWrap(False)
        self.posto_2.setObjectName('posto_2')
        self.parede1_9 = QtWidgets.QLabel(parent=self.frame_4)
        self.parede1_9.setGeometry(QtCore.QRect(262, 123, 93, 3))
        self.parede1_9.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.parede1_9.setText('')
        self.parede1_9.setObjectName('parede1_9')
        self.parede1_11 = QtWidgets.QLabel(parent=self.frame_4)
        self.parede1_11.setGeometry(QtCore.QRect(257, 70, 101, 3))
        self.parede1_11.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.parede1_11.setText('')
        self.parede1_11.setObjectName('parede1_11')
        self.parede2_6 = QtWidgets.QLabel(parent=self.frame_4)
        self.parede2_6.setGeometry(QtCore.QRect(170, 70, 3, 141))
        self.parede2_6.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.parede2_6.setText('')
        self.parede2_6.setObjectName('parede2_6')
        self.posto_3 = QtWidgets.QLabel(parent=self.frame_4)
        self.posto_3.setGeometry(QtCore.QRect(190, 240, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.posto_3.setFont(font)
        self.posto_3.setAutoFillBackground(False)
        self.posto_3.setStyleSheet('background-color: rgb(0, 0, 0);\nbackground-color: rgb(127, 127, 127);')
        self.posto_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.posto_3.setWordWrap(False)
        self.posto_3.setObjectName('posto_3')
        self.parede1_6 = QtWidgets.QLabel(parent=self.frame_4)
        self.parede1_6.setGeometry(QtCore.QRect(230, 90, 127, 3))
        self.parede1_6.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.parede1_6.setText('')
        self.parede1_6.setObjectName('parede1_6')
        self.line_6 = QtWidgets.QFrame(parent=self.frame_4)
        self.line_6.setGeometry(QtCore.QRect(84, 73, 3, 306))
        self.line_6.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_6.setObjectName('line_6')
        self.line_10 = QtWidgets.QFrame(parent=self.frame_4)
        self.line_10.setGeometry(QtCore.QRect(0, 35, 316, 3))
        self.line_10.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_10.setObjectName('line_10')
        self.line_13 = QtWidgets.QFrame(parent=self.frame_4)
        self.line_13.setGeometry(QtCore.QRect(70, 0, 4, 70))
        self.line_13.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_13.setObjectName('line_13')
        self.line_15 = QtWidgets.QFrame(parent=self.frame_4)
        self.line_15.setGeometry(QtCore.QRect(140, 0, 4, 70))
        self.line_15.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_15.setObjectName('line_15')
        self.line_16 = QtWidgets.QFrame(parent=self.frame_4)
        self.line_16.setGeometry(QtCore.QRect(210, 0, 4, 70))
        self.line_16.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_16.setObjectName('line_16')
        self.line_9 = QtWidgets.QFrame(parent=self.frame_4)
        self.line_9.setGeometry(QtCore.QRect(0, 104, 170, 4))
        self.line_9.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_9.setObjectName('line_9')
        self.line_17 = QtWidgets.QFrame(parent=self.frame_4)
        self.line_17.setGeometry(QtCore.QRect(0, 195, 170, 4))
        self.line_17.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_17.setObjectName('line_17')
        self.line_18 = QtWidgets.QFrame(parent=self.frame_4)
        self.line_18.setGeometry(QtCore.QRect(0, 164, 170, 4))
        self.line_18.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_18.setObjectName('line_18')
        self.line_19 = QtWidgets.QFrame(parent=self.frame_4)
        self.line_19.setGeometry(QtCore.QRect(0, 134, 170, 4))
        self.line_19.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_19.setObjectName('line_19')
        self.line_20 = QtWidgets.QFrame(parent=self.frame_4)
        self.line_20.setGeometry(QtCore.QRect(1, 253, 169, 4))
        self.line_20.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_20.setObjectName('line_20')
        self.line_24 = QtWidgets.QFrame(parent=self.frame_4)
        self.line_24.setGeometry(QtCore.QRect(0, 224, 84, 3))
        self.line_24.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_24.setObjectName('line_24')
        self.label = QtWidgets.QLabel(parent=self.frame_4)
        self.label.setGeometry(QtCore.QRect(400, 327, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName('label')
        self.line_22 = QtWidgets.QFrame(parent=self.frame_4)
        self.line_22.setGeometry(QtCore.QRect(0, 286, 170, 4))
        self.line_22.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_22.setObjectName('line_22')
        self.line_21 = QtWidgets.QFrame(parent=self.frame_4)
        self.line_21.setGeometry(QtCore.QRect(0, 314, 170, 4))
        self.line_21.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_21.setObjectName('line_21')
        self.line_23 = QtWidgets.QFrame(parent=self.frame_4)
        self.line_23.setGeometry(QtCore.QRect(0, 344, 170, 4))
        self.line_23.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_23.setObjectName('line_23')
        self.parede1_46 = QtWidgets.QLabel(parent=self.frame_4)
        self.parede1_46.setGeometry(QtCore.QRect(359, 280, 171, 3))
        self.parede1_46.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.parede1_46.setText('')
        self.parede1_46.setObjectName('parede1_46')
        self.parede5_5 = QtWidgets.QLabel(parent=self.frame_4)
        self.parede5_5.setGeometry(QtCore.QRect(356, 0, 3, 378))
        self.parede5_5.setStyleSheet('background-color: rgb(0, 0, 0);')
        self.parede5_5.setText('')
        self.parede5_5.setObjectName('parede5_5')
        self.frame_20 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_20.setGeometry(QtCore.QRect(850, 270, 147, 157))
        self.frame_20.setStyleSheet('background-color: rgb(255, 255, 255);\nborder: 2px solid #2E3D48')
        self.frame_20.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_20.setObjectName('frame_20')
        self.label_ocupado2_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.label_ocupado2_3.setGeometry(QtCore.QRect(40, 130, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_ocupado2_3.setFont(font)
        self.label_ocupado2_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_ocupado2_3.setObjectName('label_ocupado2_3')
        self.label_bloqueado2_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.label_bloqueado2_3.setGeometry(QtCore.QRect(40, 100, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_bloqueado2_3.setFont(font)
        self.label_bloqueado2_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_bloqueado2_3.setObjectName('label_bloqueado2_3')
        self.label_vago2_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.label_vago2_3.setGeometry(QtCore.QRect(40, 40, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_vago2_3.setFont(font)
        self.label_vago2_3.setStyleSheet('background-color: rgb(255, 255, 255);\nborder: transparent;')
        self.label_vago2_3.setObjectName('label_vago2_3')
        self.label_reservado2_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.label_reservado2_3.setGeometry(QtCore.QRect(40, 70, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_reservado2_3.setFont(font)
        self.label_reservado2_3.setStyleSheet('background-color: rgb(255, 255, 255);\nborder: transparent;')
        self.label_reservado2_3.setObjectName('label_reservado2_3')
        self.cor_legenda_red_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.cor_legenda_red_3.setGeometry(QtCore.QRect(10, 130, 21, 21))
        self.cor_legenda_red_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 0, 0);')
        self.cor_legenda_red_3.setText('')
        self.cor_legenda_red_3.setObjectName('cor_legenda_red_3')
        self.cor_b_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.cor_b_3.setGeometry(QtCore.QRect(10, 100, 21, 21))
        self.cor_b_3.setStyleSheet('\nborder: transparent;background-color: rgb(170, 170, 255);')
        self.cor_b_3.setText('')
        self.cor_b_3.setObjectName('cor_b_3')
        self.cor_legenda_blue_5 = QtWidgets.QLabel(parent=self.frame_20)
        self.cor_legenda_blue_5.setGeometry(QtCore.QRect(10, 40, 21, 21))
        self.cor_legenda_blue_5.setStyleSheet('background-color: rgb(170, 255, 255);\nborder-left-color: rgb(0, 0, 0);\nborder-bottom-color: rgb(0, 0, 0);\nborder-right-color: rgb(0, 0, 0);\nborder-right-color: rgb(0, 0, 0);\nborder-top-color: rgb(0, 0, 0);\nborder-color: rgb(0, 0, 0);\nborder: transparent;')
        self.cor_legenda_blue_5.setText('')
        self.cor_legenda_blue_5.setObjectName('cor_legenda_blue_5')
        self.legenda_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.legenda_3.setGeometry(QtCore.QRect(10, 10, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.legenda_3.setFont(font)
        self.legenda_3.setStyleSheet('background-color: rgb(255, 255, 255);\nborder: transparent;')
        self.legenda_3.setObjectName('legenda_3')
        self.cor_legenda_yellow_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.cor_legenda_yellow_3.setGeometry(QtCore.QRect(10, 70, 21, 21))
        self.cor_legenda_yellow_3.setStyleSheet('\nborder: transparent;\nbackground-color: rgb(255, 255, 0);')
        self.cor_legenda_yellow_3.setText('')
        self.cor_legenda_yellow_3.setObjectName('cor_legenda_yellow_3')
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_6.setGeometry(QtCore.QRect(850, 100, 199, 161))
        self.frame_6.setStyleSheet('background-color: rgb(255, 255, 255);\nborder: 2px solid #2E3D48')
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName('frame_6')
        self.label_ocupado1_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_ocupado1_3.setGeometry(QtCore.QRect(10, 130, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_ocupado1_3.setFont(font)
        self.label_ocupado1_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_ocupado1_3.setObjectName('label_ocupado1_3')
        self.label_tabela_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_tabela_3.setGeometry(QtCore.QRect(10, 10, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_tabela_3.setFont(font)
        self.label_tabela_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_tabela_3.setObjectName('label_tabela_3')
        self.qt_vago_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.qt_vago_3.setGeometry(QtCore.QRect(130, 40, 61, 21))
        font = QtGui.QFont()
        self.qt_vago_3.setFont(font)
        self.qt_vago_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.qt_vago_3.setObjectName('qt_vago_3')
        self.label_bloq1_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_bloq1_3.setGeometry(QtCore.QRect(10, 100, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_bloq1_3.setFont(font)
        self.label_bloq1_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_bloq1_3.setObjectName('label_bloq1_3')
        self.qt_reservado_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.qt_reservado_3.setGeometry(QtCore.QRect(130, 70, 61, 21))
        font = QtGui.QFont()
        self.qt_reservado_3.setFont(font)
        self.qt_reservado_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.qt_reservado_3.setObjectName('qt_reservado_3')
        self.qt_bloqueado_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.qt_bloqueado_3.setGeometry(QtCore.QRect(130, 100, 61, 21))
        font = QtGui.QFont()
        self.qt_bloqueado_3.setFont(font)
        self.qt_bloqueado_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.qt_bloqueado_3.setObjectName('qt_bloqueado_3')
        self.label_reser1_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_reser1_3.setGeometry(QtCore.QRect(10, 70, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_reser1_3.setFont(font)
        self.label_reser1_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_reser1_3.setObjectName('label_reser1_3')
        self.qt_ocupado_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.qt_ocupado_3.setGeometry(QtCore.QRect(130, 130, 61, 21))
        font = QtGui.QFont()
        self.qt_ocupado_3.setFont(font)
        self.qt_ocupado_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.qt_ocupado_3.setObjectName('qt_ocupado_3')
        self.label_vago1_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_vago1_3.setGeometry(QtCore.QRect(10, 40, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_vago1_3.setFont(font)
        self.label_vago1_3.setStyleSheet('\nborder: transparent;background-color: rgb(255, 255, 255);')
        self.label_vago1_3.setObjectName('label_vago1_3')
        self.labels = []
        print(16)
        for row in range(1, 33):
            label = QLabel(f'Leito {row}', self.frame_4)
            label.setGeometry(0, 20, 60, 25)
            filename = 'monitora_neo_painel.csv'

            try:
                with open(filename, mode='r') as file:
                    reader = csv.reader(file)
                    data = list(reader)
                    for data_row in range(len(data)):
                        if data[data_row][0] == f'Leito {row}':
                            x = int(data[data_row][1])
                            y = int(data[data_row][2])
                            label.setGeometry(x, y, 70, 25)
                            break
            except FileNotFoundError:
                print("File not found:", filename)

            label.setAlignment(Qt.AlignmentFlag.AlignCenter)
            label.setCursor(Qt.CursorShape.OpenHandCursor)
            label.mousePressEvent = lambda event, label=label: self.mousePressEvent(event, label)
            label.mouseMoveEvent = lambda event, label=label: self.mouseMoveEvent(event, label)
            label.setWordWrap(True)
            fonte = QFont()
            fonte.setPointSize(10)
            label.setFont(fonte)
            label.setStyleSheet('background-color: rgb(170, 255, 255);border: 1px solid black; border-radius: 10px;')
            self.labels.append(label)
            label.setAlignment(Qt.AlignmentFlag.AlignCenter)
            tooltip_text = f'Leito {row}'
            label.setToolTip(tooltip_text)
        else:
            self.conf_layout()
            self.frame_4.move(80, 60)
            self.retranslateUi(Form)

    def mousePressEvent(self, event, label):
        label.mouse_offset = event.pos()

    def mouseMoveEvent(self, event, label):
        if event.buttons() == Qt.MouseButton.LeftButton:
            new_pos = label.mapToParent(event.pos() - label.mouse_offset)
            label.move(new_pos)
            x, y = (new_pos.x(), new_pos.y())
            frame = self.frame_4
            print(y)
            if frame:
                frame_rect = frame.rect()
                new_pos.setX(max(frame_rect.left(), min(new_pos.x(), frame_rect.right() - label.width())))
                new_pos.setY(max(frame_rect.top(), min(new_pos.y(), frame_rect.bottom() - label.height())))
                label.move(new_pos)
        filename = 'monitora_neo_painel.csv'
        with open(filename, mode='w', newline='') as file:
            writer = csv.writer(file)
            for lisa in self.labels:
                texto = lisa.text()
                posicao = lisa.pos()
                writer.writerow([texto, posicao.x(), posicao.y()])

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.posto_2.setText(_translate('Form', 'POSTO'))
        self.posto_3.setText(_translate('Form', 'POSTO'))
        self.label.setText(_translate('Form', 'CANGURU'))
        self.label_tabela_3.setText(_translate('Form', 'TABELA :'))
        self.label_ocupado1_3.setText(_translate('Form', 'OCUPADO :'))
        self.label_vago1_3.setText(_translate('Form', 'VAGO :'))
        self.label_reser1_3.setText(_translate('Form', 'RESERVADO :'))
        self.label_bloq1_3.setText(_translate('Form', 'BLOQUEADO :'))
        self.legenda_3.setText(_translate('Form', 'LEGENDA :'))
        self.label_ocupado2_3.setText(_translate('Form', 'OCUPADO'))
        self.label_reservado2_3.setText(_translate('Form', 'RESERVADO'))
        self.label_vago2_3.setText(_translate('Form', 'VAGO'))
        self.label_bloqueado2_3.setText(_translate('Form', 'BLOQUEADO'))

    def conf_layout(self):
        if self.settings.contains('tema'):
            font_name = self.settings.value('font', defaultValue='')
            backcolocor = self.settings.value('tema', defaultValue='')
            color = self.settings.value('color', defaultValue='')
            tamanho = int(self.settings.value('tamanho', defaultValue=10))
            self.backcolocor = backcolocor
            self.color = color
            self.font = font_name
            self.tamanho = tamanho
            self.tela.frame_do_monitoramento.setStyleSheet('QFrame { background-color: transparent; border: 1px solid black; border-radius: 10px; box-shadow: 5px 5px 5px grey; }')